/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activiteit.ActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie.ScenarioSessiePath;
import nl.tudelft.simulation.lcms.data.tables.records.ActiviteitTypeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActiviteitType extends TableImpl<ActiviteitTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.activiteit_type</code>
     */
    public static final ActiviteitType ACTIVITEIT_TYPE = new ActiviteitType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActiviteitTypeRecord> getRecordType() {
        return ActiviteitTypeRecord.class;
    }

    /**
     * The column <code>lcms.activiteit_type.id</code>.
     */
    public final TableField<ActiviteitTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.activiteit_type.scenario_sessie_id</code>.
     */
    public final TableField<ActiviteitTypeRecord, Integer> SCENARIO_SESSIE_ID = createField(DSL.name("scenario_sessie_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit_type.naam</code>.
     */
    public final TableField<ActiviteitTypeRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private ActiviteitType(Name alias, Table<ActiviteitTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ActiviteitType(Name alias, Table<ActiviteitTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.activiteit_type</code> table reference
     */
    public ActiviteitType(String alias) {
        this(DSL.name(alias), ACTIVITEIT_TYPE);
    }

    /**
     * Create an aliased <code>lcms.activiteit_type</code> table reference
     */
    public ActiviteitType(Name alias) {
        this(alias, ACTIVITEIT_TYPE);
    }

    /**
     * Create a <code>lcms.activiteit_type</code> table reference
     */
    public ActiviteitType() {
        this(DSL.name("activiteit_type"), null);
    }

    public <O extends Record> ActiviteitType(Table<O> path, ForeignKey<O, ActiviteitTypeRecord> childPath, InverseForeignKey<O, ActiviteitTypeRecord> parentPath) {
        super(path, childPath, parentPath, ACTIVITEIT_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActiviteitTypePath extends ActiviteitType implements Path<ActiviteitTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ActiviteitTypePath(Table<O> path, ForeignKey<O, ActiviteitTypeRecord> childPath, InverseForeignKey<O, ActiviteitTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActiviteitTypePath(Name alias, Table<ActiviteitTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActiviteitTypePath as(String alias) {
            return new ActiviteitTypePath(DSL.name(alias), this);
        }

        @Override
        public ActiviteitTypePath as(Name alias) {
            return new ActiviteitTypePath(alias, this);
        }

        @Override
        public ActiviteitTypePath as(Table<?> alias) {
            return new ActiviteitTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACTIVITEIT_TYPE_FK_ACTIVITEIT_TYPE_SCENARIO_SESSIE1_IDX);
    }

    @Override
    public Identity<ActiviteitTypeRecord, Integer> getIdentity() {
        return (Identity<ActiviteitTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActiviteitTypeRecord> getPrimaryKey() {
        return Keys.KEY_ACTIVITEIT_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActiviteitTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACTIVITEIT_TYPE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ActiviteitTypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ACTIVITEIT_TYPE_SCENARIO_SESSIE1);
    }

    private transient ScenarioSessiePath _scenarioSessie;

    /**
     * Get the implicit join path to the <code>lcms.scenario_sessie</code>
     * table.
     */
    public ScenarioSessiePath scenarioSessie() {
        if (_scenarioSessie == null)
            _scenarioSessie = new ScenarioSessiePath(this, Keys.FK_ACTIVITEIT_TYPE_SCENARIO_SESSIE1, null);

        return _scenarioSessie;
    }

    private transient ActiviteitPath _activiteit;

    /**
     * Get the implicit to-many join path to the <code>lcms.activiteit</code>
     * table
     */
    public ActiviteitPath activiteit() {
        if (_activiteit == null)
            _activiteit = new ActiviteitPath(this, null, Keys.FK_ACTIVITEIT_ACTIVITEIT_TYPE1.getInverseKey());

        return _activiteit;
    }

    @Override
    public ActiviteitType as(String alias) {
        return new ActiviteitType(DSL.name(alias), this);
    }

    @Override
    public ActiviteitType as(Name alias) {
        return new ActiviteitType(alias, this);
    }

    @Override
    public ActiviteitType as(Table<?> alias) {
        return new ActiviteitType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiviteitType rename(String name) {
        return new ActiviteitType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiviteitType rename(Name name) {
        return new ActiviteitType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiviteitType rename(Table<?> name) {
        return new ActiviteitType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType where(Condition condition) {
        return new ActiviteitType(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiviteitType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiviteitType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiviteitType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiviteitType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiviteitType whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
