/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.ActiviteitType.ActiviteitTypePath;
import nl.tudelft.simulation.lcms.data.tables.BetrokkenOrganisatie.BetrokkenOrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.Bijlage.BijlagePath;
import nl.tudelft.simulation.lcms.data.tables.GebruikerActiviteit.GebruikerActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.Opschaling.OpschalingPath;
import nl.tudelft.simulation.lcms.data.tables.Organisatie.OrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.Veld.VeldPath;
import nl.tudelft.simulation.lcms.data.tables.records.ActiviteitRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Activiteit extends TableImpl<ActiviteitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.activiteit</code>
     */
    public static final Activiteit ACTIVITEIT = new Activiteit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActiviteitRecord> getRecordType() {
        return ActiviteitRecord.class;
    }

    /**
     * The column <code>lcms.activiteit.id</code>.
     */
    public final TableField<ActiviteitRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.activiteit.naam</code>.
     */
    public final TableField<ActiviteitRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.locatie</code>.
     */
    public final TableField<ActiviteitRecord, String> LOCATIE = createField(DSL.name("locatie"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.organisatie_id</code>. eigenaar
     */
    public final TableField<ActiviteitRecord, Integer> ORGANISATIE_ID = createField(DSL.name("organisatie_id"), SQLDataType.INTEGER.nullable(false), this, "eigenaar");

    /**
     * The column <code>lcms.activiteit.opschaling_id</code>.
     */
    public final TableField<ActiviteitRecord, Integer> OPSCHALING_ID = createField(DSL.name("opschaling_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.activiteit_type_id</code>.
     */
    public final TableField<ActiviteitRecord, Integer> ACTIVITEIT_TYPE_ID = createField(DSL.name("activiteit_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.datum_aanmaak</code>.
     */
    public final TableField<ActiviteitRecord, LocalDateTime> DATUM_AANMAAK = createField(DSL.name("datum_aanmaak"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.datum_wijziging</code>.
     */
    public final TableField<ActiviteitRecord, LocalDateTime> DATUM_WIJZIGING = createField(DSL.name("datum_wijziging"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>lcms.activiteit.besloten</code>.
     */
    public final TableField<ActiviteitRecord, Byte> BESLOTEN = createField(DSL.name("besloten"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    private Activiteit(Name alias, Table<ActiviteitRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Activiteit(Name alias, Table<ActiviteitRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.activiteit</code> table reference
     */
    public Activiteit(String alias) {
        this(DSL.name(alias), ACTIVITEIT);
    }

    /**
     * Create an aliased <code>lcms.activiteit</code> table reference
     */
    public Activiteit(Name alias) {
        this(alias, ACTIVITEIT);
    }

    /**
     * Create a <code>lcms.activiteit</code> table reference
     */
    public Activiteit() {
        this(DSL.name("activiteit"), null);
    }

    public <O extends Record> Activiteit(Table<O> path, ForeignKey<O, ActiviteitRecord> childPath, InverseForeignKey<O, ActiviteitRecord> parentPath) {
        super(path, childPath, parentPath, ACTIVITEIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActiviteitPath extends Activiteit implements Path<ActiviteitRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ActiviteitPath(Table<O> path, ForeignKey<O, ActiviteitRecord> childPath, InverseForeignKey<O, ActiviteitRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActiviteitPath(Name alias, Table<ActiviteitRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActiviteitPath as(String alias) {
            return new ActiviteitPath(DSL.name(alias), this);
        }

        @Override
        public ActiviteitPath as(Name alias) {
            return new ActiviteitPath(alias, this);
        }

        @Override
        public ActiviteitPath as(Table<?> alias) {
            return new ActiviteitPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACTIVITEIT_FK_ACTIVITEIT_ACTIVITEIT_TYPE1_IDX, Indexes.ACTIVITEIT_FK_ACTIVITEIT_OPSCHALING1_IDX, Indexes.ACTIVITEIT_FK_ACTIVITEIT_ORGANISATIE1_IDX);
    }

    @Override
    public Identity<ActiviteitRecord, Integer> getIdentity() {
        return (Identity<ActiviteitRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActiviteitRecord> getPrimaryKey() {
        return Keys.KEY_ACTIVITEIT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActiviteitRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACTIVITEIT_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ActiviteitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ACTIVITEIT_ACTIVITEIT_TYPE1, Keys.FK_ACTIVITEIT_OPSCHALING1, Keys.FK_ACTIVITEIT_ORGANISATIE1);
    }

    private transient ActiviteitTypePath _activiteitType;

    /**
     * Get the implicit join path to the <code>lcms.activiteit_type</code>
     * table.
     */
    public ActiviteitTypePath activiteitType() {
        if (_activiteitType == null)
            _activiteitType = new ActiviteitTypePath(this, Keys.FK_ACTIVITEIT_ACTIVITEIT_TYPE1, null);

        return _activiteitType;
    }

    private transient OpschalingPath _opschaling;

    /**
     * Get the implicit join path to the <code>lcms.opschaling</code> table.
     */
    public OpschalingPath opschaling() {
        if (_opschaling == null)
            _opschaling = new OpschalingPath(this, Keys.FK_ACTIVITEIT_OPSCHALING1, null);

        return _opschaling;
    }

    private transient OrganisatiePath _organisatie;

    /**
     * Get the implicit join path to the <code>lcms.organisatie</code> table.
     */
    public OrganisatiePath organisatie() {
        if (_organisatie == null)
            _organisatie = new OrganisatiePath(this, Keys.FK_ACTIVITEIT_ORGANISATIE1, null);

        return _organisatie;
    }

    private transient BetrokkenOrganisatiePath _betrokkenOrganisatie;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.betrokken_organisatie</code> table
     */
    public BetrokkenOrganisatiePath betrokkenOrganisatie() {
        if (_betrokkenOrganisatie == null)
            _betrokkenOrganisatie = new BetrokkenOrganisatiePath(this, null, Keys.FK_BETROKKEN_ORGANISATIE_ACTIVITEIT1.getInverseKey());

        return _betrokkenOrganisatie;
    }

    private transient BijlagePath _bijlage;

    /**
     * Get the implicit to-many join path to the <code>lcms.bijlage</code> table
     */
    public BijlagePath bijlage() {
        if (_bijlage == null)
            _bijlage = new BijlagePath(this, null, Keys.FK_BIJLAGE_ACTIVITEIT1.getInverseKey());

        return _bijlage;
    }

    private transient GebruikerActiviteitPath _gebruikerActiviteit;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.gebruiker_activiteit</code> table
     */
    public GebruikerActiviteitPath gebruikerActiviteit() {
        if (_gebruikerActiviteit == null)
            _gebruikerActiviteit = new GebruikerActiviteitPath(this, null, Keys.FK_GEBRUIKER_ACTIVITEIT_ACTIVITEIT1.getInverseKey());

        return _gebruikerActiviteit;
    }

    private transient VeldPath _veld;

    /**
     * Get the implicit to-many join path to the <code>lcms.veld</code> table
     */
    public VeldPath veld() {
        if (_veld == null)
            _veld = new VeldPath(this, null, Keys.FK_VELD_ACTIVITEIT1.getInverseKey());

        return _veld;
    }

    @Override
    public Activiteit as(String alias) {
        return new Activiteit(DSL.name(alias), this);
    }

    @Override
    public Activiteit as(Name alias) {
        return new Activiteit(alias, this);
    }

    @Override
    public Activiteit as(Table<?> alias) {
        return new Activiteit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Activiteit rename(String name) {
        return new Activiteit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activiteit rename(Name name) {
        return new Activiteit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activiteit rename(Table<?> name) {
        return new Activiteit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit where(Condition condition) {
        return new Activiteit(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activiteit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activiteit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activiteit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activiteit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activiteit whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
