/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession.ScenarioSessionPath;
import nl.tudelft.simulation.lcms.data.tables.records.ActivityTypeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityType extends TableImpl<ActivityTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.activity_type</code>
     */
    public static final ActivityType ACTIVITY_TYPE = new ActivityType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityTypeRecord> getRecordType() {
        return ActivityTypeRecord.class;
    }

    /**
     * The column <code>lcms.activity_type.id</code>.
     */
    public final TableField<ActivityTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.activity_type.name</code>.
     */
    public final TableField<ActivityTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.activity_type.scenario_session_id</code>.
     */
    public final TableField<ActivityTypeRecord, Integer> SCENARIO_SESSION_ID = createField(DSL.name("scenario_session_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ActivityType(Name alias, Table<ActivityTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ActivityType(Name alias, Table<ActivityTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.activity_type</code> table reference
     */
    public ActivityType(String alias) {
        this(DSL.name(alias), ACTIVITY_TYPE);
    }

    /**
     * Create an aliased <code>lcms.activity_type</code> table reference
     */
    public ActivityType(Name alias) {
        this(alias, ACTIVITY_TYPE);
    }

    /**
     * Create a <code>lcms.activity_type</code> table reference
     */
    public ActivityType() {
        this(DSL.name("activity_type"), null);
    }

    public <O extends Record> ActivityType(Table<O> path, ForeignKey<O, ActivityTypeRecord> childPath, InverseForeignKey<O, ActivityTypeRecord> parentPath) {
        super(path, childPath, parentPath, ACTIVITY_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActivityTypePath extends ActivityType implements Path<ActivityTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ActivityTypePath(Table<O> path, ForeignKey<O, ActivityTypeRecord> childPath, InverseForeignKey<O, ActivityTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActivityTypePath(Name alias, Table<ActivityTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActivityTypePath as(String alias) {
            return new ActivityTypePath(DSL.name(alias), this);
        }

        @Override
        public ActivityTypePath as(Name alias) {
            return new ActivityTypePath(alias, this);
        }

        @Override
        public ActivityTypePath as(Table<?> alias) {
            return new ActivityTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACTIVITY_TYPE_FK_ACTIVITY_TYPE_SCENARIO_SESSION1_IDX);
    }

    @Override
    public Identity<ActivityTypeRecord, Integer> getIdentity() {
        return (Identity<ActivityTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActivityTypeRecord> getPrimaryKey() {
        return Keys.KEY_ACTIVITY_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActivityTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACTIVITY_TYPE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ActivityTypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ACTIVITY_TYPE_SCENARIO_SESSION1);
    }

    private transient ScenarioSessionPath _scenarioSession;

    /**
     * Get the implicit join path to the <code>lcms.scenario_session</code>
     * table.
     */
    public ScenarioSessionPath scenarioSession() {
        if (_scenarioSession == null)
            _scenarioSession = new ScenarioSessionPath(this, Keys.FK_ACTIVITY_TYPE_SCENARIO_SESSION1, null);

        return _scenarioSession;
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit to-many join path to the <code>lcms.activity</code>
     * table
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, null, Keys.FK_ACTIVITY_ACTIVITY_TYPE1.getInverseKey());

        return _activity;
    }

    @Override
    public ActivityType as(String alias) {
        return new ActivityType(DSL.name(alias), this);
    }

    @Override
    public ActivityType as(Name alias) {
        return new ActivityType(alias, this);
    }

    @Override
    public ActivityType as(Table<?> alias) {
        return new ActivityType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityType rename(String name) {
        return new ActivityType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityType rename(Name name) {
        return new ActivityType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityType rename(Table<?> name) {
        return new ActivityType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType where(Condition condition) {
        return new ActivityType(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityType whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
