/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.ActivityType.ActivityTypePath;
import nl.tudelft.simulation.lcms.data.tables.Appendix.AppendixPath;
import nl.tudelft.simulation.lcms.data.tables.Field.FieldPath;
import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation.InvolvedOrganisationPath;
import nl.tudelft.simulation.lcms.data.tables.Organisation.OrganisationPath;
import nl.tudelft.simulation.lcms.data.tables.Severity.SeverityPath;
import nl.tudelft.simulation.lcms.data.tables.UserActivity.UserActivityPath;
import nl.tudelft.simulation.lcms.data.tables.records.ActivityRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Activity extends TableImpl<ActivityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.activity</code>
     */
    public static final Activity ACTIVITY = new Activity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityRecord> getRecordType() {
        return ActivityRecord.class;
    }

    /**
     * The column <code>lcms.activity.id</code>.
     */
    public final TableField<ActivityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.activity.name</code>.
     */
    public final TableField<ActivityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>lcms.activity.location</code>.
     */
    public final TableField<ActivityRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.activity.date_created</code>.
     */
    public final TableField<ActivityRecord, LocalDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>lcms.activity.date_changed</code>.
     */
    public final TableField<ActivityRecord, LocalDateTime> DATE_CHANGED = createField(DSL.name("date_changed"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>lcms.activity.closed</code>.
     */
    public final TableField<ActivityRecord, Byte> CLOSED = createField(DSL.name("closed"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>lcms.activity.activity_type_id</code>.
     */
    public final TableField<ActivityRecord, Integer> ACTIVITY_TYPE_ID = createField(DSL.name("activity_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.activity.organisation_id</code>.
     */
    public final TableField<ActivityRecord, Integer> ORGANISATION_ID = createField(DSL.name("organisation_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.activity.severity_id</code>.
     */
    public final TableField<ActivityRecord, Integer> SEVERITY_ID = createField(DSL.name("severity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Activity(Name alias, Table<ActivityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Activity(Name alias, Table<ActivityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.activity</code> table reference
     */
    public Activity(String alias) {
        this(DSL.name(alias), ACTIVITY);
    }

    /**
     * Create an aliased <code>lcms.activity</code> table reference
     */
    public Activity(Name alias) {
        this(alias, ACTIVITY);
    }

    /**
     * Create a <code>lcms.activity</code> table reference
     */
    public Activity() {
        this(DSL.name("activity"), null);
    }

    public <O extends Record> Activity(Table<O> path, ForeignKey<O, ActivityRecord> childPath, InverseForeignKey<O, ActivityRecord> parentPath) {
        super(path, childPath, parentPath, ACTIVITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActivityPath extends Activity implements Path<ActivityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ActivityPath(Table<O> path, ForeignKey<O, ActivityRecord> childPath, InverseForeignKey<O, ActivityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActivityPath(Name alias, Table<ActivityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActivityPath as(String alias) {
            return new ActivityPath(DSL.name(alias), this);
        }

        @Override
        public ActivityPath as(Name alias) {
            return new ActivityPath(alias, this);
        }

        @Override
        public ActivityPath as(Table<?> alias) {
            return new ActivityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACTIVITY_FK_ACTIVITY_ACTIVITY_TYPE1_IDX, Indexes.ACTIVITY_FK_ACTIVITY_ORGANISATION1_IDX, Indexes.ACTIVITY_FK_ACTIVITY_SEVERITY1_IDX);
    }

    @Override
    public Identity<ActivityRecord, Integer> getIdentity() {
        return (Identity<ActivityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActivityRecord> getPrimaryKey() {
        return Keys.KEY_ACTIVITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActivityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACTIVITY_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ActivityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ACTIVITY_ACTIVITY_TYPE1, Keys.FK_ACTIVITY_ORGANISATION1, Keys.FK_ACTIVITY_SEVERITY1);
    }

    private transient ActivityTypePath _activityType;

    /**
     * Get the implicit join path to the <code>lcms.activity_type</code> table.
     */
    public ActivityTypePath activityType() {
        if (_activityType == null)
            _activityType = new ActivityTypePath(this, Keys.FK_ACTIVITY_ACTIVITY_TYPE1, null);

        return _activityType;
    }

    private transient OrganisationPath _organisation;

    /**
     * Get the implicit join path to the <code>lcms.organisation</code> table.
     */
    public OrganisationPath organisation() {
        if (_organisation == null)
            _organisation = new OrganisationPath(this, Keys.FK_ACTIVITY_ORGANISATION1, null);

        return _organisation;
    }

    private transient SeverityPath _severity;

    /**
     * Get the implicit join path to the <code>lcms.severity</code> table.
     */
    public SeverityPath severity() {
        if (_severity == null)
            _severity = new SeverityPath(this, Keys.FK_ACTIVITY_SEVERITY1, null);

        return _severity;
    }

    private transient AppendixPath _appendix;

    /**
     * Get the implicit to-many join path to the <code>lcms.appendix</code>
     * table
     */
    public AppendixPath appendix() {
        if (_appendix == null)
            _appendix = new AppendixPath(this, null, Keys.FK_APPENDIX_ACTIVITY1.getInverseKey());

        return _appendix;
    }

    private transient FieldPath _field;

    /**
     * Get the implicit to-many join path to the <code>lcms.field</code> table
     */
    public FieldPath field() {
        if (_field == null)
            _field = new FieldPath(this, null, Keys.FK_FIELD_ACTIVITY1.getInverseKey());

        return _field;
    }

    private transient InvolvedOrganisationPath _involvedOrganisation;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.involved_organisation</code> table
     */
    public InvolvedOrganisationPath involvedOrganisation() {
        if (_involvedOrganisation == null)
            _involvedOrganisation = new InvolvedOrganisationPath(this, null, Keys.FK_INVOLVED_ORGANIZATION_ACTIVITY1.getInverseKey());

        return _involvedOrganisation;
    }

    private transient UserActivityPath _userActivity;

    /**
     * Get the implicit to-many join path to the <code>lcms.user_activity</code>
     * table
     */
    public UserActivityPath userActivity() {
        if (_userActivity == null)
            _userActivity = new UserActivityPath(this, null, Keys.FK_USER_ACTIVITY_ACTIVITY1.getInverseKey());

        return _userActivity;
    }

    @Override
    public Activity as(String alias) {
        return new Activity(DSL.name(alias), this);
    }

    @Override
    public Activity as(Name alias) {
        return new Activity(alias, this);
    }

    @Override
    public Activity as(Table<?> alias) {
        return new Activity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Activity rename(String name) {
        return new Activity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activity rename(Name name) {
        return new Activity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activity rename(Table<?> name) {
        return new Activity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity where(Condition condition) {
        return new Activity(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Activity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Activity whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
