/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.records.AppendixRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Appendix extends TableImpl<AppendixRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.appendix</code>
     */
    public static final Appendix APPENDIX = new Appendix();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppendixRecord> getRecordType() {
        return AppendixRecord.class;
    }

    /**
     * The column <code>lcms.appendix.id</code>.
     */
    public final TableField<AppendixRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.appendix.type</code>.
     */
    public final TableField<AppendixRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.appendix.content</code>.
     */
    public final TableField<AppendixRecord, byte[]> CONTENT = createField(DSL.name("content"), SQLDataType.BLOB(65535).nullable(false), this, "");

    /**
     * The column <code>lcms.appendix.activity_id</code>.
     */
    public final TableField<AppendixRecord, Integer> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Appendix(Name alias, Table<AppendixRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Appendix(Name alias, Table<AppendixRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.appendix</code> table reference
     */
    public Appendix(String alias) {
        this(DSL.name(alias), APPENDIX);
    }

    /**
     * Create an aliased <code>lcms.appendix</code> table reference
     */
    public Appendix(Name alias) {
        this(alias, APPENDIX);
    }

    /**
     * Create a <code>lcms.appendix</code> table reference
     */
    public Appendix() {
        this(DSL.name("appendix"), null);
    }

    public <O extends Record> Appendix(Table<O> path, ForeignKey<O, AppendixRecord> childPath, InverseForeignKey<O, AppendixRecord> parentPath) {
        super(path, childPath, parentPath, APPENDIX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppendixPath extends Appendix implements Path<AppendixRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppendixPath(Table<O> path, ForeignKey<O, AppendixRecord> childPath, InverseForeignKey<O, AppendixRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppendixPath(Name alias, Table<AppendixRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppendixPath as(String alias) {
            return new AppendixPath(DSL.name(alias), this);
        }

        @Override
        public AppendixPath as(Name alias) {
            return new AppendixPath(alias, this);
        }

        @Override
        public AppendixPath as(Table<?> alias) {
            return new AppendixPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.APPENDIX_FK_APPENDIX_ACTIVITY1_IDX);
    }

    @Override
    public Identity<AppendixRecord, Integer> getIdentity() {
        return (Identity<AppendixRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppendixRecord> getPrimaryKey() {
        return Keys.KEY_APPENDIX_PRIMARY;
    }

    @Override
    public List<UniqueKey<AppendixRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_APPENDIX_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<AppendixRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_APPENDIX_ACTIVITY1);
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit join path to the <code>lcms.activity</code> table.
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, Keys.FK_APPENDIX_ACTIVITY1, null);

        return _activity;
    }

    @Override
    public Appendix as(String alias) {
        return new Appendix(DSL.name(alias), this);
    }

    @Override
    public Appendix as(Name alias) {
        return new Appendix(alias, this);
    }

    @Override
    public Appendix as(Table<?> alias) {
        return new Appendix(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Appendix rename(String name) {
        return new Appendix(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Appendix rename(Name name) {
        return new Appendix(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Appendix rename(Table<?> name) {
        return new Appendix(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix where(Condition condition) {
        return new Appendix(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Appendix where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Appendix where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Appendix where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Appendix where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Appendix whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
