/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activiteit.ActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.Organisatie.OrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.records.BetrokkenOrganisatieRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BetrokkenOrganisatie extends TableImpl<BetrokkenOrganisatieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.betrokken_organisatie</code>
     */
    public static final BetrokkenOrganisatie BETROKKEN_ORGANISATIE = new BetrokkenOrganisatie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BetrokkenOrganisatieRecord> getRecordType() {
        return BetrokkenOrganisatieRecord.class;
    }

    /**
     * The column <code>lcms.betrokken_organisatie.id</code>.
     */
    public final TableField<BetrokkenOrganisatieRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.betrokken_organisatie.activiteit_id</code>.
     */
    public final TableField<BetrokkenOrganisatieRecord, Integer> ACTIVITEIT_ID = createField(DSL.name("activiteit_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.betrokken_organisatie.organisatie_id</code>.
     */
    public final TableField<BetrokkenOrganisatieRecord, Integer> ORGANISATIE_ID = createField(DSL.name("organisatie_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private BetrokkenOrganisatie(Name alias, Table<BetrokkenOrganisatieRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BetrokkenOrganisatie(Name alias, Table<BetrokkenOrganisatieRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.betrokken_organisatie</code> table reference
     */
    public BetrokkenOrganisatie(String alias) {
        this(DSL.name(alias), BETROKKEN_ORGANISATIE);
    }

    /**
     * Create an aliased <code>lcms.betrokken_organisatie</code> table reference
     */
    public BetrokkenOrganisatie(Name alias) {
        this(alias, BETROKKEN_ORGANISATIE);
    }

    /**
     * Create a <code>lcms.betrokken_organisatie</code> table reference
     */
    public BetrokkenOrganisatie() {
        this(DSL.name("betrokken_organisatie"), null);
    }

    public <O extends Record> BetrokkenOrganisatie(Table<O> path, ForeignKey<O, BetrokkenOrganisatieRecord> childPath, InverseForeignKey<O, BetrokkenOrganisatieRecord> parentPath) {
        super(path, childPath, parentPath, BETROKKEN_ORGANISATIE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BetrokkenOrganisatiePath extends BetrokkenOrganisatie implements Path<BetrokkenOrganisatieRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BetrokkenOrganisatiePath(Table<O> path, ForeignKey<O, BetrokkenOrganisatieRecord> childPath, InverseForeignKey<O, BetrokkenOrganisatieRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BetrokkenOrganisatiePath(Name alias, Table<BetrokkenOrganisatieRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BetrokkenOrganisatiePath as(String alias) {
            return new BetrokkenOrganisatiePath(DSL.name(alias), this);
        }

        @Override
        public BetrokkenOrganisatiePath as(Name alias) {
            return new BetrokkenOrganisatiePath(alias, this);
        }

        @Override
        public BetrokkenOrganisatiePath as(Table<?> alias) {
            return new BetrokkenOrganisatiePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BETROKKEN_ORGANISATIE_FK_BETROKKEN_ORGANISATIE_ACTIVITEIT1_IDX, Indexes.BETROKKEN_ORGANISATIE_FK_BETROKKEN_ORGANISATIE_ORGANISATIE1_IDX);
    }

    @Override
    public Identity<BetrokkenOrganisatieRecord, Integer> getIdentity() {
        return (Identity<BetrokkenOrganisatieRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BetrokkenOrganisatieRecord> getPrimaryKey() {
        return Keys.KEY_BETROKKEN_ORGANISATIE_PRIMARY;
    }

    @Override
    public List<UniqueKey<BetrokkenOrganisatieRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BETROKKEN_ORGANISATIE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<BetrokkenOrganisatieRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_BETROKKEN_ORGANISATIE_ACTIVITEIT1, Keys.FK_BETROKKEN_ORGANISATIE_ORGANISATIE1);
    }

    private transient ActiviteitPath _activiteit;

    /**
     * Get the implicit join path to the <code>lcms.activiteit</code> table.
     */
    public ActiviteitPath activiteit() {
        if (_activiteit == null)
            _activiteit = new ActiviteitPath(this, Keys.FK_BETROKKEN_ORGANISATIE_ACTIVITEIT1, null);

        return _activiteit;
    }

    private transient OrganisatiePath _organisatie;

    /**
     * Get the implicit join path to the <code>lcms.organisatie</code> table.
     */
    public OrganisatiePath organisatie() {
        if (_organisatie == null)
            _organisatie = new OrganisatiePath(this, Keys.FK_BETROKKEN_ORGANISATIE_ORGANISATIE1, null);

        return _organisatie;
    }

    @Override
    public BetrokkenOrganisatie as(String alias) {
        return new BetrokkenOrganisatie(DSL.name(alias), this);
    }

    @Override
    public BetrokkenOrganisatie as(Name alias) {
        return new BetrokkenOrganisatie(alias, this);
    }

    @Override
    public BetrokkenOrganisatie as(Table<?> alias) {
        return new BetrokkenOrganisatie(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BetrokkenOrganisatie rename(String name) {
        return new BetrokkenOrganisatie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BetrokkenOrganisatie rename(Name name) {
        return new BetrokkenOrganisatie(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BetrokkenOrganisatie rename(Table<?> name) {
        return new BetrokkenOrganisatie(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie where(Condition condition) {
        return new BetrokkenOrganisatie(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BetrokkenOrganisatie where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BetrokkenOrganisatie where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BetrokkenOrganisatie where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BetrokkenOrganisatie where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BetrokkenOrganisatie whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
