/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Profiel.ProfielPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie.ScenarioSessiePath;
import nl.tudelft.simulation.lcms.data.tables.records.DisciplineRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Discipline extends TableImpl<DisciplineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.discipline</code>
     */
    public static final Discipline DISCIPLINE = new Discipline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DisciplineRecord> getRecordType() {
        return DisciplineRecord.class;
    }

    /**
     * The column <code>lcms.discipline.id</code>.
     */
    public final TableField<DisciplineRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.discipline.scenario_sessie_id</code>.
     */
    public final TableField<DisciplineRecord, Integer> SCENARIO_SESSIE_ID = createField(DSL.name("scenario_sessie_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.discipline.naam</code>.
     */
    public final TableField<DisciplineRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private Discipline(Name alias, Table<DisciplineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Discipline(Name alias, Table<DisciplineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.discipline</code> table reference
     */
    public Discipline(String alias) {
        this(DSL.name(alias), DISCIPLINE);
    }

    /**
     * Create an aliased <code>lcms.discipline</code> table reference
     */
    public Discipline(Name alias) {
        this(alias, DISCIPLINE);
    }

    /**
     * Create a <code>lcms.discipline</code> table reference
     */
    public Discipline() {
        this(DSL.name("discipline"), null);
    }

    public <O extends Record> Discipline(Table<O> path, ForeignKey<O, DisciplineRecord> childPath, InverseForeignKey<O, DisciplineRecord> parentPath) {
        super(path, childPath, parentPath, DISCIPLINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DisciplinePath extends Discipline implements Path<DisciplineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DisciplinePath(Table<O> path, ForeignKey<O, DisciplineRecord> childPath, InverseForeignKey<O, DisciplineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DisciplinePath(Name alias, Table<DisciplineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DisciplinePath as(String alias) {
            return new DisciplinePath(DSL.name(alias), this);
        }

        @Override
        public DisciplinePath as(Name alias) {
            return new DisciplinePath(alias, this);
        }

        @Override
        public DisciplinePath as(Table<?> alias) {
            return new DisciplinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DISCIPLINE_FK_DISCIPLINE_SCENARIO_SESSIE1_IDX);
    }

    @Override
    public Identity<DisciplineRecord, Integer> getIdentity() {
        return (Identity<DisciplineRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DisciplineRecord> getPrimaryKey() {
        return Keys.KEY_DISCIPLINE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DisciplineRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DISCIPLINE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<DisciplineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DISCIPLINE_SCENARIO_SESSIE1);
    }

    private transient ScenarioSessiePath _scenarioSessie;

    /**
     * Get the implicit join path to the <code>lcms.scenario_sessie</code>
     * table.
     */
    public ScenarioSessiePath scenarioSessie() {
        if (_scenarioSessie == null)
            _scenarioSessie = new ScenarioSessiePath(this, Keys.FK_DISCIPLINE_SCENARIO_SESSIE1, null);

        return _scenarioSessie;
    }

    private transient ProfielPath _profiel;

    /**
     * Get the implicit to-many join path to the <code>lcms.profiel</code> table
     */
    public ProfielPath profiel() {
        if (_profiel == null)
            _profiel = new ProfielPath(this, null, Keys.FK_PROFIEL_DISCIPLINE1.getInverseKey());

        return _profiel;
    }

    @Override
    public Discipline as(String alias) {
        return new Discipline(DSL.name(alias), this);
    }

    @Override
    public Discipline as(Name alias) {
        return new Discipline(alias, this);
    }

    @Override
    public Discipline as(Table<?> alias) {
        return new Discipline(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Discipline rename(String name) {
        return new Discipline(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Discipline rename(Name name) {
        return new Discipline(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Discipline rename(Table<?> name) {
        return new Discipline(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline where(Condition condition) {
        return new Discipline(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discipline where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discipline where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discipline where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discipline where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discipline whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
