/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Organisation.OrganisationPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession.ScenarioSessionPath;
import nl.tudelft.simulation.lcms.data.tables.records.DomainRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Domain extends TableImpl<DomainRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.domain</code>
     */
    public static final Domain DOMAIN = new Domain();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DomainRecord> getRecordType() {
        return DomainRecord.class;
    }

    /**
     * The column <code>lcms.domain.id</code>.
     */
    public final TableField<DomainRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.domain.code</code>.
     */
    public final TableField<DomainRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.domain.name</code>.
     */
    public final TableField<DomainRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.domain.scenario_session_id</code>.
     */
    public final TableField<DomainRecord, Integer> SCENARIO_SESSION_ID = createField(DSL.name("scenario_session_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Domain(Name alias, Table<DomainRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Domain(Name alias, Table<DomainRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.domain</code> table reference
     */
    public Domain(String alias) {
        this(DSL.name(alias), DOMAIN);
    }

    /**
     * Create an aliased <code>lcms.domain</code> table reference
     */
    public Domain(Name alias) {
        this(alias, DOMAIN);
    }

    /**
     * Create a <code>lcms.domain</code> table reference
     */
    public Domain() {
        this(DSL.name("domain"), null);
    }

    public <O extends Record> Domain(Table<O> path, ForeignKey<O, DomainRecord> childPath, InverseForeignKey<O, DomainRecord> parentPath) {
        super(path, childPath, parentPath, DOMAIN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DomainPath extends Domain implements Path<DomainRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DomainPath(Table<O> path, ForeignKey<O, DomainRecord> childPath, InverseForeignKey<O, DomainRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DomainPath(Name alias, Table<DomainRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DomainPath as(String alias) {
            return new DomainPath(DSL.name(alias), this);
        }

        @Override
        public DomainPath as(Name alias) {
            return new DomainPath(alias, this);
        }

        @Override
        public DomainPath as(Table<?> alias) {
            return new DomainPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOMAIN_FK_DOMAIN_SCENARIO_SESSION1_IDX);
    }

    @Override
    public Identity<DomainRecord, Integer> getIdentity() {
        return (Identity<DomainRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DomainRecord> getPrimaryKey() {
        return Keys.KEY_DOMAIN_PRIMARY;
    }

    @Override
    public List<UniqueKey<DomainRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DOMAIN_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<DomainRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DOMAIN_SCENARIO_SESSION1);
    }

    private transient ScenarioSessionPath _scenarioSession;

    /**
     * Get the implicit join path to the <code>lcms.scenario_session</code>
     * table.
     */
    public ScenarioSessionPath scenarioSession() {
        if (_scenarioSession == null)
            _scenarioSession = new ScenarioSessionPath(this, Keys.FK_DOMAIN_SCENARIO_SESSION1, null);

        return _scenarioSession;
    }

    private transient OrganisationPath _organisation;

    /**
     * Get the implicit to-many join path to the <code>lcms.organisation</code>
     * table
     */
    public OrganisationPath organisation() {
        if (_organisation == null)
            _organisation = new OrganisationPath(this, null, Keys.FK_ORGANISATIE_DOMAIN1.getInverseKey());

        return _organisation;
    }

    @Override
    public Domain as(String alias) {
        return new Domain(DSL.name(alias), this);
    }

    @Override
    public Domain as(Name alias) {
        return new Domain(alias, this);
    }

    @Override
    public Domain as(Table<?> alias) {
        return new Domain(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Domain rename(String name) {
        return new Domain(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Domain rename(Name name) {
        return new Domain(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Domain rename(Table<?> name) {
        return new Domain(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain where(Condition condition) {
        return new Domain(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domain where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domain where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domain where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domain where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domain whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
