/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Organisatie.OrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie.ScenarioSessiePath;
import nl.tudelft.simulation.lcms.data.tables.records.DomeinRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Domein extends TableImpl<DomeinRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.domein</code>
     */
    public static final Domein DOMEIN = new Domein();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DomeinRecord> getRecordType() {
        return DomeinRecord.class;
    }

    /**
     * The column <code>lcms.domein.id</code>.
     */
    public final TableField<DomeinRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.domein.scenario_sessie_id</code>.
     */
    public final TableField<DomeinRecord, Integer> SCENARIO_SESSIE_ID = createField(DSL.name("scenario_sessie_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.domein.code</code>.
     */
    public final TableField<DomeinRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.domein.naam</code>.
     */
    public final TableField<DomeinRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private Domein(Name alias, Table<DomeinRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Domein(Name alias, Table<DomeinRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.domein</code> table reference
     */
    public Domein(String alias) {
        this(DSL.name(alias), DOMEIN);
    }

    /**
     * Create an aliased <code>lcms.domein</code> table reference
     */
    public Domein(Name alias) {
        this(alias, DOMEIN);
    }

    /**
     * Create a <code>lcms.domein</code> table reference
     */
    public Domein() {
        this(DSL.name("domein"), null);
    }

    public <O extends Record> Domein(Table<O> path, ForeignKey<O, DomeinRecord> childPath, InverseForeignKey<O, DomeinRecord> parentPath) {
        super(path, childPath, parentPath, DOMEIN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DomeinPath extends Domein implements Path<DomeinRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DomeinPath(Table<O> path, ForeignKey<O, DomeinRecord> childPath, InverseForeignKey<O, DomeinRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DomeinPath(Name alias, Table<DomeinRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DomeinPath as(String alias) {
            return new DomeinPath(DSL.name(alias), this);
        }

        @Override
        public DomeinPath as(Name alias) {
            return new DomeinPath(alias, this);
        }

        @Override
        public DomeinPath as(Table<?> alias) {
            return new DomeinPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOMEIN_FK_DOMEIN_SCENARIO_SESSIE1_IDX);
    }

    @Override
    public Identity<DomeinRecord, Integer> getIdentity() {
        return (Identity<DomeinRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DomeinRecord> getPrimaryKey() {
        return Keys.KEY_DOMEIN_PRIMARY;
    }

    @Override
    public List<UniqueKey<DomeinRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DOMEIN_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<DomeinRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DOMEIN_SCENARIO_SESSIE1);
    }

    private transient ScenarioSessiePath _scenarioSessie;

    /**
     * Get the implicit join path to the <code>lcms.scenario_sessie</code>
     * table.
     */
    public ScenarioSessiePath scenarioSessie() {
        if (_scenarioSessie == null)
            _scenarioSessie = new ScenarioSessiePath(this, Keys.FK_DOMEIN_SCENARIO_SESSIE1, null);

        return _scenarioSessie;
    }

    private transient OrganisatiePath _organisatie;

    /**
     * Get the implicit to-many join path to the <code>lcms.organisatie</code>
     * table
     */
    public OrganisatiePath organisatie() {
        if (_organisatie == null)
            _organisatie = new OrganisatiePath(this, null, Keys.FK_ORGANISATIE_DOMEIN1.getInverseKey());

        return _organisatie;
    }

    @Override
    public Domein as(String alias) {
        return new Domein(DSL.name(alias), this);
    }

    @Override
    public Domein as(Name alias) {
        return new Domein(alias, this);
    }

    @Override
    public Domein as(Table<?> alias) {
        return new Domein(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Domein rename(String name) {
        return new Domein(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Domein rename(Name name) {
        return new Domein(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Domein rename(Table<?> name) {
        return new Domein(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein where(Condition condition) {
        return new Domein(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domein where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domein where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domein where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Domein where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Domein whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
