/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.Theme.ThemePath;
import nl.tudelft.simulation.lcms.data.tables.records.FieldRecord;

import org.jooq.Condition;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Field extends TableImpl<FieldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.field</code>
     */
    public static final Field FIELD = new Field();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FieldRecord> getRecordType() {
        return FieldRecord.class;
    }

    /**
     * The column <code>lcms.field.id</code>.
     */
    public final TableField<FieldRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.field.name</code>.
     */
    public final TableField<FieldRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>lcms.field.activity_id</code>.
     */
    public final TableField<FieldRecord, Integer> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Field(Name alias, Table<FieldRecord> aliased) {
        this(alias, aliased, (org.jooq.Field<?>[]) null, null);
    }

    private Field(Name alias, Table<FieldRecord> aliased, org.jooq.Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.field</code> table reference
     */
    public Field(String alias) {
        this(DSL.name(alias), FIELD);
    }

    /**
     * Create an aliased <code>lcms.field</code> table reference
     */
    public Field(Name alias) {
        this(alias, FIELD);
    }

    /**
     * Create a <code>lcms.field</code> table reference
     */
    public Field() {
        this(DSL.name("field"), null);
    }

    public <O extends Record> Field(Table<O> path, ForeignKey<O, FieldRecord> childPath, InverseForeignKey<O, FieldRecord> parentPath) {
        super(path, childPath, parentPath, FIELD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FieldPath extends Field implements Path<FieldRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FieldPath(Table<O> path, ForeignKey<O, FieldRecord> childPath, InverseForeignKey<O, FieldRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FieldPath(Name alias, Table<FieldRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FieldPath as(String alias) {
            return new FieldPath(DSL.name(alias), this);
        }

        @Override
        public FieldPath as(Name alias) {
            return new FieldPath(alias, this);
        }

        @Override
        public FieldPath as(Table<?> alias) {
            return new FieldPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FIELD_FK_FIELD_ACTIVITY1_IDX);
    }

    @Override
    public Identity<FieldRecord, Integer> getIdentity() {
        return (Identity<FieldRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FieldRecord> getPrimaryKey() {
        return Keys.KEY_FIELD_PRIMARY;
    }

    @Override
    public List<UniqueKey<FieldRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_FIELD_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<FieldRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_FIELD_ACTIVITY1);
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit join path to the <code>lcms.activity</code> table.
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, Keys.FK_FIELD_ACTIVITY1, null);

        return _activity;
    }

    private transient ThemePath _theme;

    /**
     * Get the implicit to-many join path to the <code>lcms.theme</code> table
     */
    public ThemePath theme() {
        if (_theme == null)
            _theme = new ThemePath(this, null, Keys.FK_THEME_FIELD1.getInverseKey());

        return _theme;
    }

    @Override
    public Field as(String alias) {
        return new Field(DSL.name(alias), this);
    }

    @Override
    public Field as(Name alias) {
        return new Field(alias, this);
    }

    @Override
    public Field as(Table<?> alias) {
        return new Field(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Field rename(String name) {
        return new Field(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Field rename(Name name) {
        return new Field(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Field rename(Table<?> name) {
        return new Field(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field where(Condition condition) {
        return new Field(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field where(org.jooq.Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Field where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Field where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Field where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Field where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Field whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
