/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activiteit.ActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.Gebruiker.GebruikerPath;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerActiviteitRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GebruikerActiviteit extends TableImpl<GebruikerActiviteitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.gebruiker_activiteit</code>
     */
    public static final GebruikerActiviteit GEBRUIKER_ACTIVITEIT = new GebruikerActiviteit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GebruikerActiviteitRecord> getRecordType() {
        return GebruikerActiviteitRecord.class;
    }

    /**
     * The column <code>lcms.gebruiker_activiteit.id</code>.
     */
    public final TableField<GebruikerActiviteitRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.gebruiker_activiteit.activiteit_id</code>.
     */
    public final TableField<GebruikerActiviteitRecord, Integer> ACTIVITEIT_ID = createField(DSL.name("activiteit_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.gebruiker_activiteit.gebruiker_id</code>.
     */
    public final TableField<GebruikerActiviteitRecord, Integer> GEBRUIKER_ID = createField(DSL.name("gebruiker_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.gebruiker_activiteit.gelezen</code>.
     */
    public final TableField<GebruikerActiviteitRecord, Byte> GELEZEN = createField(DSL.name("gelezen"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    private GebruikerActiviteit(Name alias, Table<GebruikerActiviteitRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GebruikerActiviteit(Name alias, Table<GebruikerActiviteitRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.gebruiker_activiteit</code> table reference
     */
    public GebruikerActiviteit(String alias) {
        this(DSL.name(alias), GEBRUIKER_ACTIVITEIT);
    }

    /**
     * Create an aliased <code>lcms.gebruiker_activiteit</code> table reference
     */
    public GebruikerActiviteit(Name alias) {
        this(alias, GEBRUIKER_ACTIVITEIT);
    }

    /**
     * Create a <code>lcms.gebruiker_activiteit</code> table reference
     */
    public GebruikerActiviteit() {
        this(DSL.name("gebruiker_activiteit"), null);
    }

    public <O extends Record> GebruikerActiviteit(Table<O> path, ForeignKey<O, GebruikerActiviteitRecord> childPath, InverseForeignKey<O, GebruikerActiviteitRecord> parentPath) {
        super(path, childPath, parentPath, GEBRUIKER_ACTIVITEIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GebruikerActiviteitPath extends GebruikerActiviteit implements Path<GebruikerActiviteitRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GebruikerActiviteitPath(Table<O> path, ForeignKey<O, GebruikerActiviteitRecord> childPath, InverseForeignKey<O, GebruikerActiviteitRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GebruikerActiviteitPath(Name alias, Table<GebruikerActiviteitRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GebruikerActiviteitPath as(String alias) {
            return new GebruikerActiviteitPath(DSL.name(alias), this);
        }

        @Override
        public GebruikerActiviteitPath as(Name alias) {
            return new GebruikerActiviteitPath(alias, this);
        }

        @Override
        public GebruikerActiviteitPath as(Table<?> alias) {
            return new GebruikerActiviteitPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GEBRUIKER_ACTIVITEIT_FK_GEBRUIKER_ACTIVITEIT_ACTIVITEIT1_IDX, Indexes.GEBRUIKER_ACTIVITEIT_FK_GEBRUIKER_ACTIVITEIT_GEBRUIKER1_IDX);
    }

    @Override
    public Identity<GebruikerActiviteitRecord, Integer> getIdentity() {
        return (Identity<GebruikerActiviteitRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GebruikerActiviteitRecord> getPrimaryKey() {
        return Keys.KEY_GEBRUIKER_ACTIVITEIT_PRIMARY;
    }

    @Override
    public List<UniqueKey<GebruikerActiviteitRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GEBRUIKER_ACTIVITEIT_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<GebruikerActiviteitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GEBRUIKER_ACTIVITEIT_ACTIVITEIT1, Keys.FK_GEBRUIKER_ACTIVITEIT_GEBRUIKER1);
    }

    private transient ActiviteitPath _activiteit;

    /**
     * Get the implicit join path to the <code>lcms.activiteit</code> table.
     */
    public ActiviteitPath activiteit() {
        if (_activiteit == null)
            _activiteit = new ActiviteitPath(this, Keys.FK_GEBRUIKER_ACTIVITEIT_ACTIVITEIT1, null);

        return _activiteit;
    }

    private transient GebruikerPath _gebruiker;

    /**
     * Get the implicit join path to the <code>lcms.gebruiker</code> table.
     */
    public GebruikerPath gebruiker() {
        if (_gebruiker == null)
            _gebruiker = new GebruikerPath(this, Keys.FK_GEBRUIKER_ACTIVITEIT_GEBRUIKER1, null);

        return _gebruiker;
    }

    @Override
    public GebruikerActiviteit as(String alias) {
        return new GebruikerActiviteit(DSL.name(alias), this);
    }

    @Override
    public GebruikerActiviteit as(Name alias) {
        return new GebruikerActiviteit(alias, this);
    }

    @Override
    public GebruikerActiviteit as(Table<?> alias) {
        return new GebruikerActiviteit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerActiviteit rename(String name) {
        return new GebruikerActiviteit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerActiviteit rename(Name name) {
        return new GebruikerActiviteit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerActiviteit rename(Table<?> name) {
        return new GebruikerActiviteit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit where(Condition condition) {
        return new GebruikerActiviteit(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerActiviteit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerActiviteit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerActiviteit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerActiviteit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerActiviteit whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
