/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Gebruiker.GebruikerPath;
import nl.tudelft.simulation.lcms.data.tables.Profiel.ProfielPath;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerProfielRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GebruikerProfiel extends TableImpl<GebruikerProfielRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.gebruiker_profiel</code>
     */
    public static final GebruikerProfiel GEBRUIKER_PROFIEL = new GebruikerProfiel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GebruikerProfielRecord> getRecordType() {
        return GebruikerProfielRecord.class;
    }

    /**
     * The column <code>lcms.gebruiker_profiel.id</code>.
     */
    public final TableField<GebruikerProfielRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.gebruiker_profiel.profiel_id</code>.
     */
    public final TableField<GebruikerProfielRecord, Integer> PROFIEL_ID = createField(DSL.name("profiel_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.gebruiker_profiel.gebruiker_id</code>.
     */
    public final TableField<GebruikerProfielRecord, Integer> GEBRUIKER_ID = createField(DSL.name("gebruiker_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private GebruikerProfiel(Name alias, Table<GebruikerProfielRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GebruikerProfiel(Name alias, Table<GebruikerProfielRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.gebruiker_profiel</code> table reference
     */
    public GebruikerProfiel(String alias) {
        this(DSL.name(alias), GEBRUIKER_PROFIEL);
    }

    /**
     * Create an aliased <code>lcms.gebruiker_profiel</code> table reference
     */
    public GebruikerProfiel(Name alias) {
        this(alias, GEBRUIKER_PROFIEL);
    }

    /**
     * Create a <code>lcms.gebruiker_profiel</code> table reference
     */
    public GebruikerProfiel() {
        this(DSL.name("gebruiker_profiel"), null);
    }

    public <O extends Record> GebruikerProfiel(Table<O> path, ForeignKey<O, GebruikerProfielRecord> childPath, InverseForeignKey<O, GebruikerProfielRecord> parentPath) {
        super(path, childPath, parentPath, GEBRUIKER_PROFIEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GebruikerProfielPath extends GebruikerProfiel implements Path<GebruikerProfielRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GebruikerProfielPath(Table<O> path, ForeignKey<O, GebruikerProfielRecord> childPath, InverseForeignKey<O, GebruikerProfielRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GebruikerProfielPath(Name alias, Table<GebruikerProfielRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GebruikerProfielPath as(String alias) {
            return new GebruikerProfielPath(DSL.name(alias), this);
        }

        @Override
        public GebruikerProfielPath as(Name alias) {
            return new GebruikerProfielPath(alias, this);
        }

        @Override
        public GebruikerProfielPath as(Table<?> alias) {
            return new GebruikerProfielPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GEBRUIKER_PROFIEL_FK_GEBRUIKER_PROFIEL_GEBRUIKER1_IDX, Indexes.GEBRUIKER_PROFIEL_FK_GEBRUIKER_PROFIEL_PROFIEL1_IDX);
    }

    @Override
    public Identity<GebruikerProfielRecord, Integer> getIdentity() {
        return (Identity<GebruikerProfielRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GebruikerProfielRecord> getPrimaryKey() {
        return Keys.KEY_GEBRUIKER_PROFIEL_PRIMARY;
    }

    @Override
    public List<UniqueKey<GebruikerProfielRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GEBRUIKER_PROFIEL_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<GebruikerProfielRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GEBRUIKER_PROFIEL_GEBRUIKER1, Keys.FK_GEBRUIKER_PROFIEL_PROFIEL1);
    }

    private transient GebruikerPath _gebruiker;

    /**
     * Get the implicit join path to the <code>lcms.gebruiker</code> table.
     */
    public GebruikerPath gebruiker() {
        if (_gebruiker == null)
            _gebruiker = new GebruikerPath(this, Keys.FK_GEBRUIKER_PROFIEL_GEBRUIKER1, null);

        return _gebruiker;
    }

    private transient ProfielPath _profiel;

    /**
     * Get the implicit join path to the <code>lcms.profiel</code> table.
     */
    public ProfielPath profiel() {
        if (_profiel == null)
            _profiel = new ProfielPath(this, Keys.FK_GEBRUIKER_PROFIEL_PROFIEL1, null);

        return _profiel;
    }

    @Override
    public GebruikerProfiel as(String alias) {
        return new GebruikerProfiel(DSL.name(alias), this);
    }

    @Override
    public GebruikerProfiel as(Name alias) {
        return new GebruikerProfiel(alias, this);
    }

    @Override
    public GebruikerProfiel as(Table<?> alias) {
        return new GebruikerProfiel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerProfiel rename(String name) {
        return new GebruikerProfiel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerProfiel rename(Name name) {
        return new GebruikerProfiel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GebruikerProfiel rename(Table<?> name) {
        return new GebruikerProfiel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel where(Condition condition) {
        return new GebruikerProfiel(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerProfiel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerProfiel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerProfiel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GebruikerProfiel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GebruikerProfiel whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
