/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.GebruikerActiviteit.GebruikerActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.GebruikerProfiel.GebruikerProfielPath;
import nl.tudelft.simulation.lcms.data.tables.Log.LogPath;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Gebruiker extends TableImpl<GebruikerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.gebruiker</code>
     */
    public static final Gebruiker GEBRUIKER = new Gebruiker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GebruikerRecord> getRecordType() {
        return GebruikerRecord.class;
    }

    /**
     * The column <code>lcms.gebruiker.id</code>.
     */
    public final TableField<GebruikerRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.gebruiker.inlog_naam</code>.
     */
    public final TableField<GebruikerRecord, String> INLOG_NAAM = createField(DSL.name("inlog_naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.gebruiker.naam</code>.
     */
    public final TableField<GebruikerRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.gebruiker.password_hash</code>.
     */
    public final TableField<GebruikerRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Gebruiker(Name alias, Table<GebruikerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Gebruiker(Name alias, Table<GebruikerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.gebruiker</code> table reference
     */
    public Gebruiker(String alias) {
        this(DSL.name(alias), GEBRUIKER);
    }

    /**
     * Create an aliased <code>lcms.gebruiker</code> table reference
     */
    public Gebruiker(Name alias) {
        this(alias, GEBRUIKER);
    }

    /**
     * Create a <code>lcms.gebruiker</code> table reference
     */
    public Gebruiker() {
        this(DSL.name("gebruiker"), null);
    }

    public <O extends Record> Gebruiker(Table<O> path, ForeignKey<O, GebruikerRecord> childPath, InverseForeignKey<O, GebruikerRecord> parentPath) {
        super(path, childPath, parentPath, GEBRUIKER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GebruikerPath extends Gebruiker implements Path<GebruikerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GebruikerPath(Table<O> path, ForeignKey<O, GebruikerRecord> childPath, InverseForeignKey<O, GebruikerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GebruikerPath(Name alias, Table<GebruikerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GebruikerPath as(String alias) {
            return new GebruikerPath(DSL.name(alias), this);
        }

        @Override
        public GebruikerPath as(Name alias) {
            return new GebruikerPath(alias, this);
        }

        @Override
        public GebruikerPath as(Table<?> alias) {
            return new GebruikerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public Identity<GebruikerRecord, Integer> getIdentity() {
        return (Identity<GebruikerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GebruikerRecord> getPrimaryKey() {
        return Keys.KEY_GEBRUIKER_PRIMARY;
    }

    @Override
    public List<UniqueKey<GebruikerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GEBRUIKER_ID_UNIQUE);
    }

    private transient GebruikerActiviteitPath _gebruikerActiviteit;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.gebruiker_activiteit</code> table
     */
    public GebruikerActiviteitPath gebruikerActiviteit() {
        if (_gebruikerActiviteit == null)
            _gebruikerActiviteit = new GebruikerActiviteitPath(this, null, Keys.FK_GEBRUIKER_ACTIVITEIT_GEBRUIKER1.getInverseKey());

        return _gebruikerActiviteit;
    }

    private transient GebruikerProfielPath _gebruikerProfiel;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.gebruiker_profiel</code> table
     */
    public GebruikerProfielPath gebruikerProfiel() {
        if (_gebruikerProfiel == null)
            _gebruikerProfiel = new GebruikerProfielPath(this, null, Keys.FK_GEBRUIKER_PROFIEL_GEBRUIKER1.getInverseKey());

        return _gebruikerProfiel;
    }

    private transient LogPath _log;

    /**
     * Get the implicit to-many join path to the <code>lcms.log</code> table
     */
    public LogPath log() {
        if (_log == null)
            _log = new LogPath(this, null, Keys.FK_LOG_GEBRUIKER1.getInverseKey());

        return _log;
    }

    @Override
    public Gebruiker as(String alias) {
        return new Gebruiker(DSL.name(alias), this);
    }

    @Override
    public Gebruiker as(Name alias) {
        return new Gebruiker(alias, this);
    }

    @Override
    public Gebruiker as(Table<?> alias) {
        return new Gebruiker(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gebruiker rename(String name) {
        return new Gebruiker(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gebruiker rename(Name name) {
        return new Gebruiker(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gebruiker rename(Table<?> name) {
        return new Gebruiker(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker where(Condition condition) {
        return new Gebruiker(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gebruiker where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gebruiker where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gebruiker where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gebruiker where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gebruiker whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
