/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.Organisation.OrganisationPath;
import nl.tudelft.simulation.lcms.data.tables.records.InvolvedOrganisationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvolvedOrganisation extends TableImpl<InvolvedOrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.involved_organisation</code>
     */
    public static final InvolvedOrganisation INVOLVED_ORGANISATION = new InvolvedOrganisation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvolvedOrganisationRecord> getRecordType() {
        return InvolvedOrganisationRecord.class;
    }

    /**
     * The column <code>lcms.involved_organisation.id</code>.
     */
    public final TableField<InvolvedOrganisationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.involved_organisation.activity_id</code>.
     */
    public final TableField<InvolvedOrganisationRecord, Integer> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.involved_organisation.organisation_id</code>.
     */
    public final TableField<InvolvedOrganisationRecord, Integer> ORGANISATION_ID = createField(DSL.name("organisation_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private InvolvedOrganisation(Name alias, Table<InvolvedOrganisationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InvolvedOrganisation(Name alias, Table<InvolvedOrganisationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.involved_organisation</code> table reference
     */
    public InvolvedOrganisation(String alias) {
        this(DSL.name(alias), INVOLVED_ORGANISATION);
    }

    /**
     * Create an aliased <code>lcms.involved_organisation</code> table reference
     */
    public InvolvedOrganisation(Name alias) {
        this(alias, INVOLVED_ORGANISATION);
    }

    /**
     * Create a <code>lcms.involved_organisation</code> table reference
     */
    public InvolvedOrganisation() {
        this(DSL.name("involved_organisation"), null);
    }

    public <O extends Record> InvolvedOrganisation(Table<O> path, ForeignKey<O, InvolvedOrganisationRecord> childPath, InverseForeignKey<O, InvolvedOrganisationRecord> parentPath) {
        super(path, childPath, parentPath, INVOLVED_ORGANISATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InvolvedOrganisationPath extends InvolvedOrganisation implements Path<InvolvedOrganisationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InvolvedOrganisationPath(Table<O> path, ForeignKey<O, InvolvedOrganisationRecord> childPath, InverseForeignKey<O, InvolvedOrganisationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InvolvedOrganisationPath(Name alias, Table<InvolvedOrganisationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InvolvedOrganisationPath as(String alias) {
            return new InvolvedOrganisationPath(DSL.name(alias), this);
        }

        @Override
        public InvolvedOrganisationPath as(Name alias) {
            return new InvolvedOrganisationPath(alias, this);
        }

        @Override
        public InvolvedOrganisationPath as(Table<?> alias) {
            return new InvolvedOrganisationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INVOLVED_ORGANISATION_FK_INVOLVED_ORGANIZATION_ACTIVITY1_IDX, Indexes.INVOLVED_ORGANISATION_FK_INVOLVED_ORGANIZATION_ORGANISATION1_IDX);
    }

    @Override
    public Identity<InvolvedOrganisationRecord, Integer> getIdentity() {
        return (Identity<InvolvedOrganisationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InvolvedOrganisationRecord> getPrimaryKey() {
        return Keys.KEY_INVOLVED_ORGANISATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<InvolvedOrganisationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INVOLVED_ORGANISATION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<InvolvedOrganisationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_INVOLVED_ORGANIZATION_ACTIVITY1, Keys.FK_INVOLVED_ORGANIZATION_ORGANISATION1);
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit join path to the <code>lcms.activity</code> table.
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, Keys.FK_INVOLVED_ORGANIZATION_ACTIVITY1, null);

        return _activity;
    }

    private transient OrganisationPath _organisation;

    /**
     * Get the implicit join path to the <code>lcms.organisation</code> table.
     */
    public OrganisationPath organisation() {
        if (_organisation == null)
            _organisation = new OrganisationPath(this, Keys.FK_INVOLVED_ORGANIZATION_ORGANISATION1, null);

        return _organisation;
    }

    @Override
    public InvolvedOrganisation as(String alias) {
        return new InvolvedOrganisation(DSL.name(alias), this);
    }

    @Override
    public InvolvedOrganisation as(Name alias) {
        return new InvolvedOrganisation(alias, this);
    }

    @Override
    public InvolvedOrganisation as(Table<?> alias) {
        return new InvolvedOrganisation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InvolvedOrganisation rename(String name) {
        return new InvolvedOrganisation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvolvedOrganisation rename(Name name) {
        return new InvolvedOrganisation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvolvedOrganisation rename(Table<?> name) {
        return new InvolvedOrganisation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation where(Condition condition) {
        return new InvolvedOrganisation(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvolvedOrganisation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvolvedOrganisation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvolvedOrganisation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvolvedOrganisation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvolvedOrganisation whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
