/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.Domain.DomainPath;
import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation.InvolvedOrganisationPath;
import nl.tudelft.simulation.lcms.data.tables.Team.TeamPath;
import nl.tudelft.simulation.lcms.data.tables.records.OrganisationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Organisation extends TableImpl<OrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.organisation</code>
     */
    public static final Organisation ORGANISATION = new Organisation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisationRecord> getRecordType() {
        return OrganisationRecord.class;
    }

    /**
     * The column <code>lcms.organisation.id</code>.
     */
    public final TableField<OrganisationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.organisation.code</code>.
     */
    public final TableField<OrganisationRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.organisation.naam</code>.
     */
    public final TableField<OrganisationRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.organisation.domain_id</code>.
     */
    public final TableField<OrganisationRecord, Integer> DOMAIN_ID = createField(DSL.name("domain_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Organisation(Name alias, Table<OrganisationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Organisation(Name alias, Table<OrganisationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.organisation</code> table reference
     */
    public Organisation(String alias) {
        this(DSL.name(alias), ORGANISATION);
    }

    /**
     * Create an aliased <code>lcms.organisation</code> table reference
     */
    public Organisation(Name alias) {
        this(alias, ORGANISATION);
    }

    /**
     * Create a <code>lcms.organisation</code> table reference
     */
    public Organisation() {
        this(DSL.name("organisation"), null);
    }

    public <O extends Record> Organisation(Table<O> path, ForeignKey<O, OrganisationRecord> childPath, InverseForeignKey<O, OrganisationRecord> parentPath) {
        super(path, childPath, parentPath, ORGANISATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganisationPath extends Organisation implements Path<OrganisationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrganisationPath(Table<O> path, ForeignKey<O, OrganisationRecord> childPath, InverseForeignKey<O, OrganisationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganisationPath(Name alias, Table<OrganisationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganisationPath as(String alias) {
            return new OrganisationPath(DSL.name(alias), this);
        }

        @Override
        public OrganisationPath as(Name alias) {
            return new OrganisationPath(alias, this);
        }

        @Override
        public OrganisationPath as(Table<?> alias) {
            return new OrganisationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORGANISATION_FK_ORGANISATIE_DOMAIN1_IDX);
    }

    @Override
    public Identity<OrganisationRecord, Integer> getIdentity() {
        return (Identity<OrganisationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganisationRecord> getPrimaryKey() {
        return Keys.KEY_ORGANISATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrganisationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ORGANISATION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<OrganisationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORGANISATIE_DOMAIN1);
    }

    private transient DomainPath _domain;

    /**
     * Get the implicit join path to the <code>lcms.domain</code> table.
     */
    public DomainPath domain() {
        if (_domain == null)
            _domain = new DomainPath(this, Keys.FK_ORGANISATIE_DOMAIN1, null);

        return _domain;
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit to-many join path to the <code>lcms.activity</code>
     * table
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, null, Keys.FK_ACTIVITY_ORGANISATION1.getInverseKey());

        return _activity;
    }

    private transient InvolvedOrganisationPath _involvedOrganisation;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.involved_organisation</code> table
     */
    public InvolvedOrganisationPath involvedOrganisation() {
        if (_involvedOrganisation == null)
            _involvedOrganisation = new InvolvedOrganisationPath(this, null, Keys.FK_INVOLVED_ORGANIZATION_ORGANISATION1.getInverseKey());

        return _involvedOrganisation;
    }

    private transient TeamPath _team;

    /**
     * Get the implicit to-many join path to the <code>lcms.team</code> table
     */
    public TeamPath team() {
        if (_team == null)
            _team = new TeamPath(this, null, Keys.FK_TEAM_ORGANISATION1.getInverseKey());

        return _team;
    }

    @Override
    public Organisation as(String alias) {
        return new Organisation(DSL.name(alias), this);
    }

    @Override
    public Organisation as(Name alias) {
        return new Organisation(alias, this);
    }

    @Override
    public Organisation as(Table<?> alias) {
        return new Organisation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisation rename(String name) {
        return new Organisation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisation rename(Name name) {
        return new Organisation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisation rename(Table<?> name) {
        return new Organisation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation where(Condition condition) {
        return new Organisation(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisation whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
