/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activiteit.ActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.BetrokkenOrganisatie.BetrokkenOrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.Domein.DomeinPath;
import nl.tudelft.simulation.lcms.data.tables.Team.TeamPath;
import nl.tudelft.simulation.lcms.data.tables.records.OrganisatieRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Organisatie extends TableImpl<OrganisatieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.organisatie</code>
     */
    public static final Organisatie ORGANISATIE = new Organisatie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisatieRecord> getRecordType() {
        return OrganisatieRecord.class;
    }

    /**
     * The column <code>lcms.organisatie.id</code>.
     */
    public final TableField<OrganisatieRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.organisatie.domein_id</code>.
     */
    public final TableField<OrganisatieRecord, Integer> DOMEIN_ID = createField(DSL.name("domein_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.organisatie.code</code>.
     */
    public final TableField<OrganisatieRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.organisatie.naam</code>.
     */
    public final TableField<OrganisatieRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private Organisatie(Name alias, Table<OrganisatieRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Organisatie(Name alias, Table<OrganisatieRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.organisatie</code> table reference
     */
    public Organisatie(String alias) {
        this(DSL.name(alias), ORGANISATIE);
    }

    /**
     * Create an aliased <code>lcms.organisatie</code> table reference
     */
    public Organisatie(Name alias) {
        this(alias, ORGANISATIE);
    }

    /**
     * Create a <code>lcms.organisatie</code> table reference
     */
    public Organisatie() {
        this(DSL.name("organisatie"), null);
    }

    public <O extends Record> Organisatie(Table<O> path, ForeignKey<O, OrganisatieRecord> childPath, InverseForeignKey<O, OrganisatieRecord> parentPath) {
        super(path, childPath, parentPath, ORGANISATIE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganisatiePath extends Organisatie implements Path<OrganisatieRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrganisatiePath(Table<O> path, ForeignKey<O, OrganisatieRecord> childPath, InverseForeignKey<O, OrganisatieRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganisatiePath(Name alias, Table<OrganisatieRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganisatiePath as(String alias) {
            return new OrganisatiePath(DSL.name(alias), this);
        }

        @Override
        public OrganisatiePath as(Name alias) {
            return new OrganisatiePath(alias, this);
        }

        @Override
        public OrganisatiePath as(Table<?> alias) {
            return new OrganisatiePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORGANISATIE_FK_ORGANISATIE_DOMEIN1_IDX);
    }

    @Override
    public Identity<OrganisatieRecord, Integer> getIdentity() {
        return (Identity<OrganisatieRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganisatieRecord> getPrimaryKey() {
        return Keys.KEY_ORGANISATIE_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrganisatieRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ORGANISATIE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<OrganisatieRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORGANISATIE_DOMEIN1);
    }

    private transient DomeinPath _domein;

    /**
     * Get the implicit join path to the <code>lcms.domein</code> table.
     */
    public DomeinPath domein() {
        if (_domein == null)
            _domein = new DomeinPath(this, Keys.FK_ORGANISATIE_DOMEIN1, null);

        return _domein;
    }

    private transient ActiviteitPath _activiteit;

    /**
     * Get the implicit to-many join path to the <code>lcms.activiteit</code>
     * table
     */
    public ActiviteitPath activiteit() {
        if (_activiteit == null)
            _activiteit = new ActiviteitPath(this, null, Keys.FK_ACTIVITEIT_ORGANISATIE1.getInverseKey());

        return _activiteit;
    }

    private transient BetrokkenOrganisatiePath _betrokkenOrganisatie;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.betrokken_organisatie</code> table
     */
    public BetrokkenOrganisatiePath betrokkenOrganisatie() {
        if (_betrokkenOrganisatie == null)
            _betrokkenOrganisatie = new BetrokkenOrganisatiePath(this, null, Keys.FK_BETROKKEN_ORGANISATIE_ORGANISATIE1.getInverseKey());

        return _betrokkenOrganisatie;
    }

    private transient TeamPath _team;

    /**
     * Get the implicit to-many join path to the <code>lcms.team</code> table
     */
    public TeamPath team() {
        if (_team == null)
            _team = new TeamPath(this, null, Keys.FK_TEAM_ORGANISATIE1.getInverseKey());

        return _team;
    }

    @Override
    public Organisatie as(String alias) {
        return new Organisatie(DSL.name(alias), this);
    }

    @Override
    public Organisatie as(Name alias) {
        return new Organisatie(alias, this);
    }

    @Override
    public Organisatie as(Table<?> alias) {
        return new Organisatie(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisatie rename(String name) {
        return new Organisatie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisatie rename(Name name) {
        return new Organisatie(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisatie rename(Table<?> name) {
        return new Organisatie(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie where(Condition condition) {
        return new Organisatie(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisatie where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisatie where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisatie where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisatie where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisatie whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
