/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Discipline.DisciplinePath;
import nl.tudelft.simulation.lcms.data.tables.GebruikerProfiel.GebruikerProfielPath;
import nl.tudelft.simulation.lcms.data.tables.Team.TeamPath;
import nl.tudelft.simulation.lcms.data.tables.records.ProfielRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Profiel extends TableImpl<ProfielRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.profiel</code>
     */
    public static final Profiel PROFIEL = new Profiel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfielRecord> getRecordType() {
        return ProfielRecord.class;
    }

    /**
     * The column <code>lcms.profiel.id</code>.
     */
    public final TableField<ProfielRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.profiel.discipline_id</code>.
     */
    public final TableField<ProfielRecord, Integer> DISCIPLINE_ID = createField(DSL.name("discipline_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.profiel.team_id</code>.
     */
    public final TableField<ProfielRecord, Integer> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.profiel.functie</code>.
     */
    public final TableField<ProfielRecord, String> FUNCTIE = createField(DSL.name("functie"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.profiel.niveau</code>.
     */
    public final TableField<ProfielRecord, String> NIVEAU = createField(DSL.name("niveau"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.profiel.schrijver</code>.
     */
    public final TableField<ProfielRecord, Byte> SCHRIJVER = createField(DSL.name("schrijver"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    private Profiel(Name alias, Table<ProfielRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Profiel(Name alias, Table<ProfielRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.profiel</code> table reference
     */
    public Profiel(String alias) {
        this(DSL.name(alias), PROFIEL);
    }

    /**
     * Create an aliased <code>lcms.profiel</code> table reference
     */
    public Profiel(Name alias) {
        this(alias, PROFIEL);
    }

    /**
     * Create a <code>lcms.profiel</code> table reference
     */
    public Profiel() {
        this(DSL.name("profiel"), null);
    }

    public <O extends Record> Profiel(Table<O> path, ForeignKey<O, ProfielRecord> childPath, InverseForeignKey<O, ProfielRecord> parentPath) {
        super(path, childPath, parentPath, PROFIEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProfielPath extends Profiel implements Path<ProfielRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProfielPath(Table<O> path, ForeignKey<O, ProfielRecord> childPath, InverseForeignKey<O, ProfielRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProfielPath(Name alias, Table<ProfielRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProfielPath as(String alias) {
            return new ProfielPath(DSL.name(alias), this);
        }

        @Override
        public ProfielPath as(Name alias) {
            return new ProfielPath(alias, this);
        }

        @Override
        public ProfielPath as(Table<?> alias) {
            return new ProfielPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROFIEL_FK_PROFIEL_DISCIPLINE1_IDX, Indexes.PROFIEL_FK_PROFIEL_TEAM1_IDX);
    }

    @Override
    public Identity<ProfielRecord, Integer> getIdentity() {
        return (Identity<ProfielRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProfielRecord> getPrimaryKey() {
        return Keys.KEY_PROFIEL_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProfielRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROFIEL_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ProfielRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROFIEL_DISCIPLINE1, Keys.FK_PROFIEL_TEAM1);
    }

    private transient DisciplinePath _discipline;

    /**
     * Get the implicit join path to the <code>lcms.discipline</code> table.
     */
    public DisciplinePath discipline() {
        if (_discipline == null)
            _discipline = new DisciplinePath(this, Keys.FK_PROFIEL_DISCIPLINE1, null);

        return _discipline;
    }

    private transient TeamPath _team;

    /**
     * Get the implicit join path to the <code>lcms.team</code> table.
     */
    public TeamPath team() {
        if (_team == null)
            _team = new TeamPath(this, Keys.FK_PROFIEL_TEAM1, null);

        return _team;
    }

    private transient GebruikerProfielPath _gebruikerProfiel;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.gebruiker_profiel</code> table
     */
    public GebruikerProfielPath gebruikerProfiel() {
        if (_gebruikerProfiel == null)
            _gebruikerProfiel = new GebruikerProfielPath(this, null, Keys.FK_GEBRUIKER_PROFIEL_PROFIEL1.getInverseKey());

        return _gebruikerProfiel;
    }

    @Override
    public Profiel as(String alias) {
        return new Profiel(DSL.name(alias), this);
    }

    @Override
    public Profiel as(Name alias) {
        return new Profiel(alias, this);
    }

    @Override
    public Profiel as(Table<?> alias) {
        return new Profiel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Profiel rename(String name) {
        return new Profiel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profiel rename(Name name) {
        return new Profiel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profiel rename(Table<?> name) {
        return new Profiel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel where(Condition condition) {
        return new Profiel(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profiel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profiel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profiel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profiel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profiel whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
