/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Discipline.DisciplinePath;
import nl.tudelft.simulation.lcms.data.tables.Team.TeamPath;
import nl.tudelft.simulation.lcms.data.tables.UserProfile.UserProfilePath;
import nl.tudelft.simulation.lcms.data.tables.records.ProfileRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Profile extends TableImpl<ProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.profile</code>
     */
    public static final Profile PROFILE = new Profile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfileRecord> getRecordType() {
        return ProfileRecord.class;
    }

    /**
     * The column <code>lcms.profile.id</code>.
     */
    public final TableField<ProfileRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.profile.function</code>.
     */
    public final TableField<ProfileRecord, String> FUNCTION = createField(DSL.name("function"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.profile.level</code>.
     */
    public final TableField<ProfileRecord, String> LEVEL = createField(DSL.name("level"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.profile.writer</code>.
     */
    public final TableField<ProfileRecord, Byte> WRITER = createField(DSL.name("writer"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>lcms.profile.discipline_id</code>.
     */
    public final TableField<ProfileRecord, Integer> DISCIPLINE_ID = createField(DSL.name("discipline_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.profile.team_id</code>.
     */
    public final TableField<ProfileRecord, Integer> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Profile(Name alias, Table<ProfileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Profile(Name alias, Table<ProfileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.profile</code> table reference
     */
    public Profile(String alias) {
        this(DSL.name(alias), PROFILE);
    }

    /**
     * Create an aliased <code>lcms.profile</code> table reference
     */
    public Profile(Name alias) {
        this(alias, PROFILE);
    }

    /**
     * Create a <code>lcms.profile</code> table reference
     */
    public Profile() {
        this(DSL.name("profile"), null);
    }

    public <O extends Record> Profile(Table<O> path, ForeignKey<O, ProfileRecord> childPath, InverseForeignKey<O, ProfileRecord> parentPath) {
        super(path, childPath, parentPath, PROFILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProfilePath extends Profile implements Path<ProfileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProfilePath(Table<O> path, ForeignKey<O, ProfileRecord> childPath, InverseForeignKey<O, ProfileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProfilePath(Name alias, Table<ProfileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProfilePath as(String alias) {
            return new ProfilePath(DSL.name(alias), this);
        }

        @Override
        public ProfilePath as(Name alias) {
            return new ProfilePath(alias, this);
        }

        @Override
        public ProfilePath as(Table<?> alias) {
            return new ProfilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROFILE_FK_PROFIEL_DISCIPLINE1_IDX, Indexes.PROFILE_FK_PROFIEL_TEAM1_IDX);
    }

    @Override
    public Identity<ProfileRecord, Integer> getIdentity() {
        return (Identity<ProfileRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProfileRecord> getPrimaryKey() {
        return Keys.KEY_PROFILE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProfileRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROFILE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ProfileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROFIEL_DISCIPLINE1, Keys.FK_PROFIEL_TEAM1);
    }

    private transient DisciplinePath _discipline;

    /**
     * Get the implicit join path to the <code>lcms.discipline</code> table.
     */
    public DisciplinePath discipline() {
        if (_discipline == null)
            _discipline = new DisciplinePath(this, Keys.FK_PROFIEL_DISCIPLINE1, null);

        return _discipline;
    }

    private transient TeamPath _team;

    /**
     * Get the implicit join path to the <code>lcms.team</code> table.
     */
    public TeamPath team() {
        if (_team == null)
            _team = new TeamPath(this, Keys.FK_PROFIEL_TEAM1, null);

        return _team;
    }

    private transient UserProfilePath _userProfile;

    /**
     * Get the implicit to-many join path to the <code>lcms.user_profile</code>
     * table
     */
    public UserProfilePath userProfile() {
        if (_userProfile == null)
            _userProfile = new UserProfilePath(this, null, Keys.FK_USER_PROFILE_PROFILE1.getInverseKey());

        return _userProfile;
    }

    @Override
    public Profile as(String alias) {
        return new Profile(DSL.name(alias), this);
    }

    @Override
    public Profile as(Name alias) {
        return new Profile(alias, this);
    }

    @Override
    public Profile as(Table<?> alias) {
        return new Profile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Profile rename(String name) {
        return new Profile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profile rename(Name name) {
        return new Profile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profile rename(Table<?> name) {
        return new Profile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile where(Condition condition) {
        return new Profile(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profile whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
