/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Thema.ThemaPath;
import nl.tudelft.simulation.lcms.data.tables.records.PuntRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Punt extends TableImpl<PuntRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.punt</code>
     */
    public static final Punt PUNT = new Punt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PuntRecord> getRecordType() {
        return PuntRecord.class;
    }

    /**
     * The column <code>lcms.punt.id</code>.
     */
    public final TableField<PuntRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.punt.thema_id</code>.
     */
    public final TableField<PuntRecord, Integer> THEMA_ID = createField(DSL.name("thema_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.punt.inhoud</code>.
     */
    public final TableField<PuntRecord, String> INHOUD = createField(DSL.name("inhoud"), SQLDataType.CLOB(16777215).nullable(false), this, "");

    private Punt(Name alias, Table<PuntRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Punt(Name alias, Table<PuntRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.punt</code> table reference
     */
    public Punt(String alias) {
        this(DSL.name(alias), PUNT);
    }

    /**
     * Create an aliased <code>lcms.punt</code> table reference
     */
    public Punt(Name alias) {
        this(alias, PUNT);
    }

    /**
     * Create a <code>lcms.punt</code> table reference
     */
    public Punt() {
        this(DSL.name("punt"), null);
    }

    public <O extends Record> Punt(Table<O> path, ForeignKey<O, PuntRecord> childPath, InverseForeignKey<O, PuntRecord> parentPath) {
        super(path, childPath, parentPath, PUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PuntPath extends Punt implements Path<PuntRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PuntPath(Table<O> path, ForeignKey<O, PuntRecord> childPath, InverseForeignKey<O, PuntRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PuntPath(Name alias, Table<PuntRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PuntPath as(String alias) {
            return new PuntPath(DSL.name(alias), this);
        }

        @Override
        public PuntPath as(Name alias) {
            return new PuntPath(alias, this);
        }

        @Override
        public PuntPath as(Table<?> alias) {
            return new PuntPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PUNT_FK_PUNT_THEMA1_IDX);
    }

    @Override
    public Identity<PuntRecord, Integer> getIdentity() {
        return (Identity<PuntRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PuntRecord> getPrimaryKey() {
        return Keys.KEY_PUNT_PRIMARY;
    }

    @Override
    public List<UniqueKey<PuntRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PUNT_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<PuntRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PUNT_THEMA1);
    }

    private transient ThemaPath _thema;

    /**
     * Get the implicit join path to the <code>lcms.thema</code> table.
     */
    public ThemaPath thema() {
        if (_thema == null)
            _thema = new ThemaPath(this, Keys.FK_PUNT_THEMA1, null);

        return _thema;
    }

    @Override
    public Punt as(String alias) {
        return new Punt(DSL.name(alias), this);
    }

    @Override
    public Punt as(Name alias) {
        return new Punt(alias, this);
    }

    @Override
    public Punt as(Table<?> alias) {
        return new Punt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Punt rename(String name) {
        return new Punt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Punt rename(Name name) {
        return new Punt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Punt rename(Table<?> name) {
        return new Punt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt where(Condition condition) {
        return new Punt(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punt whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
