/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.ActivityType.ActivityTypePath;
import nl.tudelft.simulation.lcms.data.tables.Discipline.DisciplinePath;
import nl.tudelft.simulation.lcms.data.tables.Domain.DomainPath;
import nl.tudelft.simulation.lcms.data.tables.Scenario.ScenarioPath;
import nl.tudelft.simulation.lcms.data.tables.Session.SessionPath;
import nl.tudelft.simulation.lcms.data.tables.Severity.SeverityPath;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioSessionRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioSession extends TableImpl<ScenarioSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.scenario_session</code>
     */
    public static final ScenarioSession SCENARIO_SESSION = new ScenarioSession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScenarioSessionRecord> getRecordType() {
        return ScenarioSessionRecord.class;
    }

    /**
     * The column <code>lcms.scenario_session.id</code>.
     */
    public final TableField<ScenarioSessionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.scenario_session.scenario_id</code>.
     */
    public final TableField<ScenarioSessionRecord, Integer> SCENARIO_ID = createField(DSL.name("scenario_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.scenario_session.session_id</code>.
     */
    public final TableField<ScenarioSessionRecord, Integer> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private ScenarioSession(Name alias, Table<ScenarioSessionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScenarioSession(Name alias, Table<ScenarioSessionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.scenario_session</code> table reference
     */
    public ScenarioSession(String alias) {
        this(DSL.name(alias), SCENARIO_SESSION);
    }

    /**
     * Create an aliased <code>lcms.scenario_session</code> table reference
     */
    public ScenarioSession(Name alias) {
        this(alias, SCENARIO_SESSION);
    }

    /**
     * Create a <code>lcms.scenario_session</code> table reference
     */
    public ScenarioSession() {
        this(DSL.name("scenario_session"), null);
    }

    public <O extends Record> ScenarioSession(Table<O> path, ForeignKey<O, ScenarioSessionRecord> childPath, InverseForeignKey<O, ScenarioSessionRecord> parentPath) {
        super(path, childPath, parentPath, SCENARIO_SESSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ScenarioSessionPath extends ScenarioSession implements Path<ScenarioSessionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ScenarioSessionPath(Table<O> path, ForeignKey<O, ScenarioSessionRecord> childPath, InverseForeignKey<O, ScenarioSessionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ScenarioSessionPath(Name alias, Table<ScenarioSessionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ScenarioSessionPath as(String alias) {
            return new ScenarioSessionPath(DSL.name(alias), this);
        }

        @Override
        public ScenarioSessionPath as(Name alias) {
            return new ScenarioSessionPath(alias, this);
        }

        @Override
        public ScenarioSessionPath as(Table<?> alias) {
            return new ScenarioSessionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCENARIO_SESSION_FK_SCENARIO_SESSIE_SCENARIO1_IDX, Indexes.SCENARIO_SESSION_FK_SCENARIO_SESSION_SESSION1_IDX);
    }

    @Override
    public Identity<ScenarioSessionRecord, Integer> getIdentity() {
        return (Identity<ScenarioSessionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ScenarioSessionRecord> getPrimaryKey() {
        return Keys.KEY_SCENARIO_SESSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<ScenarioSessionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SCENARIO_SESSION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ScenarioSessionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SCENARIO_SESSIE_SCENARIO1, Keys.FK_SCENARIO_SESSION_SESSION1);
    }

    private transient ScenarioPath _scenario;

    /**
     * Get the implicit join path to the <code>lcms.scenario</code> table.
     */
    public ScenarioPath scenario() {
        if (_scenario == null)
            _scenario = new ScenarioPath(this, Keys.FK_SCENARIO_SESSIE_SCENARIO1, null);

        return _scenario;
    }

    private transient SessionPath _session;

    /**
     * Get the implicit join path to the <code>lcms.session</code> table.
     */
    public SessionPath session() {
        if (_session == null)
            _session = new SessionPath(this, Keys.FK_SCENARIO_SESSION_SESSION1, null);

        return _session;
    }

    private transient ActivityTypePath _activityType;

    /**
     * Get the implicit to-many join path to the <code>lcms.activity_type</code>
     * table
     */
    public ActivityTypePath activityType() {
        if (_activityType == null)
            _activityType = new ActivityTypePath(this, null, Keys.FK_ACTIVITY_TYPE_SCENARIO_SESSION1.getInverseKey());

        return _activityType;
    }

    private transient DisciplinePath _discipline;

    /**
     * Get the implicit to-many join path to the <code>lcms.discipline</code>
     * table
     */
    public DisciplinePath discipline() {
        if (_discipline == null)
            _discipline = new DisciplinePath(this, null, Keys.FK_DISCIPLINE_SCENARIO_SESSION1.getInverseKey());

        return _discipline;
    }

    private transient DomainPath _domain;

    /**
     * Get the implicit to-many join path to the <code>lcms.domain</code> table
     */
    public DomainPath domain() {
        if (_domain == null)
            _domain = new DomainPath(this, null, Keys.FK_DOMAIN_SCENARIO_SESSION1.getInverseKey());

        return _domain;
    }

    private transient SeverityPath _severity;

    /**
     * Get the implicit to-many join path to the <code>lcms.severity</code>
     * table
     */
    public SeverityPath severity() {
        if (_severity == null)
            _severity = new SeverityPath(this, null, Keys.FK_SEVERITY_SCENARIO_SESSION1.getInverseKey());

        return _severity;
    }

    @Override
    public ScenarioSession as(String alias) {
        return new ScenarioSession(DSL.name(alias), this);
    }

    @Override
    public ScenarioSession as(Name alias) {
        return new ScenarioSession(alias, this);
    }

    @Override
    public ScenarioSession as(Table<?> alias) {
        return new ScenarioSession(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSession rename(String name) {
        return new ScenarioSession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSession rename(Name name) {
        return new ScenarioSession(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSession rename(Table<?> name) {
        return new ScenarioSession(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession where(Condition condition) {
        return new ScenarioSession(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSession where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSession where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSession where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSession where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSession whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
