/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.ActiviteitType.ActiviteitTypePath;
import nl.tudelft.simulation.lcms.data.tables.Discipline.DisciplinePath;
import nl.tudelft.simulation.lcms.data.tables.Domein.DomeinPath;
import nl.tudelft.simulation.lcms.data.tables.Opschaling.OpschalingPath;
import nl.tudelft.simulation.lcms.data.tables.Scenario.ScenarioPath;
import nl.tudelft.simulation.lcms.data.tables.Sessie.SessiePath;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioSessieRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioSessie extends TableImpl<ScenarioSessieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.scenario_sessie</code>
     */
    public static final ScenarioSessie SCENARIO_SESSIE = new ScenarioSessie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScenarioSessieRecord> getRecordType() {
        return ScenarioSessieRecord.class;
    }

    /**
     * The column <code>lcms.scenario_sessie.id</code>.
     */
    public final TableField<ScenarioSessieRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.scenario_sessie.scenario_id</code>.
     */
    public final TableField<ScenarioSessieRecord, Integer> SCENARIO_ID = createField(DSL.name("scenario_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.scenario_sessie.sessie_id</code>.
     */
    public final TableField<ScenarioSessieRecord, Integer> SESSIE_ID = createField(DSL.name("sessie_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private ScenarioSessie(Name alias, Table<ScenarioSessieRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScenarioSessie(Name alias, Table<ScenarioSessieRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.scenario_sessie</code> table reference
     */
    public ScenarioSessie(String alias) {
        this(DSL.name(alias), SCENARIO_SESSIE);
    }

    /**
     * Create an aliased <code>lcms.scenario_sessie</code> table reference
     */
    public ScenarioSessie(Name alias) {
        this(alias, SCENARIO_SESSIE);
    }

    /**
     * Create a <code>lcms.scenario_sessie</code> table reference
     */
    public ScenarioSessie() {
        this(DSL.name("scenario_sessie"), null);
    }

    public <O extends Record> ScenarioSessie(Table<O> path, ForeignKey<O, ScenarioSessieRecord> childPath, InverseForeignKey<O, ScenarioSessieRecord> parentPath) {
        super(path, childPath, parentPath, SCENARIO_SESSIE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ScenarioSessiePath extends ScenarioSessie implements Path<ScenarioSessieRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ScenarioSessiePath(Table<O> path, ForeignKey<O, ScenarioSessieRecord> childPath, InverseForeignKey<O, ScenarioSessieRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ScenarioSessiePath(Name alias, Table<ScenarioSessieRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ScenarioSessiePath as(String alias) {
            return new ScenarioSessiePath(DSL.name(alias), this);
        }

        @Override
        public ScenarioSessiePath as(Name alias) {
            return new ScenarioSessiePath(alias, this);
        }

        @Override
        public ScenarioSessiePath as(Table<?> alias) {
            return new ScenarioSessiePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCENARIO_SESSIE_FK_SCENARIO_SESSIE_SCENARIO1_IDX, Indexes.SCENARIO_SESSIE_FK_SCENARIO_SESSIE_SESSIE1_IDX);
    }

    @Override
    public Identity<ScenarioSessieRecord, Integer> getIdentity() {
        return (Identity<ScenarioSessieRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ScenarioSessieRecord> getPrimaryKey() {
        return Keys.KEY_SCENARIO_SESSIE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ScenarioSessieRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SCENARIO_SESSIE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ScenarioSessieRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SCENARIO_SESSIE_SCENARIO1, Keys.FK_SCENARIO_SESSIE_SESSIE1);
    }

    private transient ScenarioPath _scenario;

    /**
     * Get the implicit join path to the <code>lcms.scenario</code> table.
     */
    public ScenarioPath scenario() {
        if (_scenario == null)
            _scenario = new ScenarioPath(this, Keys.FK_SCENARIO_SESSIE_SCENARIO1, null);

        return _scenario;
    }

    private transient SessiePath _sessie;

    /**
     * Get the implicit join path to the <code>lcms.sessie</code> table.
     */
    public SessiePath sessie() {
        if (_sessie == null)
            _sessie = new SessiePath(this, Keys.FK_SCENARIO_SESSIE_SESSIE1, null);

        return _sessie;
    }

    private transient ActiviteitTypePath _activiteitType;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.activiteit_type</code> table
     */
    public ActiviteitTypePath activiteitType() {
        if (_activiteitType == null)
            _activiteitType = new ActiviteitTypePath(this, null, Keys.FK_ACTIVITEIT_TYPE_SCENARIO_SESSIE1.getInverseKey());

        return _activiteitType;
    }

    private transient DisciplinePath _discipline;

    /**
     * Get the implicit to-many join path to the <code>lcms.discipline</code>
     * table
     */
    public DisciplinePath discipline() {
        if (_discipline == null)
            _discipline = new DisciplinePath(this, null, Keys.FK_DISCIPLINE_SCENARIO_SESSIE1.getInverseKey());

        return _discipline;
    }

    private transient DomeinPath _domein;

    /**
     * Get the implicit to-many join path to the <code>lcms.domein</code> table
     */
    public DomeinPath domein() {
        if (_domein == null)
            _domein = new DomeinPath(this, null, Keys.FK_DOMEIN_SCENARIO_SESSIE1.getInverseKey());

        return _domein;
    }

    private transient OpschalingPath _opschaling;

    /**
     * Get the implicit to-many join path to the <code>lcms.opschaling</code>
     * table
     */
    public OpschalingPath opschaling() {
        if (_opschaling == null)
            _opschaling = new OpschalingPath(this, null, Keys.FK_OPSCHALING_SCENARIO_SESSIE1.getInverseKey());

        return _opschaling;
    }

    @Override
    public ScenarioSessie as(String alias) {
        return new ScenarioSessie(DSL.name(alias), this);
    }

    @Override
    public ScenarioSessie as(Name alias) {
        return new ScenarioSessie(alias, this);
    }

    @Override
    public ScenarioSessie as(Table<?> alias) {
        return new ScenarioSessie(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSessie rename(String name) {
        return new ScenarioSessie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSessie rename(Name name) {
        return new ScenarioSessie(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioSessie rename(Table<?> name) {
        return new ScenarioSessie(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie where(Condition condition) {
        return new ScenarioSessie(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSessie where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSessie where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSessie where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScenarioSessie where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScenarioSessie whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
