/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Scenario.ScenarioPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession.ScenarioSessionPath;
import nl.tudelft.simulation.lcms.data.tables.records.SessionRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Session extends TableImpl<SessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.session</code>
     */
    public static final Session SESSION = new Session();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionRecord> getRecordType() {
        return SessionRecord.class;
    }

    /**
     * The column <code>lcms.session.id</code>.
     */
    public final TableField<SessionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.session.name</code>.
     */
    public final TableField<SessionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.session.location</code>.
     */
    public final TableField<SessionRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>lcms.session.date_start</code>.
     */
    public final TableField<SessionRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>lcms.session.date_end</code>.
     */
    public final TableField<SessionRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>lcms.session.scenario_id</code>.
     */
    public final TableField<SessionRecord, Integer> SCENARIO_ID = createField(DSL.name("scenario_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Session(Name alias, Table<SessionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Session(Name alias, Table<SessionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.session</code> table reference
     */
    public Session(String alias) {
        this(DSL.name(alias), SESSION);
    }

    /**
     * Create an aliased <code>lcms.session</code> table reference
     */
    public Session(Name alias) {
        this(alias, SESSION);
    }

    /**
     * Create a <code>lcms.session</code> table reference
     */
    public Session() {
        this(DSL.name("session"), null);
    }

    public <O extends Record> Session(Table<O> path, ForeignKey<O, SessionRecord> childPath, InverseForeignKey<O, SessionRecord> parentPath) {
        super(path, childPath, parentPath, SESSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SessionPath extends Session implements Path<SessionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SessionPath(Table<O> path, ForeignKey<O, SessionRecord> childPath, InverseForeignKey<O, SessionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SessionPath(Name alias, Table<SessionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SessionPath as(String alias) {
            return new SessionPath(DSL.name(alias), this);
        }

        @Override
        public SessionPath as(Name alias) {
            return new SessionPath(alias, this);
        }

        @Override
        public SessionPath as(Table<?> alias) {
            return new SessionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SESSION_FK_SESSION_SCENARIO1_IDX);
    }

    @Override
    public Identity<SessionRecord, Integer> getIdentity() {
        return (Identity<SessionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SessionRecord> getPrimaryKey() {
        return Keys.KEY_SESSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<SessionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SESSION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<SessionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SESSION_SCENARIO1);
    }

    private transient ScenarioPath _scenario;

    /**
     * Get the implicit join path to the <code>lcms.scenario</code> table.
     */
    public ScenarioPath scenario() {
        if (_scenario == null)
            _scenario = new ScenarioPath(this, Keys.FK_SESSION_SCENARIO1, null);

        return _scenario;
    }

    private transient ScenarioSessionPath _scenarioSession;

    /**
     * Get the implicit to-many join path to the
     * <code>lcms.scenario_session</code> table
     */
    public ScenarioSessionPath scenarioSession() {
        if (_scenarioSession == null)
            _scenarioSession = new ScenarioSessionPath(this, null, Keys.FK_SCENARIO_SESSION_SESSION1.getInverseKey());

        return _scenarioSession;
    }

    @Override
    public Session as(String alias) {
        return new Session(DSL.name(alias), this);
    }

    @Override
    public Session as(Name alias) {
        return new Session(alias, this);
    }

    @Override
    public Session as(Table<?> alias) {
        return new Session(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Session rename(String name) {
        return new Session(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Session rename(Name name) {
        return new Session(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Session rename(Table<?> name) {
        return new Session(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session where(Condition condition) {
        return new Session(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Session where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Session where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Session where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Session where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Session whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
