/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession.ScenarioSessionPath;
import nl.tudelft.simulation.lcms.data.tables.records.SeverityRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Nederlands: opschaling, GRIP1, GRIP2, etc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Severity extends TableImpl<SeverityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.severity</code>
     */
    public static final Severity SEVERITY = new Severity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeverityRecord> getRecordType() {
        return SeverityRecord.class;
    }

    /**
     * The column <code>lcms.severity.id</code>.
     */
    public final TableField<SeverityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.severity.code</code>.
     */
    public final TableField<SeverityRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.severity.name</code>.
     */
    public final TableField<SeverityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lcms.severity.scenario_session_id</code>.
     */
    public final TableField<SeverityRecord, Integer> SCENARIO_SESSION_ID = createField(DSL.name("scenario_session_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Severity(Name alias, Table<SeverityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Severity(Name alias, Table<SeverityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Nederlands: opschaling, GRIP1, GRIP2, etc."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.severity</code> table reference
     */
    public Severity(String alias) {
        this(DSL.name(alias), SEVERITY);
    }

    /**
     * Create an aliased <code>lcms.severity</code> table reference
     */
    public Severity(Name alias) {
        this(alias, SEVERITY);
    }

    /**
     * Create a <code>lcms.severity</code> table reference
     */
    public Severity() {
        this(DSL.name("severity"), null);
    }

    public <O extends Record> Severity(Table<O> path, ForeignKey<O, SeverityRecord> childPath, InverseForeignKey<O, SeverityRecord> parentPath) {
        super(path, childPath, parentPath, SEVERITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SeverityPath extends Severity implements Path<SeverityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SeverityPath(Table<O> path, ForeignKey<O, SeverityRecord> childPath, InverseForeignKey<O, SeverityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SeverityPath(Name alias, Table<SeverityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SeverityPath as(String alias) {
            return new SeverityPath(DSL.name(alias), this);
        }

        @Override
        public SeverityPath as(Name alias) {
            return new SeverityPath(alias, this);
        }

        @Override
        public SeverityPath as(Table<?> alias) {
            return new SeverityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SEVERITY_FK_SEVERITY_SCENARIO_SESSION1_IDX);
    }

    @Override
    public Identity<SeverityRecord, Integer> getIdentity() {
        return (Identity<SeverityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SeverityRecord> getPrimaryKey() {
        return Keys.KEY_SEVERITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<SeverityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SEVERITY_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<SeverityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SEVERITY_SCENARIO_SESSION1);
    }

    private transient ScenarioSessionPath _scenarioSession;

    /**
     * Get the implicit join path to the <code>lcms.scenario_session</code>
     * table.
     */
    public ScenarioSessionPath scenarioSession() {
        if (_scenarioSession == null)
            _scenarioSession = new ScenarioSessionPath(this, Keys.FK_SEVERITY_SCENARIO_SESSION1, null);

        return _scenarioSession;
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit to-many join path to the <code>lcms.activity</code>
     * table
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, null, Keys.FK_ACTIVITY_SEVERITY1.getInverseKey());

        return _activity;
    }

    @Override
    public Severity as(String alias) {
        return new Severity(DSL.name(alias), this);
    }

    @Override
    public Severity as(Name alias) {
        return new Severity(alias, this);
    }

    @Override
    public Severity as(Table<?> alias) {
        return new Severity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Severity rename(String name) {
        return new Severity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Severity rename(Name name) {
        return new Severity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Severity rename(Table<?> name) {
        return new Severity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity where(Condition condition) {
        return new Severity(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Severity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Severity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Severity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Severity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Severity whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
