/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Organisatie.OrganisatiePath;
import nl.tudelft.simulation.lcms.data.tables.Profiel.ProfielPath;
import nl.tudelft.simulation.lcms.data.tables.records.TeamRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Team extends TableImpl<TeamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.team</code>
     */
    public static final Team TEAM = new Team();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamRecord> getRecordType() {
        return TeamRecord.class;
    }

    /**
     * The column <code>lcms.team.id</code>.
     */
    public final TableField<TeamRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.team.organisatie_id</code>.
     */
    public final TableField<TeamRecord, Integer> ORGANISATIE_ID = createField(DSL.name("organisatie_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.team.code</code>.
     */
    public final TableField<TeamRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>lcms.team.naam</code>.
     */
    public final TableField<TeamRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private Team(Name alias, Table<TeamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Team(Name alias, Table<TeamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.team</code> table reference
     */
    public Team(String alias) {
        this(DSL.name(alias), TEAM);
    }

    /**
     * Create an aliased <code>lcms.team</code> table reference
     */
    public Team(Name alias) {
        this(alias, TEAM);
    }

    /**
     * Create a <code>lcms.team</code> table reference
     */
    public Team() {
        this(DSL.name("team"), null);
    }

    public <O extends Record> Team(Table<O> path, ForeignKey<O, TeamRecord> childPath, InverseForeignKey<O, TeamRecord> parentPath) {
        super(path, childPath, parentPath, TEAM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TeamPath extends Team implements Path<TeamRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TeamPath(Table<O> path, ForeignKey<O, TeamRecord> childPath, InverseForeignKey<O, TeamRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TeamPath(Name alias, Table<TeamRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TeamPath as(String alias) {
            return new TeamPath(DSL.name(alias), this);
        }

        @Override
        public TeamPath as(Name alias) {
            return new TeamPath(alias, this);
        }

        @Override
        public TeamPath as(Table<?> alias) {
            return new TeamPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TEAM_FK_TEAM_ORGANISATIE1_IDX);
    }

    @Override
    public Identity<TeamRecord, Integer> getIdentity() {
        return (Identity<TeamRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TeamRecord> getPrimaryKey() {
        return Keys.KEY_TEAM_PRIMARY;
    }

    @Override
    public List<UniqueKey<TeamRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TEAM_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<TeamRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_TEAM_ORGANISATIE1);
    }

    private transient OrganisatiePath _organisatie;

    /**
     * Get the implicit join path to the <code>lcms.organisatie</code> table.
     */
    public OrganisatiePath organisatie() {
        if (_organisatie == null)
            _organisatie = new OrganisatiePath(this, Keys.FK_TEAM_ORGANISATIE1, null);

        return _organisatie;
    }

    private transient ProfielPath _profiel;

    /**
     * Get the implicit to-many join path to the <code>lcms.profiel</code> table
     */
    public ProfielPath profiel() {
        if (_profiel == null)
            _profiel = new ProfielPath(this, null, Keys.FK_PROFIEL_TEAM1.getInverseKey());

        return _profiel;
    }

    @Override
    public Team as(String alias) {
        return new Team(DSL.name(alias), this);
    }

    @Override
    public Team as(Name alias) {
        return new Team(alias, this);
    }

    @Override
    public Team as(Table<?> alias) {
        return new Team(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(String name) {
        return new Team(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(Name name) {
        return new Team(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(Table<?> name) {
        return new Team(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Condition condition) {
        return new Team(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
