/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Punt.PuntPath;
import nl.tudelft.simulation.lcms.data.tables.Veld.VeldPath;
import nl.tudelft.simulation.lcms.data.tables.records.ThemaRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Thema extends TableImpl<ThemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.thema</code>
     */
    public static final Thema THEMA = new Thema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThemaRecord> getRecordType() {
        return ThemaRecord.class;
    }

    /**
     * The column <code>lcms.thema.id</code>.
     */
    public final TableField<ThemaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.thema.veld_id</code>.
     */
    public final TableField<ThemaRecord, Integer> VELD_ID = createField(DSL.name("veld_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.thema.naam</code>.
     */
    public final TableField<ThemaRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    private Thema(Name alias, Table<ThemaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Thema(Name alias, Table<ThemaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.thema</code> table reference
     */
    public Thema(String alias) {
        this(DSL.name(alias), THEMA);
    }

    /**
     * Create an aliased <code>lcms.thema</code> table reference
     */
    public Thema(Name alias) {
        this(alias, THEMA);
    }

    /**
     * Create a <code>lcms.thema</code> table reference
     */
    public Thema() {
        this(DSL.name("thema"), null);
    }

    public <O extends Record> Thema(Table<O> path, ForeignKey<O, ThemaRecord> childPath, InverseForeignKey<O, ThemaRecord> parentPath) {
        super(path, childPath, parentPath, THEMA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ThemaPath extends Thema implements Path<ThemaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ThemaPath(Table<O> path, ForeignKey<O, ThemaRecord> childPath, InverseForeignKey<O, ThemaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ThemaPath(Name alias, Table<ThemaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ThemaPath as(String alias) {
            return new ThemaPath(DSL.name(alias), this);
        }

        @Override
        public ThemaPath as(Name alias) {
            return new ThemaPath(alias, this);
        }

        @Override
        public ThemaPath as(Table<?> alias) {
            return new ThemaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.THEMA_FK_THEMA_VELD1_IDX);
    }

    @Override
    public Identity<ThemaRecord, Integer> getIdentity() {
        return (Identity<ThemaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ThemaRecord> getPrimaryKey() {
        return Keys.KEY_THEMA_PRIMARY;
    }

    @Override
    public List<UniqueKey<ThemaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_THEMA_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ThemaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_THEMA_VELD1);
    }

    private transient VeldPath _veld;

    /**
     * Get the implicit join path to the <code>lcms.veld</code> table.
     */
    public VeldPath veld() {
        if (_veld == null)
            _veld = new VeldPath(this, Keys.FK_THEMA_VELD1, null);

        return _veld;
    }

    private transient PuntPath _punt;

    /**
     * Get the implicit to-many join path to the <code>lcms.punt</code> table
     */
    public PuntPath punt() {
        if (_punt == null)
            _punt = new PuntPath(this, null, Keys.FK_PUNT_THEMA1.getInverseKey());

        return _punt;
    }

    @Override
    public Thema as(String alias) {
        return new Thema(DSL.name(alias), this);
    }

    @Override
    public Thema as(Name alias) {
        return new Thema(alias, this);
    }

    @Override
    public Thema as(Table<?> alias) {
        return new Thema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Thema rename(String name) {
        return new Thema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Thema rename(Name name) {
        return new Thema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Thema rename(Table<?> name) {
        return new Thema(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema where(Condition condition) {
        return new Thema(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Thema where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Thema where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Thema where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Thema where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Thema whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
