/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Field.FieldPath;
import nl.tudelft.simulation.lcms.data.tables.Point.PointPath;
import nl.tudelft.simulation.lcms.data.tables.records.ThemeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Theme extends TableImpl<ThemeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.theme</code>
     */
    public static final Theme THEME = new Theme();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThemeRecord> getRecordType() {
        return ThemeRecord.class;
    }

    /**
     * The column <code>lcms.theme.id</code>.
     */
    public final TableField<ThemeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.theme.name</code>.
     */
    public final TableField<ThemeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>lcms.theme.field_id</code>.
     */
    public final TableField<ThemeRecord, Integer> FIELD_ID = createField(DSL.name("field_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Theme(Name alias, Table<ThemeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Theme(Name alias, Table<ThemeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.theme</code> table reference
     */
    public Theme(String alias) {
        this(DSL.name(alias), THEME);
    }

    /**
     * Create an aliased <code>lcms.theme</code> table reference
     */
    public Theme(Name alias) {
        this(alias, THEME);
    }

    /**
     * Create a <code>lcms.theme</code> table reference
     */
    public Theme() {
        this(DSL.name("theme"), null);
    }

    public <O extends Record> Theme(Table<O> path, ForeignKey<O, ThemeRecord> childPath, InverseForeignKey<O, ThemeRecord> parentPath) {
        super(path, childPath, parentPath, THEME);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ThemePath extends Theme implements Path<ThemeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ThemePath(Table<O> path, ForeignKey<O, ThemeRecord> childPath, InverseForeignKey<O, ThemeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ThemePath(Name alias, Table<ThemeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ThemePath as(String alias) {
            return new ThemePath(DSL.name(alias), this);
        }

        @Override
        public ThemePath as(Name alias) {
            return new ThemePath(alias, this);
        }

        @Override
        public ThemePath as(Table<?> alias) {
            return new ThemePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.THEME_FK_THEME_FIELD1_IDX);
    }

    @Override
    public Identity<ThemeRecord, Integer> getIdentity() {
        return (Identity<ThemeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ThemeRecord> getPrimaryKey() {
        return Keys.KEY_THEME_PRIMARY;
    }

    @Override
    public List<UniqueKey<ThemeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_THEME_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ThemeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_THEME_FIELD1);
    }

    private transient FieldPath _field;

    /**
     * Get the implicit join path to the <code>lcms.field</code> table.
     */
    public FieldPath field() {
        if (_field == null)
            _field = new FieldPath(this, Keys.FK_THEME_FIELD1, null);

        return _field;
    }

    private transient PointPath _point;

    /**
     * Get the implicit to-many join path to the <code>lcms.point</code> table
     */
    public PointPath point() {
        if (_point == null)
            _point = new PointPath(this, null, Keys.FK_POINT_THEME1.getInverseKey());

        return _point;
    }

    @Override
    public Theme as(String alias) {
        return new Theme(DSL.name(alias), this);
    }

    @Override
    public Theme as(Name alias) {
        return new Theme(alias, this);
    }

    @Override
    public Theme as(Table<?> alias) {
        return new Theme(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Theme rename(String name) {
        return new Theme(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Theme rename(Name name) {
        return new Theme(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Theme rename(Table<?> name) {
        return new Theme(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme where(Condition condition) {
        return new Theme(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Theme where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Theme where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Theme where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Theme where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Theme whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
