/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Profile.ProfilePath;
import nl.tudelft.simulation.lcms.data.tables.User.UserPath;
import nl.tudelft.simulation.lcms.data.tables.records.UserProfileRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfile extends TableImpl<UserProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.user_profile</code>
     */
    public static final UserProfile USER_PROFILE = new UserProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserProfileRecord> getRecordType() {
        return UserProfileRecord.class;
    }

    /**
     * The column <code>lcms.user_profile.id</code>.
     */
    public final TableField<UserProfileRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.user_profile.profile_id</code>.
     */
    public final TableField<UserProfileRecord, Integer> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.user_profile.user_id</code>.
     */
    public final TableField<UserProfileRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserProfile(Name alias, Table<UserProfileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserProfile(Name alias, Table<UserProfileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.user_profile</code> table reference
     */
    public UserProfile(String alias) {
        this(DSL.name(alias), USER_PROFILE);
    }

    /**
     * Create an aliased <code>lcms.user_profile</code> table reference
     */
    public UserProfile(Name alias) {
        this(alias, USER_PROFILE);
    }

    /**
     * Create a <code>lcms.user_profile</code> table reference
     */
    public UserProfile() {
        this(DSL.name("user_profile"), null);
    }

    public <O extends Record> UserProfile(Table<O> path, ForeignKey<O, UserProfileRecord> childPath, InverseForeignKey<O, UserProfileRecord> parentPath) {
        super(path, childPath, parentPath, USER_PROFILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserProfilePath extends UserProfile implements Path<UserProfileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserProfilePath(Table<O> path, ForeignKey<O, UserProfileRecord> childPath, InverseForeignKey<O, UserProfileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserProfilePath(Name alias, Table<UserProfileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserProfilePath as(String alias) {
            return new UserProfilePath(DSL.name(alias), this);
        }

        @Override
        public UserProfilePath as(Name alias) {
            return new UserProfilePath(alias, this);
        }

        @Override
        public UserProfilePath as(Table<?> alias) {
            return new UserProfilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_PROFILE_FK_USER_PROFILE_PROFILE1_IDX, Indexes.USER_PROFILE_FK_USER_PROFILE_USER1_IDX);
    }

    @Override
    public Identity<UserProfileRecord, Integer> getIdentity() {
        return (Identity<UserProfileRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserProfileRecord> getPrimaryKey() {
        return Keys.KEY_USER_PROFILE_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserProfileRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_USER_PROFILE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<UserProfileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_PROFILE_PROFILE1, Keys.FK_USER_PROFILE_USER1);
    }

    private transient ProfilePath _profile;

    /**
     * Get the implicit join path to the <code>lcms.profile</code> table.
     */
    public ProfilePath profile() {
        if (_profile == null)
            _profile = new ProfilePath(this, Keys.FK_USER_PROFILE_PROFILE1, null);

        return _profile;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>lcms.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FK_USER_PROFILE_USER1, null);

        return _user;
    }

    @Override
    public UserProfile as(String alias) {
        return new UserProfile(DSL.name(alias), this);
    }

    @Override
    public UserProfile as(Name alias) {
        return new UserProfile(alias, this);
    }

    @Override
    public UserProfile as(Table<?> alias) {
        return new UserProfile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfile rename(String name) {
        return new UserProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfile rename(Name name) {
        return new UserProfile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfile rename(Table<?> name) {
        return new UserProfile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile where(Condition condition) {
        return new UserProfile(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfile whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
