/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activity.ActivityPath;
import nl.tudelft.simulation.lcms.data.tables.User.UserPath;
import nl.tudelft.simulation.lcms.data.tables.records.UserActivityRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserActivity extends TableImpl<UserActivityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.user_activity</code>
     */
    public static final UserActivity USER_ACTIVITY = new UserActivity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserActivityRecord> getRecordType() {
        return UserActivityRecord.class;
    }

    /**
     * The column <code>lcms.user_activity.id</code>.
     */
    public final TableField<UserActivityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.user_activity.read</code>.
     */
    public final TableField<UserActivityRecord, Byte> READ = createField(DSL.name("read"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>lcms.user_activity.activity_id</code>.
     */
    public final TableField<UserActivityRecord, Integer> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.user_activity.user_id</code>.
     */
    public final TableField<UserActivityRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserActivity(Name alias, Table<UserActivityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserActivity(Name alias, Table<UserActivityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.user_activity</code> table reference
     */
    public UserActivity(String alias) {
        this(DSL.name(alias), USER_ACTIVITY);
    }

    /**
     * Create an aliased <code>lcms.user_activity</code> table reference
     */
    public UserActivity(Name alias) {
        this(alias, USER_ACTIVITY);
    }

    /**
     * Create a <code>lcms.user_activity</code> table reference
     */
    public UserActivity() {
        this(DSL.name("user_activity"), null);
    }

    public <O extends Record> UserActivity(Table<O> path, ForeignKey<O, UserActivityRecord> childPath, InverseForeignKey<O, UserActivityRecord> parentPath) {
        super(path, childPath, parentPath, USER_ACTIVITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserActivityPath extends UserActivity implements Path<UserActivityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserActivityPath(Table<O> path, ForeignKey<O, UserActivityRecord> childPath, InverseForeignKey<O, UserActivityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserActivityPath(Name alias, Table<UserActivityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserActivityPath as(String alias) {
            return new UserActivityPath(DSL.name(alias), this);
        }

        @Override
        public UserActivityPath as(Name alias) {
            return new UserActivityPath(alias, this);
        }

        @Override
        public UserActivityPath as(Table<?> alias) {
            return new UserActivityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_ACTIVITY_FK_USER_ACTIVITY_ACTIVITY1_IDX, Indexes.USER_ACTIVITY_FK_USER_ACTIVITY_USER1_IDX);
    }

    @Override
    public Identity<UserActivityRecord, Integer> getIdentity() {
        return (Identity<UserActivityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserActivityRecord> getPrimaryKey() {
        return Keys.KEY_USER_ACTIVITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserActivityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_USER_ACTIVITY_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<UserActivityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_ACTIVITY_ACTIVITY1, Keys.FK_USER_ACTIVITY_USER1);
    }

    private transient ActivityPath _activity;

    /**
     * Get the implicit join path to the <code>lcms.activity</code> table.
     */
    public ActivityPath activity() {
        if (_activity == null)
            _activity = new ActivityPath(this, Keys.FK_USER_ACTIVITY_ACTIVITY1, null);

        return _activity;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>lcms.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FK_USER_ACTIVITY_USER1, null);

        return _user;
    }

    @Override
    public UserActivity as(String alias) {
        return new UserActivity(DSL.name(alias), this);
    }

    @Override
    public UserActivity as(Name alias) {
        return new UserActivity(alias, this);
    }

    @Override
    public UserActivity as(Table<?> alias) {
        return new UserActivity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserActivity rename(String name) {
        return new UserActivity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserActivity rename(Name name) {
        return new UserActivity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserActivity rename(Table<?> name) {
        return new UserActivity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity where(Condition condition) {
        return new UserActivity(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserActivity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserActivity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserActivity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserActivity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserActivity whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
