/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.tudelft.simulation.lcms.data.Indexes;
import nl.tudelft.simulation.lcms.data.Keys;
import nl.tudelft.simulation.lcms.data.Lcms;
import nl.tudelft.simulation.lcms.data.tables.Activiteit.ActiviteitPath;
import nl.tudelft.simulation.lcms.data.tables.Thema.ThemaPath;
import nl.tudelft.simulation.lcms.data.tables.records.VeldRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Veld extends TableImpl<VeldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms.veld</code>
     */
    public static final Veld VELD = new Veld();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VeldRecord> getRecordType() {
        return VeldRecord.class;
    }

    /**
     * The column <code>lcms.veld.id</code>.
     */
    public final TableField<VeldRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>lcms.veld.activiteit_id</code>.
     */
    public final TableField<VeldRecord, Integer> ACTIVITEIT_ID = createField(DSL.name("activiteit_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lcms.veld.naam</code>.
     */
    public final TableField<VeldRecord, String> NAAM = createField(DSL.name("naam"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    private Veld(Name alias, Table<VeldRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Veld(Name alias, Table<VeldRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lcms.veld</code> table reference
     */
    public Veld(String alias) {
        this(DSL.name(alias), VELD);
    }

    /**
     * Create an aliased <code>lcms.veld</code> table reference
     */
    public Veld(Name alias) {
        this(alias, VELD);
    }

    /**
     * Create a <code>lcms.veld</code> table reference
     */
    public Veld() {
        this(DSL.name("veld"), null);
    }

    public <O extends Record> Veld(Table<O> path, ForeignKey<O, VeldRecord> childPath, InverseForeignKey<O, VeldRecord> parentPath) {
        super(path, childPath, parentPath, VELD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VeldPath extends Veld implements Path<VeldRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VeldPath(Table<O> path, ForeignKey<O, VeldRecord> childPath, InverseForeignKey<O, VeldRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VeldPath(Name alias, Table<VeldRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VeldPath as(String alias) {
            return new VeldPath(DSL.name(alias), this);
        }

        @Override
        public VeldPath as(Name alias) {
            return new VeldPath(alias, this);
        }

        @Override
        public VeldPath as(Table<?> alias) {
            return new VeldPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Lcms.LCMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VELD_FK_VELD_ACTIVITEIT1_IDX);
    }

    @Override
    public Identity<VeldRecord, Integer> getIdentity() {
        return (Identity<VeldRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<VeldRecord> getPrimaryKey() {
        return Keys.KEY_VELD_PRIMARY;
    }

    @Override
    public List<UniqueKey<VeldRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_VELD_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<VeldRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_VELD_ACTIVITEIT1);
    }

    private transient ActiviteitPath _activiteit;

    /**
     * Get the implicit join path to the <code>lcms.activiteit</code> table.
     */
    public ActiviteitPath activiteit() {
        if (_activiteit == null)
            _activiteit = new ActiviteitPath(this, Keys.FK_VELD_ACTIVITEIT1, null);

        return _activiteit;
    }

    private transient ThemaPath _thema;

    /**
     * Get the implicit to-many join path to the <code>lcms.thema</code> table
     */
    public ThemaPath thema() {
        if (_thema == null)
            _thema = new ThemaPath(this, null, Keys.FK_THEMA_VELD1.getInverseKey());

        return _thema;
    }

    @Override
    public Veld as(String alias) {
        return new Veld(DSL.name(alias), this);
    }

    @Override
    public Veld as(Name alias) {
        return new Veld(alias, this);
    }

    @Override
    public Veld as(Table<?> alias) {
        return new Veld(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Veld rename(String name) {
        return new Veld(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Veld rename(Name name) {
        return new Veld(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Veld rename(Table<?> name) {
        return new Veld(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld where(Condition condition) {
        return new Veld(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Veld where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Veld where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Veld where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Veld where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Veld whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
