/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data;


import nl.tudelft.simulation.lcms.data.tables.Activity;
import nl.tudelft.simulation.lcms.data.tables.ActivityType;
import nl.tudelft.simulation.lcms.data.tables.Appendix;
import nl.tudelft.simulation.lcms.data.tables.Discipline;
import nl.tudelft.simulation.lcms.data.tables.Domain;
import nl.tudelft.simulation.lcms.data.tables.Field;
import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation;
import nl.tudelft.simulation.lcms.data.tables.Log;
import nl.tudelft.simulation.lcms.data.tables.Organisation;
import nl.tudelft.simulation.lcms.data.tables.Point;
import nl.tudelft.simulation.lcms.data.tables.Profile;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession;
import nl.tudelft.simulation.lcms.data.tables.Session;
import nl.tudelft.simulation.lcms.data.tables.Severity;
import nl.tudelft.simulation.lcms.data.tables.Team;
import nl.tudelft.simulation.lcms.data.tables.Theme;
import nl.tudelft.simulation.lcms.data.tables.UserActivity;
import nl.tudelft.simulation.lcms.data.tables.UserProfile;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in lcms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTIVITY_FK_ACTIVITY_ACTIVITY_TYPE1_IDX = Internal.createIndex(DSL.name("fk_activity_activity_type1_idx"), Activity.ACTIVITY, new OrderField[] { Activity.ACTIVITY.ACTIVITY_TYPE_ID }, false);
    public static final Index ACTIVITY_FK_ACTIVITY_ORGANISATION1_IDX = Internal.createIndex(DSL.name("fk_activity_organisation1_idx"), Activity.ACTIVITY, new OrderField[] { Activity.ACTIVITY.ORGANISATION_ID }, false);
    public static final Index ACTIVITY_FK_ACTIVITY_SEVERITY1_IDX = Internal.createIndex(DSL.name("fk_activity_severity1_idx"), Activity.ACTIVITY, new OrderField[] { Activity.ACTIVITY.SEVERITY_ID }, false);
    public static final Index ACTIVITY_TYPE_FK_ACTIVITY_TYPE_SCENARIO_SESSION1_IDX = Internal.createIndex(DSL.name("fk_activity_type_scenario_session1_idx"), ActivityType.ACTIVITY_TYPE, new OrderField[] { ActivityType.ACTIVITY_TYPE.SCENARIO_SESSION_ID }, false);
    public static final Index APPENDIX_FK_APPENDIX_ACTIVITY1_IDX = Internal.createIndex(DSL.name("fk_appendix_activity1_idx"), Appendix.APPENDIX, new OrderField[] { Appendix.APPENDIX.ACTIVITY_ID }, false);
    public static final Index DISCIPLINE_FK_DISCIPLINE_SCENARIO_SESSION1_IDX = Internal.createIndex(DSL.name("fk_discipline_scenario_session1_idx"), Discipline.DISCIPLINE, new OrderField[] { Discipline.DISCIPLINE.SCENARIO_SESSION_ID }, false);
    public static final Index DOMAIN_FK_DOMAIN_SCENARIO_SESSION1_IDX = Internal.createIndex(DSL.name("fk_domain_scenario_session1_idx"), Domain.DOMAIN, new OrderField[] { Domain.DOMAIN.SCENARIO_SESSION_ID }, false);
    public static final Index FIELD_FK_FIELD_ACTIVITY1_IDX = Internal.createIndex(DSL.name("fk_field_activity1_idx"), Field.FIELD, new OrderField[] { Field.FIELD.ACTIVITY_ID }, false);
    public static final Index INVOLVED_ORGANISATION_FK_INVOLVED_ORGANIZATION_ACTIVITY1_IDX = Internal.createIndex(DSL.name("fk_involved_organization_activity1_idx"), InvolvedOrganisation.INVOLVED_ORGANISATION, new OrderField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ACTIVITY_ID }, false);
    public static final Index INVOLVED_ORGANISATION_FK_INVOLVED_ORGANIZATION_ORGANISATION1_IDX = Internal.createIndex(DSL.name("fk_involved_organization_organisation1_idx"), InvolvedOrganisation.INVOLVED_ORGANISATION, new OrderField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ORGANISATION_ID }, false);
    public static final Index LOG_FK_LOG_USER1_IDX = Internal.createIndex(DSL.name("fk_log_user1_idx"), Log.LOG, new OrderField[] { Log.LOG.USER_ID }, false);
    public static final Index ORGANISATION_FK_ORGANISATIE_DOMAIN1_IDX = Internal.createIndex(DSL.name("fk_organisatie_domain1_idx"), Organisation.ORGANISATION, new OrderField[] { Organisation.ORGANISATION.DOMAIN_ID }, false);
    public static final Index POINT_FK_POINT_THEME1_IDX = Internal.createIndex(DSL.name("fk_point_theme1_idx"), Point.POINT, new OrderField[] { Point.POINT.THEME_ID }, false);
    public static final Index PROFILE_FK_PROFIEL_DISCIPLINE1_IDX = Internal.createIndex(DSL.name("fk_profiel_discipline1_idx"), Profile.PROFILE, new OrderField[] { Profile.PROFILE.DISCIPLINE_ID }, false);
    public static final Index PROFILE_FK_PROFIEL_TEAM1_IDX = Internal.createIndex(DSL.name("fk_profiel_team1_idx"), Profile.PROFILE, new OrderField[] { Profile.PROFILE.TEAM_ID }, false);
    public static final Index SCENARIO_SESSION_FK_SCENARIO_SESSIE_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_scenario_sessie_scenario1_idx"), ScenarioSession.SCENARIO_SESSION, new OrderField[] { ScenarioSession.SCENARIO_SESSION.SCENARIO_ID }, false);
    public static final Index SCENARIO_SESSION_FK_SCENARIO_SESSION_SESSION1_IDX = Internal.createIndex(DSL.name("fk_scenario_session_session1_idx"), ScenarioSession.SCENARIO_SESSION, new OrderField[] { ScenarioSession.SCENARIO_SESSION.SESSION_ID }, false);
    public static final Index SESSION_FK_SESSION_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_session_scenario1_idx"), Session.SESSION, new OrderField[] { Session.SESSION.SCENARIO_ID }, false);
    public static final Index SEVERITY_FK_SEVERITY_SCENARIO_SESSION1_IDX = Internal.createIndex(DSL.name("fk_severity_scenario_session1_idx"), Severity.SEVERITY, new OrderField[] { Severity.SEVERITY.SCENARIO_SESSION_ID }, false);
    public static final Index TEAM_FK_TEAM_ORGANISATION1_IDX = Internal.createIndex(DSL.name("fk_team_organisation1_idx"), Team.TEAM, new OrderField[] { Team.TEAM.ORGANISATION_ID }, false);
    public static final Index THEME_FK_THEME_FIELD1_IDX = Internal.createIndex(DSL.name("fk_theme_field1_idx"), Theme.THEME, new OrderField[] { Theme.THEME.FIELD_ID }, false);
    public static final Index USER_ACTIVITY_FK_USER_ACTIVITY_ACTIVITY1_IDX = Internal.createIndex(DSL.name("fk_user_activity_activity1_idx"), UserActivity.USER_ACTIVITY, new OrderField[] { UserActivity.USER_ACTIVITY.ACTIVITY_ID }, false);
    public static final Index USER_ACTIVITY_FK_USER_ACTIVITY_USER1_IDX = Internal.createIndex(DSL.name("fk_user_activity_user1_idx"), UserActivity.USER_ACTIVITY, new OrderField[] { UserActivity.USER_ACTIVITY.USER_ID }, false);
    public static final Index USER_PROFILE_FK_USER_PROFILE_PROFILE1_IDX = Internal.createIndex(DSL.name("fk_user_profile_profile1_idx"), UserProfile.USER_PROFILE, new OrderField[] { UserProfile.USER_PROFILE.PROFILE_ID }, false);
    public static final Index USER_PROFILE_FK_USER_PROFILE_USER1_IDX = Internal.createIndex(DSL.name("fk_user_profile_user1_idx"), UserProfile.USER_PROFILE, new OrderField[] { UserProfile.USER_PROFILE.USER_ID }, false);
}
