/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data;


import nl.tudelft.simulation.lcms.data.tables.Activity;
import nl.tudelft.simulation.lcms.data.tables.ActivityType;
import nl.tudelft.simulation.lcms.data.tables.Appendix;
import nl.tudelft.simulation.lcms.data.tables.Discipline;
import nl.tudelft.simulation.lcms.data.tables.Domain;
import nl.tudelft.simulation.lcms.data.tables.Field;
import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation;
import nl.tudelft.simulation.lcms.data.tables.Log;
import nl.tudelft.simulation.lcms.data.tables.Organisation;
import nl.tudelft.simulation.lcms.data.tables.Point;
import nl.tudelft.simulation.lcms.data.tables.Profile;
import nl.tudelft.simulation.lcms.data.tables.Scenario;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession;
import nl.tudelft.simulation.lcms.data.tables.Session;
import nl.tudelft.simulation.lcms.data.tables.Severity;
import nl.tudelft.simulation.lcms.data.tables.Team;
import nl.tudelft.simulation.lcms.data.tables.Theme;
import nl.tudelft.simulation.lcms.data.tables.User;
import nl.tudelft.simulation.lcms.data.tables.UserActivity;
import nl.tudelft.simulation.lcms.data.tables.UserProfile;
import nl.tudelft.simulation.lcms.data.tables.records.ActivityRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ActivityTypeRecord;
import nl.tudelft.simulation.lcms.data.tables.records.AppendixRecord;
import nl.tudelft.simulation.lcms.data.tables.records.DisciplineRecord;
import nl.tudelft.simulation.lcms.data.tables.records.DomainRecord;
import nl.tudelft.simulation.lcms.data.tables.records.FieldRecord;
import nl.tudelft.simulation.lcms.data.tables.records.InvolvedOrganisationRecord;
import nl.tudelft.simulation.lcms.data.tables.records.LogRecord;
import nl.tudelft.simulation.lcms.data.tables.records.OrganisationRecord;
import nl.tudelft.simulation.lcms.data.tables.records.PointRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ProfileRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioSessionRecord;
import nl.tudelft.simulation.lcms.data.tables.records.SessionRecord;
import nl.tudelft.simulation.lcms.data.tables.records.SeverityRecord;
import nl.tudelft.simulation.lcms.data.tables.records.TeamRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ThemeRecord;
import nl.tudelft.simulation.lcms.data.tables.records.UserActivityRecord;
import nl.tudelft.simulation.lcms.data.tables.records.UserProfileRecord;
import nl.tudelft.simulation.lcms.data.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * lcms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_ID_UNIQUE = Internal.createUniqueKey(Activity.ACTIVITY, DSL.name("KEY_activity_id_UNIQUE"), new TableField[] { Activity.ACTIVITY.ID }, true);
    public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_PRIMARY = Internal.createUniqueKey(Activity.ACTIVITY, DSL.name("KEY_activity_PRIMARY"), new TableField[] { Activity.ACTIVITY.ID }, true);
    public static final UniqueKey<ActivityTypeRecord> KEY_ACTIVITY_TYPE_ID_UNIQUE = Internal.createUniqueKey(ActivityType.ACTIVITY_TYPE, DSL.name("KEY_activity_type_id_UNIQUE"), new TableField[] { ActivityType.ACTIVITY_TYPE.ID }, true);
    public static final UniqueKey<ActivityTypeRecord> KEY_ACTIVITY_TYPE_PRIMARY = Internal.createUniqueKey(ActivityType.ACTIVITY_TYPE, DSL.name("KEY_activity_type_PRIMARY"), new TableField[] { ActivityType.ACTIVITY_TYPE.ID }, true);
    public static final UniqueKey<AppendixRecord> KEY_APPENDIX_ID_UNIQUE = Internal.createUniqueKey(Appendix.APPENDIX, DSL.name("KEY_appendix_id_UNIQUE"), new TableField[] { Appendix.APPENDIX.ID }, true);
    public static final UniqueKey<AppendixRecord> KEY_APPENDIX_PRIMARY = Internal.createUniqueKey(Appendix.APPENDIX, DSL.name("KEY_appendix_PRIMARY"), new TableField[] { Appendix.APPENDIX.ID }, true);
    public static final UniqueKey<DisciplineRecord> KEY_DISCIPLINE_ID_UNIQUE = Internal.createUniqueKey(Discipline.DISCIPLINE, DSL.name("KEY_discipline_id_UNIQUE"), new TableField[] { Discipline.DISCIPLINE.ID }, true);
    public static final UniqueKey<DisciplineRecord> KEY_DISCIPLINE_PRIMARY = Internal.createUniqueKey(Discipline.DISCIPLINE, DSL.name("KEY_discipline_PRIMARY"), new TableField[] { Discipline.DISCIPLINE.ID }, true);
    public static final UniqueKey<DomainRecord> KEY_DOMAIN_ID_UNIQUE = Internal.createUniqueKey(Domain.DOMAIN, DSL.name("KEY_domain_id_UNIQUE"), new TableField[] { Domain.DOMAIN.ID }, true);
    public static final UniqueKey<DomainRecord> KEY_DOMAIN_PRIMARY = Internal.createUniqueKey(Domain.DOMAIN, DSL.name("KEY_domain_PRIMARY"), new TableField[] { Domain.DOMAIN.ID }, true);
    public static final UniqueKey<FieldRecord> KEY_FIELD_ID_UNIQUE = Internal.createUniqueKey(Field.FIELD, DSL.name("KEY_field_id_UNIQUE"), new TableField[] { Field.FIELD.ID }, true);
    public static final UniqueKey<FieldRecord> KEY_FIELD_PRIMARY = Internal.createUniqueKey(Field.FIELD, DSL.name("KEY_field_PRIMARY"), new TableField[] { Field.FIELD.ID }, true);
    public static final UniqueKey<InvolvedOrganisationRecord> KEY_INVOLVED_ORGANISATION_ID_UNIQUE = Internal.createUniqueKey(InvolvedOrganisation.INVOLVED_ORGANISATION, DSL.name("KEY_involved_organisation_id_UNIQUE"), new TableField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ID }, true);
    public static final UniqueKey<InvolvedOrganisationRecord> KEY_INVOLVED_ORGANISATION_PRIMARY = Internal.createUniqueKey(InvolvedOrganisation.INVOLVED_ORGANISATION, DSL.name("KEY_involved_organisation_PRIMARY"), new TableField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ID }, true);
    public static final UniqueKey<LogRecord> KEY_LOG_ID_UNIQUE = Internal.createUniqueKey(Log.LOG, DSL.name("KEY_log_id_UNIQUE"), new TableField[] { Log.LOG.ID }, true);
    public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = Internal.createUniqueKey(Log.LOG, DSL.name("KEY_log_PRIMARY"), new TableField[] { Log.LOG.ID }, true);
    public static final UniqueKey<OrganisationRecord> KEY_ORGANISATION_ID_UNIQUE = Internal.createUniqueKey(Organisation.ORGANISATION, DSL.name("KEY_organisation_id_UNIQUE"), new TableField[] { Organisation.ORGANISATION.ID }, true);
    public static final UniqueKey<OrganisationRecord> KEY_ORGANISATION_PRIMARY = Internal.createUniqueKey(Organisation.ORGANISATION, DSL.name("KEY_organisation_PRIMARY"), new TableField[] { Organisation.ORGANISATION.ID }, true);
    public static final UniqueKey<PointRecord> KEY_POINT_ID_UNIQUE = Internal.createUniqueKey(Point.POINT, DSL.name("KEY_point_id_UNIQUE"), new TableField[] { Point.POINT.ID }, true);
    public static final UniqueKey<PointRecord> KEY_POINT_PRIMARY = Internal.createUniqueKey(Point.POINT, DSL.name("KEY_point_PRIMARY"), new TableField[] { Point.POINT.ID }, true);
    public static final UniqueKey<ProfileRecord> KEY_PROFILE_ID_UNIQUE = Internal.createUniqueKey(Profile.PROFILE, DSL.name("KEY_profile_id_UNIQUE"), new TableField[] { Profile.PROFILE.ID }, true);
    public static final UniqueKey<ProfileRecord> KEY_PROFILE_PRIMARY = Internal.createUniqueKey(Profile.PROFILE, DSL.name("KEY_profile_PRIMARY"), new TableField[] { Profile.PROFILE.ID }, true);
    public static final UniqueKey<ScenarioRecord> KEY_SCENARIO_ID_UNIQUE = Internal.createUniqueKey(Scenario.SCENARIO, DSL.name("KEY_scenario_id_UNIQUE"), new TableField[] { Scenario.SCENARIO.ID }, true);
    public static final UniqueKey<ScenarioRecord> KEY_SCENARIO_PRIMARY = Internal.createUniqueKey(Scenario.SCENARIO, DSL.name("KEY_scenario_PRIMARY"), new TableField[] { Scenario.SCENARIO.ID }, true);
    public static final UniqueKey<ScenarioSessionRecord> KEY_SCENARIO_SESSION_ID_UNIQUE = Internal.createUniqueKey(ScenarioSession.SCENARIO_SESSION, DSL.name("KEY_scenario_session_id_UNIQUE"), new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true);
    public static final UniqueKey<ScenarioSessionRecord> KEY_SCENARIO_SESSION_PRIMARY = Internal.createUniqueKey(ScenarioSession.SCENARIO_SESSION, DSL.name("KEY_scenario_session_PRIMARY"), new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true);
    public static final UniqueKey<SessionRecord> KEY_SESSION_ID_UNIQUE = Internal.createUniqueKey(Session.SESSION, DSL.name("KEY_session_id_UNIQUE"), new TableField[] { Session.SESSION.ID }, true);
    public static final UniqueKey<SessionRecord> KEY_SESSION_PRIMARY = Internal.createUniqueKey(Session.SESSION, DSL.name("KEY_session_PRIMARY"), new TableField[] { Session.SESSION.ID }, true);
    public static final UniqueKey<SeverityRecord> KEY_SEVERITY_ID_UNIQUE = Internal.createUniqueKey(Severity.SEVERITY, DSL.name("KEY_severity_id_UNIQUE"), new TableField[] { Severity.SEVERITY.ID }, true);
    public static final UniqueKey<SeverityRecord> KEY_SEVERITY_PRIMARY = Internal.createUniqueKey(Severity.SEVERITY, DSL.name("KEY_severity_PRIMARY"), new TableField[] { Severity.SEVERITY.ID }, true);
    public static final UniqueKey<TeamRecord> KEY_TEAM_ID_UNIQUE = Internal.createUniqueKey(Team.TEAM, DSL.name("KEY_team_id_UNIQUE"), new TableField[] { Team.TEAM.ID }, true);
    public static final UniqueKey<TeamRecord> KEY_TEAM_PRIMARY = Internal.createUniqueKey(Team.TEAM, DSL.name("KEY_team_PRIMARY"), new TableField[] { Team.TEAM.ID }, true);
    public static final UniqueKey<ThemeRecord> KEY_THEME_ID_UNIQUE = Internal.createUniqueKey(Theme.THEME, DSL.name("KEY_theme_id_UNIQUE"), new TableField[] { Theme.THEME.ID }, true);
    public static final UniqueKey<ThemeRecord> KEY_THEME_PRIMARY = Internal.createUniqueKey(Theme.THEME, DSL.name("KEY_theme_PRIMARY"), new TableField[] { Theme.THEME.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_ID_UNIQUE = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_id_UNIQUE"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserActivityRecord> KEY_USER_ACTIVITY_ID_UNIQUE = Internal.createUniqueKey(UserActivity.USER_ACTIVITY, DSL.name("KEY_user_activity_id_UNIQUE"), new TableField[] { UserActivity.USER_ACTIVITY.ID }, true);
    public static final UniqueKey<UserActivityRecord> KEY_USER_ACTIVITY_PRIMARY = Internal.createUniqueKey(UserActivity.USER_ACTIVITY, DSL.name("KEY_user_activity_PRIMARY"), new TableField[] { UserActivity.USER_ACTIVITY.ID }, true);
    public static final UniqueKey<UserProfileRecord> KEY_USER_PROFILE_ID_UNIQUE = Internal.createUniqueKey(UserProfile.USER_PROFILE, DSL.name("KEY_user_profile_id_UNIQUE"), new TableField[] { UserProfile.USER_PROFILE.ID }, true);
    public static final UniqueKey<UserProfileRecord> KEY_USER_PROFILE_PRIMARY = Internal.createUniqueKey(UserProfile.USER_PROFILE, DSL.name("KEY_user_profile_PRIMARY"), new TableField[] { UserProfile.USER_PROFILE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActivityRecord, ActivityTypeRecord> FK_ACTIVITY_ACTIVITY_TYPE1 = Internal.createForeignKey(Activity.ACTIVITY, DSL.name("fk_activity_activity_type1"), new TableField[] { Activity.ACTIVITY.ACTIVITY_TYPE_ID }, Keys.KEY_ACTIVITY_TYPE_PRIMARY, new TableField[] { ActivityType.ACTIVITY_TYPE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActivityRecord, OrganisationRecord> FK_ACTIVITY_ORGANISATION1 = Internal.createForeignKey(Activity.ACTIVITY, DSL.name("fk_activity_organisation1"), new TableField[] { Activity.ACTIVITY.ORGANISATION_ID }, Keys.KEY_ORGANISATION_PRIMARY, new TableField[] { Organisation.ORGANISATION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActivityRecord, SeverityRecord> FK_ACTIVITY_SEVERITY1 = Internal.createForeignKey(Activity.ACTIVITY, DSL.name("fk_activity_severity1"), new TableField[] { Activity.ACTIVITY.SEVERITY_ID }, Keys.KEY_SEVERITY_PRIMARY, new TableField[] { Severity.SEVERITY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActivityTypeRecord, ScenarioSessionRecord> FK_ACTIVITY_TYPE_SCENARIO_SESSION1 = Internal.createForeignKey(ActivityType.ACTIVITY_TYPE, DSL.name("fk_activity_type_scenario_session1"), new TableField[] { ActivityType.ACTIVITY_TYPE.SCENARIO_SESSION_ID }, Keys.KEY_SCENARIO_SESSION_PRIMARY, new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<AppendixRecord, ActivityRecord> FK_APPENDIX_ACTIVITY1 = Internal.createForeignKey(Appendix.APPENDIX, DSL.name("fk_appendix_activity1"), new TableField[] { Appendix.APPENDIX.ACTIVITY_ID }, Keys.KEY_ACTIVITY_PRIMARY, new TableField[] { Activity.ACTIVITY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DisciplineRecord, ScenarioSessionRecord> FK_DISCIPLINE_SCENARIO_SESSION1 = Internal.createForeignKey(Discipline.DISCIPLINE, DSL.name("fk_discipline_scenario_session1"), new TableField[] { Discipline.DISCIPLINE.SCENARIO_SESSION_ID }, Keys.KEY_SCENARIO_SESSION_PRIMARY, new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DomainRecord, ScenarioSessionRecord> FK_DOMAIN_SCENARIO_SESSION1 = Internal.createForeignKey(Domain.DOMAIN, DSL.name("fk_domain_scenario_session1"), new TableField[] { Domain.DOMAIN.SCENARIO_SESSION_ID }, Keys.KEY_SCENARIO_SESSION_PRIMARY, new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<FieldRecord, ActivityRecord> FK_FIELD_ACTIVITY1 = Internal.createForeignKey(Field.FIELD, DSL.name("fk_field_activity1"), new TableField[] { Field.FIELD.ACTIVITY_ID }, Keys.KEY_ACTIVITY_PRIMARY, new TableField[] { Activity.ACTIVITY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<InvolvedOrganisationRecord, ActivityRecord> FK_INVOLVED_ORGANIZATION_ACTIVITY1 = Internal.createForeignKey(InvolvedOrganisation.INVOLVED_ORGANISATION, DSL.name("fk_involved_organization_activity1"), new TableField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ACTIVITY_ID }, Keys.KEY_ACTIVITY_PRIMARY, new TableField[] { Activity.ACTIVITY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<InvolvedOrganisationRecord, OrganisationRecord> FK_INVOLVED_ORGANIZATION_ORGANISATION1 = Internal.createForeignKey(InvolvedOrganisation.INVOLVED_ORGANISATION, DSL.name("fk_involved_organization_organisation1"), new TableField[] { InvolvedOrganisation.INVOLVED_ORGANISATION.ORGANISATION_ID }, Keys.KEY_ORGANISATION_PRIMARY, new TableField[] { Organisation.ORGANISATION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<LogRecord, UserRecord> FK_LOG_USER1 = Internal.createForeignKey(Log.LOG, DSL.name("fk_log_user1"), new TableField[] { Log.LOG.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<OrganisationRecord, DomainRecord> FK_ORGANISATIE_DOMAIN1 = Internal.createForeignKey(Organisation.ORGANISATION, DSL.name("fk_organisatie_domain1"), new TableField[] { Organisation.ORGANISATION.DOMAIN_ID }, Keys.KEY_DOMAIN_PRIMARY, new TableField[] { Domain.DOMAIN.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PointRecord, ThemeRecord> FK_POINT_THEME1 = Internal.createForeignKey(Point.POINT, DSL.name("fk_point_theme1"), new TableField[] { Point.POINT.THEME_ID }, Keys.KEY_THEME_PRIMARY, new TableField[] { Theme.THEME.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ProfileRecord, DisciplineRecord> FK_PROFIEL_DISCIPLINE1 = Internal.createForeignKey(Profile.PROFILE, DSL.name("fk_profiel_discipline1"), new TableField[] { Profile.PROFILE.DISCIPLINE_ID }, Keys.KEY_DISCIPLINE_PRIMARY, new TableField[] { Discipline.DISCIPLINE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ProfileRecord, TeamRecord> FK_PROFIEL_TEAM1 = Internal.createForeignKey(Profile.PROFILE, DSL.name("fk_profiel_team1"), new TableField[] { Profile.PROFILE.TEAM_ID }, Keys.KEY_TEAM_PRIMARY, new TableField[] { Team.TEAM.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ScenarioSessionRecord, ScenarioRecord> FK_SCENARIO_SESSIE_SCENARIO1 = Internal.createForeignKey(ScenarioSession.SCENARIO_SESSION, DSL.name("fk_scenario_sessie_scenario1"), new TableField[] { ScenarioSession.SCENARIO_SESSION.SCENARIO_ID }, Keys.KEY_SCENARIO_PRIMARY, new TableField[] { Scenario.SCENARIO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ScenarioSessionRecord, SessionRecord> FK_SCENARIO_SESSION_SESSION1 = Internal.createForeignKey(ScenarioSession.SCENARIO_SESSION, DSL.name("fk_scenario_session_session1"), new TableField[] { ScenarioSession.SCENARIO_SESSION.SESSION_ID }, Keys.KEY_SESSION_PRIMARY, new TableField[] { Session.SESSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SessionRecord, ScenarioRecord> FK_SESSION_SCENARIO1 = Internal.createForeignKey(Session.SESSION, DSL.name("fk_session_scenario1"), new TableField[] { Session.SESSION.SCENARIO_ID }, Keys.KEY_SCENARIO_PRIMARY, new TableField[] { Scenario.SCENARIO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SeverityRecord, ScenarioSessionRecord> FK_SEVERITY_SCENARIO_SESSION1 = Internal.createForeignKey(Severity.SEVERITY, DSL.name("fk_severity_scenario_session1"), new TableField[] { Severity.SEVERITY.SCENARIO_SESSION_ID }, Keys.KEY_SCENARIO_SESSION_PRIMARY, new TableField[] { ScenarioSession.SCENARIO_SESSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TeamRecord, OrganisationRecord> FK_TEAM_ORGANISATION1 = Internal.createForeignKey(Team.TEAM, DSL.name("fk_team_organisation1"), new TableField[] { Team.TEAM.ORGANISATION_ID }, Keys.KEY_ORGANISATION_PRIMARY, new TableField[] { Organisation.ORGANISATION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ThemeRecord, FieldRecord> FK_THEME_FIELD1 = Internal.createForeignKey(Theme.THEME, DSL.name("fk_theme_field1"), new TableField[] { Theme.THEME.FIELD_ID }, Keys.KEY_FIELD_PRIMARY, new TableField[] { Field.FIELD.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserActivityRecord, ActivityRecord> FK_USER_ACTIVITY_ACTIVITY1 = Internal.createForeignKey(UserActivity.USER_ACTIVITY, DSL.name("fk_user_activity_activity1"), new TableField[] { UserActivity.USER_ACTIVITY.ACTIVITY_ID }, Keys.KEY_ACTIVITY_PRIMARY, new TableField[] { Activity.ACTIVITY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserActivityRecord, UserRecord> FK_USER_ACTIVITY_USER1 = Internal.createForeignKey(UserActivity.USER_ACTIVITY, DSL.name("fk_user_activity_user1"), new TableField[] { UserActivity.USER_ACTIVITY.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserProfileRecord, ProfileRecord> FK_USER_PROFILE_PROFILE1 = Internal.createForeignKey(UserProfile.USER_PROFILE, DSL.name("fk_user_profile_profile1"), new TableField[] { UserProfile.USER_PROFILE.PROFILE_ID }, Keys.KEY_PROFILE_PRIMARY, new TableField[] { Profile.PROFILE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserProfileRecord, UserRecord> FK_USER_PROFILE_USER1 = Internal.createForeignKey(UserProfile.USER_PROFILE, DSL.name("fk_user_profile_user1"), new TableField[] { UserProfile.USER_PROFILE.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
