/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data;


import nl.tudelft.simulation.lcms.data.tables.Activiteit;
import nl.tudelft.simulation.lcms.data.tables.ActiviteitType;
import nl.tudelft.simulation.lcms.data.tables.BetrokkenOrganisatie;
import nl.tudelft.simulation.lcms.data.tables.Bijlage;
import nl.tudelft.simulation.lcms.data.tables.Discipline;
import nl.tudelft.simulation.lcms.data.tables.Domein;
import nl.tudelft.simulation.lcms.data.tables.Gebruiker;
import nl.tudelft.simulation.lcms.data.tables.GebruikerActiviteit;
import nl.tudelft.simulation.lcms.data.tables.GebruikerProfiel;
import nl.tudelft.simulation.lcms.data.tables.Log;
import nl.tudelft.simulation.lcms.data.tables.Opschaling;
import nl.tudelft.simulation.lcms.data.tables.Organisatie;
import nl.tudelft.simulation.lcms.data.tables.Profiel;
import nl.tudelft.simulation.lcms.data.tables.Punt;
import nl.tudelft.simulation.lcms.data.tables.Scenario;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie;
import nl.tudelft.simulation.lcms.data.tables.Sessie;
import nl.tudelft.simulation.lcms.data.tables.Team;
import nl.tudelft.simulation.lcms.data.tables.Thema;
import nl.tudelft.simulation.lcms.data.tables.Veld;
import nl.tudelft.simulation.lcms.data.tables.records.ActiviteitRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ActiviteitTypeRecord;
import nl.tudelft.simulation.lcms.data.tables.records.BetrokkenOrganisatieRecord;
import nl.tudelft.simulation.lcms.data.tables.records.BijlageRecord;
import nl.tudelft.simulation.lcms.data.tables.records.DisciplineRecord;
import nl.tudelft.simulation.lcms.data.tables.records.DomeinRecord;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerActiviteitRecord;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerProfielRecord;
import nl.tudelft.simulation.lcms.data.tables.records.GebruikerRecord;
import nl.tudelft.simulation.lcms.data.tables.records.LogRecord;
import nl.tudelft.simulation.lcms.data.tables.records.OpschalingRecord;
import nl.tudelft.simulation.lcms.data.tables.records.OrganisatieRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ProfielRecord;
import nl.tudelft.simulation.lcms.data.tables.records.PuntRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ScenarioSessieRecord;
import nl.tudelft.simulation.lcms.data.tables.records.SessieRecord;
import nl.tudelft.simulation.lcms.data.tables.records.TeamRecord;
import nl.tudelft.simulation.lcms.data.tables.records.ThemaRecord;
import nl.tudelft.simulation.lcms.data.tables.records.VeldRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * lcms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActiviteitRecord> KEY_ACTIVITEIT_ID_UNIQUE = Internal.createUniqueKey(Activiteit.ACTIVITEIT, DSL.name("KEY_activiteit_id_UNIQUE"), new TableField[] { Activiteit.ACTIVITEIT.ID }, true);
    public static final UniqueKey<ActiviteitRecord> KEY_ACTIVITEIT_PRIMARY = Internal.createUniqueKey(Activiteit.ACTIVITEIT, DSL.name("KEY_activiteit_PRIMARY"), new TableField[] { Activiteit.ACTIVITEIT.ID }, true);
    public static final UniqueKey<ActiviteitTypeRecord> KEY_ACTIVITEIT_TYPE_ID_UNIQUE = Internal.createUniqueKey(ActiviteitType.ACTIVITEIT_TYPE, DSL.name("KEY_activiteit_type_id_UNIQUE"), new TableField[] { ActiviteitType.ACTIVITEIT_TYPE.ID }, true);
    public static final UniqueKey<ActiviteitTypeRecord> KEY_ACTIVITEIT_TYPE_PRIMARY = Internal.createUniqueKey(ActiviteitType.ACTIVITEIT_TYPE, DSL.name("KEY_activiteit_type_PRIMARY"), new TableField[] { ActiviteitType.ACTIVITEIT_TYPE.ID }, true);
    public static final UniqueKey<BetrokkenOrganisatieRecord> KEY_BETROKKEN_ORGANISATIE_ID_UNIQUE = Internal.createUniqueKey(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE, DSL.name("KEY_betrokken_organisatie_id_UNIQUE"), new TableField[] { BetrokkenOrganisatie.BETROKKEN_ORGANISATIE.ID }, true);
    public static final UniqueKey<BetrokkenOrganisatieRecord> KEY_BETROKKEN_ORGANISATIE_PRIMARY = Internal.createUniqueKey(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE, DSL.name("KEY_betrokken_organisatie_PRIMARY"), new TableField[] { BetrokkenOrganisatie.BETROKKEN_ORGANISATIE.ID }, true);
    public static final UniqueKey<BijlageRecord> KEY_BIJLAGE_ID_UNIQUE = Internal.createUniqueKey(Bijlage.BIJLAGE, DSL.name("KEY_bijlage_id_UNIQUE"), new TableField[] { Bijlage.BIJLAGE.ID }, true);
    public static final UniqueKey<BijlageRecord> KEY_BIJLAGE_PRIMARY = Internal.createUniqueKey(Bijlage.BIJLAGE, DSL.name("KEY_bijlage_PRIMARY"), new TableField[] { Bijlage.BIJLAGE.ID }, true);
    public static final UniqueKey<DisciplineRecord> KEY_DISCIPLINE_ID_UNIQUE = Internal.createUniqueKey(Discipline.DISCIPLINE, DSL.name("KEY_discipline_id_UNIQUE"), new TableField[] { Discipline.DISCIPLINE.ID }, true);
    public static final UniqueKey<DisciplineRecord> KEY_DISCIPLINE_PRIMARY = Internal.createUniqueKey(Discipline.DISCIPLINE, DSL.name("KEY_discipline_PRIMARY"), new TableField[] { Discipline.DISCIPLINE.ID }, true);
    public static final UniqueKey<DomeinRecord> KEY_DOMEIN_ID_UNIQUE = Internal.createUniqueKey(Domein.DOMEIN, DSL.name("KEY_domein_id_UNIQUE"), new TableField[] { Domein.DOMEIN.ID }, true);
    public static final UniqueKey<DomeinRecord> KEY_DOMEIN_PRIMARY = Internal.createUniqueKey(Domein.DOMEIN, DSL.name("KEY_domein_PRIMARY"), new TableField[] { Domein.DOMEIN.ID }, true);
    public static final UniqueKey<GebruikerRecord> KEY_GEBRUIKER_ID_UNIQUE = Internal.createUniqueKey(Gebruiker.GEBRUIKER, DSL.name("KEY_gebruiker_id_UNIQUE"), new TableField[] { Gebruiker.GEBRUIKER.ID }, true);
    public static final UniqueKey<GebruikerRecord> KEY_GEBRUIKER_PRIMARY = Internal.createUniqueKey(Gebruiker.GEBRUIKER, DSL.name("KEY_gebruiker_PRIMARY"), new TableField[] { Gebruiker.GEBRUIKER.ID }, true);
    public static final UniqueKey<GebruikerActiviteitRecord> KEY_GEBRUIKER_ACTIVITEIT_ID_UNIQUE = Internal.createUniqueKey(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT, DSL.name("KEY_gebruiker_activiteit_id_UNIQUE"), new TableField[] { GebruikerActiviteit.GEBRUIKER_ACTIVITEIT.ID }, true);
    public static final UniqueKey<GebruikerActiviteitRecord> KEY_GEBRUIKER_ACTIVITEIT_PRIMARY = Internal.createUniqueKey(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT, DSL.name("KEY_gebruiker_activiteit_PRIMARY"), new TableField[] { GebruikerActiviteit.GEBRUIKER_ACTIVITEIT.ID }, true);
    public static final UniqueKey<GebruikerProfielRecord> KEY_GEBRUIKER_PROFIEL_ID_UNIQUE = Internal.createUniqueKey(GebruikerProfiel.GEBRUIKER_PROFIEL, DSL.name("KEY_gebruiker_profiel_id_UNIQUE"), new TableField[] { GebruikerProfiel.GEBRUIKER_PROFIEL.ID }, true);
    public static final UniqueKey<GebruikerProfielRecord> KEY_GEBRUIKER_PROFIEL_PRIMARY = Internal.createUniqueKey(GebruikerProfiel.GEBRUIKER_PROFIEL, DSL.name("KEY_gebruiker_profiel_PRIMARY"), new TableField[] { GebruikerProfiel.GEBRUIKER_PROFIEL.ID }, true);
    public static final UniqueKey<LogRecord> KEY_LOG_ID_UNIQUE = Internal.createUniqueKey(Log.LOG, DSL.name("KEY_log_id_UNIQUE"), new TableField[] { Log.LOG.ID }, true);
    public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = Internal.createUniqueKey(Log.LOG, DSL.name("KEY_log_PRIMARY"), new TableField[] { Log.LOG.ID }, true);
    public static final UniqueKey<OpschalingRecord> KEY_OPSCHALING_ID_UNIQUE = Internal.createUniqueKey(Opschaling.OPSCHALING, DSL.name("KEY_opschaling_id_UNIQUE"), new TableField[] { Opschaling.OPSCHALING.ID }, true);
    public static final UniqueKey<OpschalingRecord> KEY_OPSCHALING_PRIMARY = Internal.createUniqueKey(Opschaling.OPSCHALING, DSL.name("KEY_opschaling_PRIMARY"), new TableField[] { Opschaling.OPSCHALING.ID }, true);
    public static final UniqueKey<OrganisatieRecord> KEY_ORGANISATIE_ID_UNIQUE = Internal.createUniqueKey(Organisatie.ORGANISATIE, DSL.name("KEY_organisatie_id_UNIQUE"), new TableField[] { Organisatie.ORGANISATIE.ID }, true);
    public static final UniqueKey<OrganisatieRecord> KEY_ORGANISATIE_PRIMARY = Internal.createUniqueKey(Organisatie.ORGANISATIE, DSL.name("KEY_organisatie_PRIMARY"), new TableField[] { Organisatie.ORGANISATIE.ID }, true);
    public static final UniqueKey<ProfielRecord> KEY_PROFIEL_ID_UNIQUE = Internal.createUniqueKey(Profiel.PROFIEL, DSL.name("KEY_profiel_id_UNIQUE"), new TableField[] { Profiel.PROFIEL.ID }, true);
    public static final UniqueKey<ProfielRecord> KEY_PROFIEL_PRIMARY = Internal.createUniqueKey(Profiel.PROFIEL, DSL.name("KEY_profiel_PRIMARY"), new TableField[] { Profiel.PROFIEL.ID }, true);
    public static final UniqueKey<PuntRecord> KEY_PUNT_ID_UNIQUE = Internal.createUniqueKey(Punt.PUNT, DSL.name("KEY_punt_id_UNIQUE"), new TableField[] { Punt.PUNT.ID }, true);
    public static final UniqueKey<PuntRecord> KEY_PUNT_PRIMARY = Internal.createUniqueKey(Punt.PUNT, DSL.name("KEY_punt_PRIMARY"), new TableField[] { Punt.PUNT.ID }, true);
    public static final UniqueKey<ScenarioRecord> KEY_SCENARIO_ID_UNIQUE = Internal.createUniqueKey(Scenario.SCENARIO, DSL.name("KEY_scenario_id_UNIQUE"), new TableField[] { Scenario.SCENARIO.ID }, true);
    public static final UniqueKey<ScenarioRecord> KEY_SCENARIO_PRIMARY = Internal.createUniqueKey(Scenario.SCENARIO, DSL.name("KEY_scenario_PRIMARY"), new TableField[] { Scenario.SCENARIO.ID }, true);
    public static final UniqueKey<ScenarioSessieRecord> KEY_SCENARIO_SESSIE_ID_UNIQUE = Internal.createUniqueKey(ScenarioSessie.SCENARIO_SESSIE, DSL.name("KEY_scenario_sessie_id_UNIQUE"), new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true);
    public static final UniqueKey<ScenarioSessieRecord> KEY_SCENARIO_SESSIE_PRIMARY = Internal.createUniqueKey(ScenarioSessie.SCENARIO_SESSIE, DSL.name("KEY_scenario_sessie_PRIMARY"), new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true);
    public static final UniqueKey<SessieRecord> KEY_SESSIE_ID_UNIQUE = Internal.createUniqueKey(Sessie.SESSIE, DSL.name("KEY_sessie_id_UNIQUE"), new TableField[] { Sessie.SESSIE.ID }, true);
    public static final UniqueKey<SessieRecord> KEY_SESSIE_PRIMARY = Internal.createUniqueKey(Sessie.SESSIE, DSL.name("KEY_sessie_PRIMARY"), new TableField[] { Sessie.SESSIE.ID }, true);
    public static final UniqueKey<TeamRecord> KEY_TEAM_ID_UNIQUE = Internal.createUniqueKey(Team.TEAM, DSL.name("KEY_team_id_UNIQUE"), new TableField[] { Team.TEAM.ID }, true);
    public static final UniqueKey<TeamRecord> KEY_TEAM_PRIMARY = Internal.createUniqueKey(Team.TEAM, DSL.name("KEY_team_PRIMARY"), new TableField[] { Team.TEAM.ID }, true);
    public static final UniqueKey<ThemaRecord> KEY_THEMA_ID_UNIQUE = Internal.createUniqueKey(Thema.THEMA, DSL.name("KEY_thema_id_UNIQUE"), new TableField[] { Thema.THEMA.ID }, true);
    public static final UniqueKey<ThemaRecord> KEY_THEMA_PRIMARY = Internal.createUniqueKey(Thema.THEMA, DSL.name("KEY_thema_PRIMARY"), new TableField[] { Thema.THEMA.ID }, true);
    public static final UniqueKey<VeldRecord> KEY_VELD_ID_UNIQUE = Internal.createUniqueKey(Veld.VELD, DSL.name("KEY_veld_id_UNIQUE"), new TableField[] { Veld.VELD.ID }, true);
    public static final UniqueKey<VeldRecord> KEY_VELD_PRIMARY = Internal.createUniqueKey(Veld.VELD, DSL.name("KEY_veld_PRIMARY"), new TableField[] { Veld.VELD.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActiviteitRecord, ActiviteitTypeRecord> FK_ACTIVITEIT_ACTIVITEIT_TYPE1 = Internal.createForeignKey(Activiteit.ACTIVITEIT, DSL.name("fk_activiteit_activiteit_type1"), new TableField[] { Activiteit.ACTIVITEIT.ACTIVITEIT_TYPE_ID }, Keys.KEY_ACTIVITEIT_TYPE_PRIMARY, new TableField[] { ActiviteitType.ACTIVITEIT_TYPE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActiviteitRecord, OpschalingRecord> FK_ACTIVITEIT_OPSCHALING1 = Internal.createForeignKey(Activiteit.ACTIVITEIT, DSL.name("fk_activiteit_opschaling1"), new TableField[] { Activiteit.ACTIVITEIT.OPSCHALING_ID }, Keys.KEY_OPSCHALING_PRIMARY, new TableField[] { Opschaling.OPSCHALING.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActiviteitRecord, OrganisatieRecord> FK_ACTIVITEIT_ORGANISATIE1 = Internal.createForeignKey(Activiteit.ACTIVITEIT, DSL.name("fk_activiteit_organisatie1"), new TableField[] { Activiteit.ACTIVITEIT.ORGANISATIE_ID }, Keys.KEY_ORGANISATIE_PRIMARY, new TableField[] { Organisatie.ORGANISATIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ActiviteitTypeRecord, ScenarioSessieRecord> FK_ACTIVITEIT_TYPE_SCENARIO_SESSIE1 = Internal.createForeignKey(ActiviteitType.ACTIVITEIT_TYPE, DSL.name("fk_activiteit_type_scenario_sessie1"), new TableField[] { ActiviteitType.ACTIVITEIT_TYPE.SCENARIO_SESSIE_ID }, Keys.KEY_SCENARIO_SESSIE_PRIMARY, new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BetrokkenOrganisatieRecord, ActiviteitRecord> FK_BETROKKEN_ORGANISATIE_ACTIVITEIT1 = Internal.createForeignKey(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE, DSL.name("fk_betrokken_organisatie_activiteit1"), new TableField[] { BetrokkenOrganisatie.BETROKKEN_ORGANISATIE.ACTIVITEIT_ID }, Keys.KEY_ACTIVITEIT_PRIMARY, new TableField[] { Activiteit.ACTIVITEIT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BetrokkenOrganisatieRecord, OrganisatieRecord> FK_BETROKKEN_ORGANISATIE_ORGANISATIE1 = Internal.createForeignKey(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE, DSL.name("fk_betrokken_organisatie_organisatie1"), new TableField[] { BetrokkenOrganisatie.BETROKKEN_ORGANISATIE.ORGANISATIE_ID }, Keys.KEY_ORGANISATIE_PRIMARY, new TableField[] { Organisatie.ORGANISATIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BijlageRecord, ActiviteitRecord> FK_BIJLAGE_ACTIVITEIT1 = Internal.createForeignKey(Bijlage.BIJLAGE, DSL.name("fk_bijlage_activiteit1"), new TableField[] { Bijlage.BIJLAGE.ACTIVITEIT_ID }, Keys.KEY_ACTIVITEIT_PRIMARY, new TableField[] { Activiteit.ACTIVITEIT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DisciplineRecord, ScenarioSessieRecord> FK_DISCIPLINE_SCENARIO_SESSIE1 = Internal.createForeignKey(Discipline.DISCIPLINE, DSL.name("fk_discipline_scenario_sessie1"), new TableField[] { Discipline.DISCIPLINE.SCENARIO_SESSIE_ID }, Keys.KEY_SCENARIO_SESSIE_PRIMARY, new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DomeinRecord, ScenarioSessieRecord> FK_DOMEIN_SCENARIO_SESSIE1 = Internal.createForeignKey(Domein.DOMEIN, DSL.name("fk_domein_scenario_sessie1"), new TableField[] { Domein.DOMEIN.SCENARIO_SESSIE_ID }, Keys.KEY_SCENARIO_SESSIE_PRIMARY, new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<GebruikerActiviteitRecord, ActiviteitRecord> FK_GEBRUIKER_ACTIVITEIT_ACTIVITEIT1 = Internal.createForeignKey(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT, DSL.name("fk_gebruiker_activiteit_activiteit1"), new TableField[] { GebruikerActiviteit.GEBRUIKER_ACTIVITEIT.ACTIVITEIT_ID }, Keys.KEY_ACTIVITEIT_PRIMARY, new TableField[] { Activiteit.ACTIVITEIT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<GebruikerActiviteitRecord, GebruikerRecord> FK_GEBRUIKER_ACTIVITEIT_GEBRUIKER1 = Internal.createForeignKey(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT, DSL.name("fk_gebruiker_activiteit_gebruiker1"), new TableField[] { GebruikerActiviteit.GEBRUIKER_ACTIVITEIT.GEBRUIKER_ID }, Keys.KEY_GEBRUIKER_PRIMARY, new TableField[] { Gebruiker.GEBRUIKER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<GebruikerProfielRecord, GebruikerRecord> FK_GEBRUIKER_PROFIEL_GEBRUIKER1 = Internal.createForeignKey(GebruikerProfiel.GEBRUIKER_PROFIEL, DSL.name("fk_gebruiker_profiel_gebruiker1"), new TableField[] { GebruikerProfiel.GEBRUIKER_PROFIEL.GEBRUIKER_ID }, Keys.KEY_GEBRUIKER_PRIMARY, new TableField[] { Gebruiker.GEBRUIKER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<GebruikerProfielRecord, ProfielRecord> FK_GEBRUIKER_PROFIEL_PROFIEL1 = Internal.createForeignKey(GebruikerProfiel.GEBRUIKER_PROFIEL, DSL.name("fk_gebruiker_profiel_profiel1"), new TableField[] { GebruikerProfiel.GEBRUIKER_PROFIEL.PROFIEL_ID }, Keys.KEY_PROFIEL_PRIMARY, new TableField[] { Profiel.PROFIEL.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<LogRecord, GebruikerRecord> FK_LOG_GEBRUIKER1 = Internal.createForeignKey(Log.LOG, DSL.name("fk_log_gebruiker1"), new TableField[] { Log.LOG.GEBRUIKER_ID }, Keys.KEY_GEBRUIKER_PRIMARY, new TableField[] { Gebruiker.GEBRUIKER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<OpschalingRecord, ScenarioSessieRecord> FK_OPSCHALING_SCENARIO_SESSIE1 = Internal.createForeignKey(Opschaling.OPSCHALING, DSL.name("fk_opschaling_scenario_sessie1"), new TableField[] { Opschaling.OPSCHALING.SCENARIO_SESSIE_ID }, Keys.KEY_SCENARIO_SESSIE_PRIMARY, new TableField[] { ScenarioSessie.SCENARIO_SESSIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<OrganisatieRecord, DomeinRecord> FK_ORGANISATIE_DOMEIN1 = Internal.createForeignKey(Organisatie.ORGANISATIE, DSL.name("fk_organisatie_domein1"), new TableField[] { Organisatie.ORGANISATIE.DOMEIN_ID }, Keys.KEY_DOMEIN_PRIMARY, new TableField[] { Domein.DOMEIN.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ProfielRecord, DisciplineRecord> FK_PROFIEL_DISCIPLINE1 = Internal.createForeignKey(Profiel.PROFIEL, DSL.name("fk_profiel_discipline1"), new TableField[] { Profiel.PROFIEL.DISCIPLINE_ID }, Keys.KEY_DISCIPLINE_PRIMARY, new TableField[] { Discipline.DISCIPLINE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ProfielRecord, TeamRecord> FK_PROFIEL_TEAM1 = Internal.createForeignKey(Profiel.PROFIEL, DSL.name("fk_profiel_team1"), new TableField[] { Profiel.PROFIEL.TEAM_ID }, Keys.KEY_TEAM_PRIMARY, new TableField[] { Team.TEAM.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PuntRecord, ThemaRecord> FK_PUNT_THEMA1 = Internal.createForeignKey(Punt.PUNT, DSL.name("fk_punt_thema1"), new TableField[] { Punt.PUNT.THEMA_ID }, Keys.KEY_THEMA_PRIMARY, new TableField[] { Thema.THEMA.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ScenarioSessieRecord, ScenarioRecord> FK_SCENARIO_SESSIE_SCENARIO1 = Internal.createForeignKey(ScenarioSessie.SCENARIO_SESSIE, DSL.name("fk_scenario_sessie_scenario1"), new TableField[] { ScenarioSessie.SCENARIO_SESSIE.SCENARIO_ID }, Keys.KEY_SCENARIO_PRIMARY, new TableField[] { Scenario.SCENARIO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ScenarioSessieRecord, SessieRecord> FK_SCENARIO_SESSIE_SESSIE1 = Internal.createForeignKey(ScenarioSessie.SCENARIO_SESSIE, DSL.name("fk_scenario_sessie_sessie1"), new TableField[] { ScenarioSessie.SCENARIO_SESSIE.SESSIE_ID }, Keys.KEY_SESSIE_PRIMARY, new TableField[] { Sessie.SESSIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SessieRecord, ScenarioRecord> FK_SESSIE_SCENARIO1 = Internal.createForeignKey(Sessie.SESSIE, DSL.name("fk_sessie_scenario1"), new TableField[] { Sessie.SESSIE.SCENARIO_ID }, Keys.KEY_SCENARIO_PRIMARY, new TableField[] { Scenario.SCENARIO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TeamRecord, OrganisatieRecord> FK_TEAM_ORGANISATIE1 = Internal.createForeignKey(Team.TEAM, DSL.name("fk_team_organisatie1"), new TableField[] { Team.TEAM.ORGANISATIE_ID }, Keys.KEY_ORGANISATIE_PRIMARY, new TableField[] { Organisatie.ORGANISATIE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ThemaRecord, VeldRecord> FK_THEMA_VELD1 = Internal.createForeignKey(Thema.THEMA, DSL.name("fk_thema_veld1"), new TableField[] { Thema.THEMA.VELD_ID }, Keys.KEY_VELD_PRIMARY, new TableField[] { Veld.VELD.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<VeldRecord, ActiviteitRecord> FK_VELD_ACTIVITEIT1 = Internal.createForeignKey(Veld.VELD, DSL.name("fk_veld_activiteit1"), new TableField[] { Veld.VELD.ACTIVITEIT_ID }, Keys.KEY_ACTIVITEIT_PRIMARY, new TableField[] { Activiteit.ACTIVITEIT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
