/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data;


import java.util.Arrays;
import java.util.List;

import nl.tudelft.simulation.lcms.data.tables.Activiteit;
import nl.tudelft.simulation.lcms.data.tables.ActiviteitType;
import nl.tudelft.simulation.lcms.data.tables.Admin;
import nl.tudelft.simulation.lcms.data.tables.BetrokkenOrganisatie;
import nl.tudelft.simulation.lcms.data.tables.Bijlage;
import nl.tudelft.simulation.lcms.data.tables.Discipline;
import nl.tudelft.simulation.lcms.data.tables.Domein;
import nl.tudelft.simulation.lcms.data.tables.Gebruiker;
import nl.tudelft.simulation.lcms.data.tables.GebruikerActiviteit;
import nl.tudelft.simulation.lcms.data.tables.GebruikerProfiel;
import nl.tudelft.simulation.lcms.data.tables.Log;
import nl.tudelft.simulation.lcms.data.tables.Opschaling;
import nl.tudelft.simulation.lcms.data.tables.Organisatie;
import nl.tudelft.simulation.lcms.data.tables.Profiel;
import nl.tudelft.simulation.lcms.data.tables.Punt;
import nl.tudelft.simulation.lcms.data.tables.Scenario;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie;
import nl.tudelft.simulation.lcms.data.tables.Sessie;
import nl.tudelft.simulation.lcms.data.tables.Team;
import nl.tudelft.simulation.lcms.data.tables.Thema;
import nl.tudelft.simulation.lcms.data.tables.Veld;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lcms extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lcms</code>
     */
    public static final Lcms LCMS = new Lcms();

    /**
     * The table <code>lcms.activiteit</code>.
     */
    public final Activiteit ACTIVITEIT = Activiteit.ACTIVITEIT;

    /**
     * The table <code>lcms.activiteit_type</code>.
     */
    public final ActiviteitType ACTIVITEIT_TYPE = ActiviteitType.ACTIVITEIT_TYPE;

    /**
     * The table <code>lcms.admin</code>.
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>lcms.betrokken_organisatie</code>.
     */
    public final BetrokkenOrganisatie BETROKKEN_ORGANISATIE = BetrokkenOrganisatie.BETROKKEN_ORGANISATIE;

    /**
     * The table <code>lcms.bijlage</code>.
     */
    public final Bijlage BIJLAGE = Bijlage.BIJLAGE;

    /**
     * The table <code>lcms.discipline</code>.
     */
    public final Discipline DISCIPLINE = Discipline.DISCIPLINE;

    /**
     * The table <code>lcms.domein</code>.
     */
    public final Domein DOMEIN = Domein.DOMEIN;

    /**
     * The table <code>lcms.gebruiker</code>.
     */
    public final Gebruiker GEBRUIKER = Gebruiker.GEBRUIKER;

    /**
     * The table <code>lcms.gebruiker_activiteit</code>.
     */
    public final GebruikerActiviteit GEBRUIKER_ACTIVITEIT = GebruikerActiviteit.GEBRUIKER_ACTIVITEIT;

    /**
     * The table <code>lcms.gebruiker_profiel</code>.
     */
    public final GebruikerProfiel GEBRUIKER_PROFIEL = GebruikerProfiel.GEBRUIKER_PROFIEL;

    /**
     * The table <code>lcms.log</code>.
     */
    public final Log LOG = Log.LOG;

    /**
     * The table <code>lcms.opschaling</code>.
     */
    public final Opschaling OPSCHALING = Opschaling.OPSCHALING;

    /**
     * The table <code>lcms.organisatie</code>.
     */
    public final Organisatie ORGANISATIE = Organisatie.ORGANISATIE;

    /**
     * The table <code>lcms.profiel</code>.
     */
    public final Profiel PROFIEL = Profiel.PROFIEL;

    /**
     * The table <code>lcms.punt</code>.
     */
    public final Punt PUNT = Punt.PUNT;

    /**
     * The table <code>lcms.scenario</code>.
     */
    public final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>lcms.scenario_sessie</code>.
     */
    public final ScenarioSessie SCENARIO_SESSIE = ScenarioSessie.SCENARIO_SESSIE;

    /**
     * The table <code>lcms.sessie</code>.
     */
    public final Sessie SESSIE = Sessie.SESSIE;

    /**
     * The table <code>lcms.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>lcms.thema</code>.
     */
    public final Thema THEMA = Thema.THEMA;

    /**
     * The table <code>lcms.veld</code>.
     */
    public final Veld VELD = Veld.VELD;

    /**
     * No further instances allowed
     */
    private Lcms() {
        super(DSL.name("lcms"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Activiteit.ACTIVITEIT,
            ActiviteitType.ACTIVITEIT_TYPE,
            Admin.ADMIN,
            BetrokkenOrganisatie.BETROKKEN_ORGANISATIE,
            Bijlage.BIJLAGE,
            Discipline.DISCIPLINE,
            Domein.DOMEIN,
            Gebruiker.GEBRUIKER,
            GebruikerActiviteit.GEBRUIKER_ACTIVITEIT,
            GebruikerProfiel.GEBRUIKER_PROFIEL,
            Log.LOG,
            Opschaling.OPSCHALING,
            Organisatie.ORGANISATIE,
            Profiel.PROFIEL,
            Punt.PUNT,
            Scenario.SCENARIO,
            ScenarioSessie.SCENARIO_SESSIE,
            Sessie.SESSIE,
            Team.TEAM,
            Thema.THEMA,
            Veld.VELD
        );
    }
}
