/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data;


import nl.tudelft.simulation.lcms.data.tables.Activity;
import nl.tudelft.simulation.lcms.data.tables.ActivityType;
import nl.tudelft.simulation.lcms.data.tables.Appendix;
import nl.tudelft.simulation.lcms.data.tables.Discipline;
import nl.tudelft.simulation.lcms.data.tables.Domain;
import nl.tudelft.simulation.lcms.data.tables.Field;
import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation;
import nl.tudelft.simulation.lcms.data.tables.Log;
import nl.tudelft.simulation.lcms.data.tables.Organisation;
import nl.tudelft.simulation.lcms.data.tables.Point;
import nl.tudelft.simulation.lcms.data.tables.Profile;
import nl.tudelft.simulation.lcms.data.tables.Scenario;
import nl.tudelft.simulation.lcms.data.tables.ScenarioSession;
import nl.tudelft.simulation.lcms.data.tables.Session;
import nl.tudelft.simulation.lcms.data.tables.Severity;
import nl.tudelft.simulation.lcms.data.tables.Team;
import nl.tudelft.simulation.lcms.data.tables.Theme;
import nl.tudelft.simulation.lcms.data.tables.User;
import nl.tudelft.simulation.lcms.data.tables.UserActivity;
import nl.tudelft.simulation.lcms.data.tables.UserProfile;


/**
 * Convenience access to all tables in lcms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>lcms.activity</code>.
     */
    public static final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>lcms.activity_type</code>.
     */
    public static final ActivityType ACTIVITY_TYPE = ActivityType.ACTIVITY_TYPE;

    /**
     * The table <code>lcms.appendix</code>.
     */
    public static final Appendix APPENDIX = Appendix.APPENDIX;

    /**
     * The table <code>lcms.discipline</code>.
     */
    public static final Discipline DISCIPLINE = Discipline.DISCIPLINE;

    /**
     * The table <code>lcms.domain</code>.
     */
    public static final Domain DOMAIN = Domain.DOMAIN;

    /**
     * The table <code>lcms.field</code>.
     */
    public static final Field FIELD = Field.FIELD;

    /**
     * The table <code>lcms.involved_organisation</code>.
     */
    public static final InvolvedOrganisation INVOLVED_ORGANISATION = InvolvedOrganisation.INVOLVED_ORGANISATION;

    /**
     * The table <code>lcms.log</code>.
     */
    public static final Log LOG = Log.LOG;

    /**
     * The table <code>lcms.organisation</code>.
     */
    public static final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>lcms.point</code>.
     */
    public static final Point POINT = Point.POINT;

    /**
     * The table <code>lcms.profile</code>.
     */
    public static final Profile PROFILE = Profile.PROFILE;

    /**
     * The table <code>lcms.scenario</code>.
     */
    public static final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>lcms.scenario_session</code>.
     */
    public static final ScenarioSession SCENARIO_SESSION = ScenarioSession.SCENARIO_SESSION;

    /**
     * The table <code>lcms.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * Nederlands: opschaling, GRIP1, GRIP2, etc.
     */
    public static final Severity SEVERITY = Severity.SEVERITY;

    /**
     * The table <code>lcms.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>lcms.theme</code>.
     */
    public static final Theme THEME = Theme.THEME;

    /**
     * The table <code>lcms.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>lcms.user_activity</code>.
     */
    public static final UserActivity USER_ACTIVITY = UserActivity.USER_ACTIVITY;

    /**
     * The table <code>lcms.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
