/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.ActiviteitType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActiviteitTypeRecord extends UpdatableRecordImpl<ActiviteitTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.activiteit_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.activiteit_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.activiteit_type.scenario_sessie_id</code>.
     */
    public void setScenarioSessieId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.activiteit_type.scenario_sessie_id</code>.
     */
    public Integer getScenarioSessieId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.activiteit_type.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.activiteit_type.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActiviteitTypeRecord
     */
    public ActiviteitTypeRecord() {
        super(ActiviteitType.ACTIVITEIT_TYPE);
    }

    /**
     * Create a detached, initialised ActiviteitTypeRecord
     */
    public ActiviteitTypeRecord(Integer id, Integer scenarioSessieId, String naam) {
        super(ActiviteitType.ACTIVITEIT_TYPE);

        setId(id);
        setScenarioSessieId(scenarioSessieId);
        setNaam(naam);
        resetTouchedOnNotNull();
    }
}
