/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.ActivityType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityTypeRecord extends UpdatableRecordImpl<ActivityTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.activity_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.activity_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.activity_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.activity_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.activity_type.scenario_session_id</code>.
     */
    public void setScenarioSessionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.activity_type.scenario_session_id</code>.
     */
    public Integer getScenarioSessionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityTypeRecord
     */
    public ActivityTypeRecord() {
        super(ActivityType.ACTIVITY_TYPE);
    }

    /**
     * Create a detached, initialised ActivityTypeRecord
     */
    public ActivityTypeRecord(Integer id, String name, Integer scenarioSessionId) {
        super(ActivityType.ACTIVITY_TYPE);

        setId(id);
        setName(name);
        setScenarioSessionId(scenarioSessionId);
        resetTouchedOnNotNull();
    }
}
