/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.lcms.data.tables.Activity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityRecord extends UpdatableRecordImpl<ActivityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.activity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.activity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.activity.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.activity.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.activity.location</code>.
     */
    public void setLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.activity.location</code>.
     */
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.activity.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.activity.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>lcms.activity.date_changed</code>.
     */
    public void setDateChanged(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.activity.date_changed</code>.
     */
    public LocalDateTime getDateChanged() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lcms.activity.closed</code>.
     */
    public void setClosed(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.activity.closed</code>.
     */
    public Byte getClosed() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>lcms.activity.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lcms.activity.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>lcms.activity.organisation_id</code>.
     */
    public void setOrganisationId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lcms.activity.organisation_id</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lcms.activity.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>lcms.activity.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(Integer id, String name, String location, LocalDateTime dateCreated, LocalDateTime dateChanged, Byte closed, Integer activityTypeId, Integer organisationId, Integer severityId) {
        super(Activity.ACTIVITY);

        setId(id);
        setName(name);
        setLocation(location);
        setDateCreated(dateCreated);
        setDateChanged(dateChanged);
        setClosed(closed);
        setActivityTypeId(activityTypeId);
        setOrganisationId(organisationId);
        setSeverityId(severityId);
        resetTouchedOnNotNull();
    }
}
