/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.lcms.data.tables.Activiteit;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActiviteitRecord extends UpdatableRecordImpl<ActiviteitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.activiteit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.activiteit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.activiteit.naam</code>.
     */
    public void setNaam(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.activiteit.naam</code>.
     */
    public String getNaam() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.activiteit.locatie</code>.
     */
    public void setLocatie(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.activiteit.locatie</code>.
     */
    public String getLocatie() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.activiteit.organisatie_id</code>. eigenaar
     */
    public void setOrganisatieId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.activiteit.organisatie_id</code>. eigenaar
     */
    public Integer getOrganisatieId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lcms.activiteit.opschaling_id</code>.
     */
    public void setOpschalingId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.activiteit.opschaling_id</code>.
     */
    public Integer getOpschalingId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lcms.activiteit.activiteit_type_id</code>.
     */
    public void setActiviteitTypeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.activiteit.activiteit_type_id</code>.
     */
    public Integer getActiviteitTypeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lcms.activiteit.datum_aanmaak</code>.
     */
    public void setDatumAanmaak(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>lcms.activiteit.datum_aanmaak</code>.
     */
    public LocalDateTime getDatumAanmaak() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>lcms.activiteit.datum_wijziging</code>.
     */
    public void setDatumWijziging(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>lcms.activiteit.datum_wijziging</code>.
     */
    public LocalDateTime getDatumWijziging() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>lcms.activiteit.besloten</code>.
     */
    public void setBesloten(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>lcms.activiteit.besloten</code>.
     */
    public Byte getBesloten() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActiviteitRecord
     */
    public ActiviteitRecord() {
        super(Activiteit.ACTIVITEIT);
    }

    /**
     * Create a detached, initialised ActiviteitRecord
     */
    public ActiviteitRecord(Integer id, String naam, String locatie, Integer organisatieId, Integer opschalingId, Integer activiteitTypeId, LocalDateTime datumAanmaak, LocalDateTime datumWijziging, Byte besloten) {
        super(Activiteit.ACTIVITEIT);

        setId(id);
        setNaam(naam);
        setLocatie(locatie);
        setOrganisatieId(organisatieId);
        setOpschalingId(opschalingId);
        setActiviteitTypeId(activiteitTypeId);
        setDatumAanmaak(datumAanmaak);
        setDatumWijziging(datumWijziging);
        setBesloten(besloten);
        resetTouchedOnNotNull();
    }
}
