/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Admin;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.admin.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.admin.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.admin.inlog_naam</code>.
     */
    public void setInlogNaam(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.admin.inlog_naam</code>.
     */
    public String getInlogNaam() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.admin.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.admin.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.admin.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.admin.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lcms.admin.admin</code>.
     */
    public void setAdmin(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.admin.admin</code>.
     */
    public Byte getAdmin() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>lcms.admin.facilitator</code>.
     */
    public void setFacilitator(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.admin.facilitator</code>.
     */
    public Byte getFacilitator() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>lcms.admin.onderzoeker</code>.
     */
    public void setOnderzoeker(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>lcms.admin.onderzoeker</code>.
     */
    public Byte getOnderzoeker() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(Integer id, String inlogNaam, String naam, String passwordHash, Byte admin, Byte facilitator, Byte onderzoeker) {
        super(Admin.ADMIN);

        setId(id);
        setInlogNaam(inlogNaam);
        setNaam(naam);
        setPasswordHash(passwordHash);
        setAdmin(admin);
        setFacilitator(facilitator);
        setOnderzoeker(onderzoeker);
        resetTouchedOnNotNull();
    }
}
