/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.BetrokkenOrganisatie;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BetrokkenOrganisatieRecord extends UpdatableRecordImpl<BetrokkenOrganisatieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.betrokken_organisatie.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.betrokken_organisatie.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.betrokken_organisatie.activiteit_id</code>.
     */
    public void setActiviteitId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.betrokken_organisatie.activiteit_id</code>.
     */
    public Integer getActiviteitId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.betrokken_organisatie.organisatie_id</code>.
     */
    public void setOrganisatieId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.betrokken_organisatie.organisatie_id</code>.
     */
    public Integer getOrganisatieId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BetrokkenOrganisatieRecord
     */
    public BetrokkenOrganisatieRecord() {
        super(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE);
    }

    /**
     * Create a detached, initialised BetrokkenOrganisatieRecord
     */
    public BetrokkenOrganisatieRecord(Integer id, Integer activiteitId, Integer organisatieId) {
        super(BetrokkenOrganisatie.BETROKKEN_ORGANISATIE);

        setId(id);
        setActiviteitId(activiteitId);
        setOrganisatieId(organisatieId);
        resetTouchedOnNotNull();
    }
}
