/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Bijlage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BijlageRecord extends UpdatableRecordImpl<BijlageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.bijlage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.bijlage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.bijlage.activiteit_id</code>.
     */
    public void setActiviteitId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.bijlage.activiteit_id</code>.
     */
    public Integer getActiviteitId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.bijlage.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.bijlage.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.bijlage.inhoud</code>.
     */
    public void setInhoud(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.bijlage.inhoud</code>.
     */
    public byte[] getInhoud() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BijlageRecord
     */
    public BijlageRecord() {
        super(Bijlage.BIJLAGE);
    }

    /**
     * Create a detached, initialised BijlageRecord
     */
    public BijlageRecord(Integer id, Integer activiteitId, String type, byte[] inhoud) {
        super(Bijlage.BIJLAGE);

        setId(id);
        setActiviteitId(activiteitId);
        setType(type);
        setInhoud(inhoud);
        resetTouchedOnNotNull();
    }
}
