/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Domain;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DomainRecord extends UpdatableRecordImpl<DomainRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.domain.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.domain.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.domain.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.domain.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.domain.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.domain.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.domain.scenario_session_id</code>.
     */
    public void setScenarioSessionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.domain.scenario_session_id</code>.
     */
    public Integer getScenarioSessionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DomainRecord
     */
    public DomainRecord() {
        super(Domain.DOMAIN);
    }

    /**
     * Create a detached, initialised DomainRecord
     */
    public DomainRecord(Integer id, String code, String name, Integer scenarioSessionId) {
        super(Domain.DOMAIN);

        setId(id);
        setCode(code);
        setName(name);
        setScenarioSessionId(scenarioSessionId);
        resetTouchedOnNotNull();
    }
}
