/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Field;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FieldRecord extends UpdatableRecordImpl<FieldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.field.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.field.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.field.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.field.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.field.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.field.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FieldRecord
     */
    public FieldRecord() {
        super(Field.FIELD);
    }

    /**
     * Create a detached, initialised FieldRecord
     */
    public FieldRecord(Integer id, String name, Integer activityId) {
        super(Field.FIELD);

        setId(id);
        setName(name);
        setActivityId(activityId);
        resetTouchedOnNotNull();
    }
}
