/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.GebruikerActiviteit;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GebruikerActiviteitRecord extends UpdatableRecordImpl<GebruikerActiviteitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.gebruiker_activiteit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.gebruiker_activiteit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.gebruiker_activiteit.activiteit_id</code>.
     */
    public void setActiviteitId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.gebruiker_activiteit.activiteit_id</code>.
     */
    public Integer getActiviteitId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.gebruiker_activiteit.gebruiker_id</code>.
     */
    public void setGebruikerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.gebruiker_activiteit.gebruiker_id</code>.
     */
    public Integer getGebruikerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lcms.gebruiker_activiteit.gelezen</code>.
     */
    public void setGelezen(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.gebruiker_activiteit.gelezen</code>.
     */
    public Byte getGelezen() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GebruikerActiviteitRecord
     */
    public GebruikerActiviteitRecord() {
        super(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT);
    }

    /**
     * Create a detached, initialised GebruikerActiviteitRecord
     */
    public GebruikerActiviteitRecord(Integer id, Integer activiteitId, Integer gebruikerId, Byte gelezen) {
        super(GebruikerActiviteit.GEBRUIKER_ACTIVITEIT);

        setId(id);
        setActiviteitId(activiteitId);
        setGebruikerId(gebruikerId);
        setGelezen(gelezen);
        resetTouchedOnNotNull();
    }
}
