/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Gebruiker;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GebruikerRecord extends UpdatableRecordImpl<GebruikerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.gebruiker.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.gebruiker.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.gebruiker.inlog_naam</code>.
     */
    public void setInlogNaam(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.gebruiker.inlog_naam</code>.
     */
    public String getInlogNaam() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.gebruiker.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.gebruiker.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.gebruiker.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.gebruiker.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GebruikerRecord
     */
    public GebruikerRecord() {
        super(Gebruiker.GEBRUIKER);
    }

    /**
     * Create a detached, initialised GebruikerRecord
     */
    public GebruikerRecord(Integer id, String inlogNaam, String naam, String passwordHash) {
        super(Gebruiker.GEBRUIKER);

        setId(id);
        setInlogNaam(inlogNaam);
        setNaam(naam);
        setPasswordHash(passwordHash);
        resetTouchedOnNotNull();
    }
}
