/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.InvolvedOrganisation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvolvedOrganisationRecord extends UpdatableRecordImpl<InvolvedOrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.involved_organisation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.involved_organisation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.involved_organisation.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.involved_organisation.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.involved_organisation.organisation_id</code>.
     */
    public void setOrganisationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.involved_organisation.organisation_id</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvolvedOrganisationRecord
     */
    public InvolvedOrganisationRecord() {
        super(InvolvedOrganisation.INVOLVED_ORGANISATION);
    }

    /**
     * Create a detached, initialised InvolvedOrganisationRecord
     */
    public InvolvedOrganisationRecord(Integer id, Integer activityId, Integer organisationId) {
        super(InvolvedOrganisation.INVOLVED_ORGANISATION);

        setId(id);
        setActivityId(activityId);
        setOrganisationId(organisationId);
        resetTouchedOnNotNull();
    }
}
