/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.lcms.data.tables.Log;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogRecord extends UpdatableRecordImpl<LogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.log.table</code>.
     */
    public void setTable_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.log.table</code>.
     */
    public String getTable_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.log.change</code>.
     */
    public void setChange(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.log.change</code>.
     */
    public String getChange() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.log.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.log.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>lcms.log.gametime</code>.
     */
    public void setGametime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.log.gametime</code>.
     */
    public LocalDateTime getGametime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lcms.log.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.log.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(Integer id, String table, String change, LocalDateTime timestamp, LocalDateTime gametime, Integer userId) {
        super(Log.LOG);

        setId(id);
        setTable_(table);
        setChange(change);
        setTimestamp(timestamp);
        setGametime(gametime);
        setUserId(userId);
        resetTouchedOnNotNull();
    }
}
