/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Opschaling;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OpschalingRecord extends UpdatableRecordImpl<OpschalingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.opschaling.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.opschaling.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.opschaling.scenario_sessie_id</code>.
     */
    public void setScenarioSessieId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.opschaling.scenario_sessie_id</code>.
     */
    public Integer getScenarioSessieId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.opschaling.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.opschaling.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.opschaling.naam</code>.
     */
    public void setNaam(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.opschaling.naam</code>.
     */
    public String getNaam() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpschalingRecord
     */
    public OpschalingRecord() {
        super(Opschaling.OPSCHALING);
    }

    /**
     * Create a detached, initialised OpschalingRecord
     */
    public OpschalingRecord(Integer id, Integer scenarioSessieId, String code, String naam) {
        super(Opschaling.OPSCHALING);

        setId(id);
        setScenarioSessieId(scenarioSessieId);
        setCode(code);
        setNaam(naam);
        resetTouchedOnNotNull();
    }
}
