/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Organisation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrganisationRecord extends UpdatableRecordImpl<OrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.organisation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.organisation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.organisation.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.organisation.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.organisation.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.organisation.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.organisation.domain_id</code>.
     */
    public void setDomainId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.organisation.domain_id</code>.
     */
    public Integer getDomainId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationRecord
     */
    public OrganisationRecord() {
        super(Organisation.ORGANISATION);
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(Integer id, String code, String naam, Integer domainId) {
        super(Organisation.ORGANISATION);

        setId(id);
        setCode(code);
        setNaam(naam);
        setDomainId(domainId);
        resetTouchedOnNotNull();
    }
}
