/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Point;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PointRecord extends UpdatableRecordImpl<PointRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.point.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.point.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.point.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.point.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.point.theme_id</code>.
     */
    public void setThemeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.point.theme_id</code>.
     */
    public Integer getThemeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PointRecord
     */
    public PointRecord() {
        super(Point.POINT);
    }

    /**
     * Create a detached, initialised PointRecord
     */
    public PointRecord(Integer id, String content, Integer themeId) {
        super(Point.POINT);

        setId(id);
        setContent(content);
        setThemeId(themeId);
        resetTouchedOnNotNull();
    }
}
