/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Punt;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PuntRecord extends UpdatableRecordImpl<PuntRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.punt.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.punt.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.punt.thema_id</code>.
     */
    public void setThemaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.punt.thema_id</code>.
     */
    public Integer getThemaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.punt.inhoud</code>.
     */
    public void setInhoud(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.punt.inhoud</code>.
     */
    public String getInhoud() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PuntRecord
     */
    public PuntRecord() {
        super(Punt.PUNT);
    }

    /**
     * Create a detached, initialised PuntRecord
     */
    public PuntRecord(Integer id, Integer themaId, String inhoud) {
        super(Punt.PUNT);

        setId(id);
        setThemaId(themaId);
        setInhoud(inhoud);
        resetTouchedOnNotNull();
    }
}
