/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.ScenarioSession;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioSessionRecord extends UpdatableRecordImpl<ScenarioSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.scenario_session.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.scenario_session.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.scenario_session.scenario_id</code>.
     */
    public void setScenarioId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.scenario_session.scenario_id</code>.
     */
    public Integer getScenarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.scenario_session.session_id</code>.
     */
    public void setSessionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.scenario_session.session_id</code>.
     */
    public Integer getSessionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioSessionRecord
     */
    public ScenarioSessionRecord() {
        super(ScenarioSession.SCENARIO_SESSION);
    }

    /**
     * Create a detached, initialised ScenarioSessionRecord
     */
    public ScenarioSessionRecord(Integer id, Integer scenarioId, Integer sessionId) {
        super(ScenarioSession.SCENARIO_SESSION);

        setId(id);
        setScenarioId(scenarioId);
        setSessionId(sessionId);
        resetTouchedOnNotNull();
    }
}
