/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.ScenarioSessie;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioSessieRecord extends UpdatableRecordImpl<ScenarioSessieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.scenario_sessie.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.scenario_sessie.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.scenario_sessie.scenario_id</code>.
     */
    public void setScenarioId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.scenario_sessie.scenario_id</code>.
     */
    public Integer getScenarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.scenario_sessie.sessie_id</code>.
     */
    public void setSessieId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.scenario_sessie.sessie_id</code>.
     */
    public Integer getSessieId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioSessieRecord
     */
    public ScenarioSessieRecord() {
        super(ScenarioSessie.SCENARIO_SESSIE);
    }

    /**
     * Create a detached, initialised ScenarioSessieRecord
     */
    public ScenarioSessieRecord(Integer id, Integer scenarioId, Integer sessieId) {
        super(ScenarioSessie.SCENARIO_SESSIE);

        setId(id);
        setScenarioId(scenarioId);
        setSessieId(sessieId);
        resetTouchedOnNotNull();
    }
}
