/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.lcms.data.tables.Sessie;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessieRecord extends UpdatableRecordImpl<SessieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.sessie.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.sessie.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.sessie.scenario_id</code>.
     */
    public void setScenarioId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.sessie.scenario_id</code>.
     */
    public Integer getScenarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.sessie.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.sessie.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.sessie.locatie</code>.
     */
    public void setLocatie(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.sessie.locatie</code>.
     */
    public String getLocatie() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lcms.sessie.datum_start</code>.
     */
    public void setDatumStart(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.sessie.datum_start</code>.
     */
    public LocalDateTime getDatumStart() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lcms.sessie.datum_eind</code>.
     */
    public void setDatumEind(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.sessie.datum_eind</code>.
     */
    public LocalDateTime getDatumEind() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessieRecord
     */
    public SessieRecord() {
        super(Sessie.SESSIE);
    }

    /**
     * Create a detached, initialised SessieRecord
     */
    public SessieRecord(Integer id, Integer scenarioId, String naam, String locatie, LocalDateTime datumStart, LocalDateTime datumEind) {
        super(Sessie.SESSIE);

        setId(id);
        setScenarioId(scenarioId);
        setNaam(naam);
        setLocatie(locatie);
        setDatumStart(datumStart);
        setDatumEind(datumEind);
        resetTouchedOnNotNull();
    }
}
