/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.lcms.data.tables.Session;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionRecord extends UpdatableRecordImpl<SessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.session.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.session.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.session.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.session.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.session.location</code>.
     */
    public void setLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.session.location</code>.
     */
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.session.date_start</code>.
     */
    public void setDateStart(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.session.date_start</code>.
     */
    public LocalDateTime getDateStart() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>lcms.session.date_end</code>.
     */
    public void setDateEnd(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.session.date_end</code>.
     */
    public LocalDateTime getDateEnd() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lcms.session.scenario_id</code>.
     */
    public void setScenarioId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.session.scenario_id</code>.
     */
    public Integer getScenarioId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRecord
     */
    public SessionRecord() {
        super(Session.SESSION);
    }

    /**
     * Create a detached, initialised SessionRecord
     */
    public SessionRecord(Integer id, String name, String location, LocalDateTime dateStart, LocalDateTime dateEnd, Integer scenarioId) {
        super(Session.SESSION);

        setId(id);
        setName(name);
        setLocation(location);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        setScenarioId(scenarioId);
        resetTouchedOnNotNull();
    }
}
