/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Severity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Nederlands: opschaling, GRIP1, GRIP2, etc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeverityRecord extends UpdatableRecordImpl<SeverityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.severity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.severity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.severity.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.severity.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.severity.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.severity.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.severity.scenario_session_id</code>.
     */
    public void setScenarioSessionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.severity.scenario_session_id</code>.
     */
    public Integer getScenarioSessionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeverityRecord
     */
    public SeverityRecord() {
        super(Severity.SEVERITY);
    }

    /**
     * Create a detached, initialised SeverityRecord
     */
    public SeverityRecord(Integer id, String code, String name, Integer scenarioSessionId) {
        super(Severity.SEVERITY);

        setId(id);
        setCode(code);
        setName(name);
        setScenarioSessionId(scenarioSessionId);
        resetTouchedOnNotNull();
    }
}
