/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Team;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamRecord extends UpdatableRecordImpl<TeamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.team.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.team.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.team.organisatie_id</code>.
     */
    public void setOrganisatieId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.team.organisatie_id</code>.
     */
    public Integer getOrganisatieId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.team.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.team.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.team.naam</code>.
     */
    public void setNaam(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.team.naam</code>.
     */
    public String getNaam() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamRecord
     */
    public TeamRecord() {
        super(Team.TEAM);
    }

    /**
     * Create a detached, initialised TeamRecord
     */
    public TeamRecord(Integer id, Integer organisatieId, String code, String naam) {
        super(Team.TEAM);

        setId(id);
        setOrganisatieId(organisatieId);
        setCode(code);
        setNaam(naam);
        resetTouchedOnNotNull();
    }
}
