/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Theme;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThemeRecord extends UpdatableRecordImpl<ThemeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.theme.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.theme.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.theme.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.theme.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.theme.field_id</code>.
     */
    public void setFieldId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.theme.field_id</code>.
     */
    public Integer getFieldId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThemeRecord
     */
    public ThemeRecord() {
        super(Theme.THEME);
    }

    /**
     * Create a detached, initialised ThemeRecord
     */
    public ThemeRecord(Integer id, String name, Integer fieldId) {
        super(Theme.THEME);

        setId(id);
        setName(name);
        setFieldId(fieldId);
        resetTouchedOnNotNull();
    }
}
