/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Thema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThemaRecord extends UpdatableRecordImpl<ThemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.thema.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.thema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.thema.veld_id</code>.
     */
    public void setVeldId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.thema.veld_id</code>.
     */
    public Integer getVeldId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.thema.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.thema.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThemaRecord
     */
    public ThemaRecord() {
        super(Thema.THEMA);
    }

    /**
     * Create a detached, initialised ThemaRecord
     */
    public ThemaRecord(Integer id, Integer veldId, String naam) {
        super(Thema.THEMA);

        setId(id);
        setVeldId(veldId);
        setNaam(naam);
        resetTouchedOnNotNull();
    }
}
