/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.UserActivity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserActivityRecord extends UpdatableRecordImpl<UserActivityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.user_activity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.user_activity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.user_activity.read</code>.
     */
    public void setRead(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.user_activity.read</code>.
     */
    public Byte getRead() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>lcms.user_activity.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.user_activity.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lcms.user_activity.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.user_activity.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserActivityRecord
     */
    public UserActivityRecord() {
        super(UserActivity.USER_ACTIVITY);
    }

    /**
     * Create a detached, initialised UserActivityRecord
     */
    public UserActivityRecord(Integer id, Byte read, Integer activityId, Integer userId) {
        super(UserActivity.USER_ACTIVITY);

        setId(id);
        setRead(read);
        setActivityId(activityId);
        setUserId(userId);
        resetTouchedOnNotNull();
    }
}
