/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.User;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.user.login_name</code>.
     */
    public void setLoginName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.user.login_name</code>.
     */
    public String getLoginName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lcms.user.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.user.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lcms.user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lcms.user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lcms.user.admin</code>.
     */
    public void setAdmin(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>lcms.user.admin</code>.
     */
    public Byte getAdmin() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>lcms.user.facilitator</code>.
     */
    public void setFacilitator(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lcms.user.facilitator</code>.
     */
    public Byte getFacilitator() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>lcms.user.researcher</code>.
     */
    public void setResearcher(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>lcms.user.researcher</code>.
     */
    public Byte getResearcher() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String loginName, String name, String passwordHash, Byte admin, Byte facilitator, Byte researcher) {
        super(User.USER);

        setId(id);
        setLoginName(loginName);
        setName(name);
        setPasswordHash(passwordHash);
        setAdmin(admin);
        setFacilitator(facilitator);
        setResearcher(researcher);
        resetTouchedOnNotNull();
    }
}
