/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.lcms.data.tables.records;


import nl.tudelft.simulation.lcms.data.tables.Veld;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VeldRecord extends UpdatableRecordImpl<VeldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lcms.veld.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lcms.veld.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lcms.veld.activiteit_id</code>.
     */
    public void setActiviteitId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lcms.veld.activiteit_id</code>.
     */
    public Integer getActiviteitId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lcms.veld.naam</code>.
     */
    public void setNaam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lcms.veld.naam</code>.
     */
    public String getNaam() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VeldRecord
     */
    public VeldRecord() {
        super(Veld.VELD);
    }

    /**
     * Create a detached, initialised VeldRecord
     */
    public VeldRecord(Integer id, Integer activiteitId, String naam) {
        super(Veld.VELD);

        setId(id);
        setActiviteitId(activiteitId);
        setNaam(naam);
        resetTouchedOnNotNull();
    }
}
